

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Locale } from '../types';
import { MERCHANT_TRANSLATIONS } from './merchantTranslations';
import { ONBOARDING_TRANSLATIONS } from './onboardingTranslations';

interface Dictionary {
  [key: string]: {
    [key: string]: string;
  };
}

const DICTIONARY: Dictionary = {
  en: {
    man_loading: 'Loading analytics...',
    man_error: 'Unable to load analytics. Please try again.',
    man_retry: 'Retry',
    man_ai_dashboard: 'AI Insights Dashboard',
    man_ai_dashboard_sub: 'Full AI-powered analysis & predictions',
    man_title: 'Campaign Analytics',
    man_my_insights: 'My Insights',
    man_lifetime: 'Lifetime',
    man_n_days: '{n} Days',
    man_campaigns: 'Campaigns',
    man_active: 'Active',
    man_redeemed: 'Redeemed',
    man_campaign_status: 'Campaign Status',
    man_approved: 'Approved',
    man_in_review: 'In Review',
    man_needs_review: 'Needs Review',
    man_expired: 'Expired',
    man_campaign_trend: 'Campaign Trend',
    man_lifetime_analytics: 'Lifetime Analytics',
    man_loading_lifetime: 'Loading lifetime data...',
    man_total_clicks: 'Total Clicks',
    man_conversion_rate: 'Conversion Rate',
    man_invites_sent: 'Invites Sent',
    man_invites_accepted: 'Invites Accepted',
    man_customer_loyalty: 'Customer Loyalty',
    man_no_redemption: 'No redemption data yet. Customers who redeem your deals will appear here.',
    man_total_customers: 'Total Customers',
    man_repeat: 'Repeat',
    man_repeat_rate: 'Repeat Rate',
    man_redemption_frequency: 'Redemption Frequency',
    man_1_time: '1 time',
    man_2_times: '2 times',
    man_3_5_times: '3-5 times',
    man_6_plus_times: '6+ times',
    man_top_loyal: 'Top Loyal Customers',
    man_customer: 'Customer',
    man_n_different_deals: '{n} different deals',
    man_avg_redemptions: 'Avg {n} redemptions per customer',
    man_unable_customer: 'Unable to load customer data.',
    man_product_catalogue: 'Product Catalogue',
    man_products: 'Products',
    man_views: 'Views',
    man_likes: 'Likes',
    man_top_performers: 'Top Performers',
    man_no_product_data: 'No product data yet',
    man_smart_insights: 'Smart Insights',
    man_top_category: 'Top Category',
    man_top_category_tip: 'Focus on adding more products in this category',
    man_avg_performance: 'Avg Performance',
    man_views_per_product: 'views/product',
    man_likes_per_product: 'likes/product',
    man_needs_attention: 'Needs Attention',
    man_n_products: '{n} products',
    man_needs_attention_tip: 'Update images or descriptions to boost engagement',
    man_performance_score: 'Performance Score',
    man_score_breakdown: 'Score Breakdown',
    man_quick_wins: 'Quick Wins',
    man_view_ai_dashboard: 'View AI Insights Dashboard',
    man_calculating_score: 'Calculating your performance score...',
    man_ai_recommendations: 'AI Recommendations',
    man_ai_analyzing: 'AI is analyzing your data...',
    man_ai_analyzing_sub: 'Insights will appear as you add products and create deals',
    man_grade_excellent: 'Excellent',
    man_grade_good: 'Good',
    man_grade_fair: 'Fair',
    man_grade_needs_improvement: 'Needs Improvement',
    man_impact_high: 'high',
    man_impact_medium: 'medium',
    man_impact_low: 'low',
    mnav_console: 'Console',
    mnav_campaigns: 'Campaigns',
    mnav_catalogue: 'Catalogue',
    mnav_dotd: 'Deal of Day',
    mnav_intel: 'Intel',
    mnav_hub: 'Hub',
    app_name: 'DealPro',
    login_header: 'Smart Discovery',
    login_sub: 'Unlock exclusive Deals & Discounts near you.',
    login_placeholder_id: 'Username / Email',
    login_placeholder_pass: 'Password',
    login_btn: 'Sign in',
    login_forgot: 'Forgot password?',
    login_register_hint: 'New to DealPro?',
    login_register_action: 'Create Account',
    home_deals: 'Deals',
    home_near_you: 'NEAR YOU',
    home_daily_waves: 'Daily WAVES',
    home_see_all: 'See all deals in',
    home_adjust_range: 'ADJUST RANGE',
    lang_select_title: 'Select Language',
    lang_select_sub: 'Choose your language for better experience',
    reg_title: 'JOIN THE GRID',
    reg_consumer: 'Consumer',
    reg_merchant: 'Merchant',
    reg_choose_account: 'Choose your account type to get started',
    reg_consumer_desc: 'Join the network to discover local deals and save money',
    reg_merchant_desc: 'Empower your business with DealPro digital waves',
    reg_have_account: 'Already have an account?',
    reg_back_login: 'Back to Login',
    reg_fullname: 'Full Name',
    reg_username: 'Username',
    reg_email: 'Email Address',
    reg_password: 'Password',
    reg_is_owner: 'Are you Store Owner',
    reg_brand: 'Main Store Name - GST Registered',
    reg_category: 'Business Category',
    reg_locations: 'Retail Store Locations',
    reg_store_name_label: 'Store Name (e.g., Main Street Branch)', // NEW
    reg_street: 'Street Address',
    reg_state: 'State',
    reg_city: 'City',
    reg_hours: 'Operating Hours',
    reg_24h: '24 Hrs',
    reg_opens: 'Opens',
    reg_closes: 'Closes',
    reg_landmark: 'Landmark (Optional)',
    reg_use_my_loc: 'Use My Location',
    reg_sync_verified: 'Sync Verified',
    reg_add_outlet: 'Add Another Outlet',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN Card',
    reg_submit: 'Create my account',
    reg_verify: 'Verify',
    loc_title: 'Discovery Parameters',
    loc_sub: 'Grid Scanning Logic',
    loc_radius: 'Search Radius',
    loc_gps: 'GPS Tracking',
    loc_manual: 'Manual Grid',
    loc_region: 'Select Region',
    loc_city: 'Select City',
    loc_area: 'Select Area',
    loc_scan_btn: 'Scan Area',
    loc_syncing: 'Syncing Localities...',
    loc_resolving: 'Resolving Coordinates',
    loc_locked: 'Signal Locked',
    loc_awaiting: 'Awaiting Location',
    onboarding_1_headline: "Hyper-Local Discovery",
    onboarding_1_sub: "Pinpoint exclusive retail opportunities in your immediate vicinity with precision GPS logic.",
    onboarding_1_tag: "Proximity Intelligence",
    onboarding_2_headline: "Real-Time Flash Sales",
    onboarding_2_sub: "Synchronize with active merchant waves and capture high-value incentives before they expire.",
    onboarding_2_tag: "Temporal Efficiency",
    onboarding_3_headline: "Institutional Trust",
    onboarding_3_sub: "Verified nodes and secure voucher protocols ensure a premium local shopping experience.",
    onboarding_3_tag: "Grid Security",
    home_daily: "Today's Deal",
    home_local_area: 'Local Area',
    home_your_area: 'Your Area',
    home_your_city: 'Your City',
    home_your_sector: 'Your Sector',
    home_for_you: 'For You',
    home_nearby_deals: 'Nearby Deals',
    home_all_deals: 'All Deals',
    home_your_insights: 'Your Insights',
    insight_love_category: 'You love {category} deals - {count} claimed!',
    insight_nearby_deals: '{count} great deals near you right now',
    insight_new_deals: '{count} fresh deals launched this week',
    insight_redeemed: "You've redeemed {count} deals - great saver!",
    insight_no_deals: 'No active deals available right now',
    home_deal_singular: 'deal',
    home_deals_plural: 'deals',
    home_in: 'in',
    home_no_deals_sector: 'No active waves in this sector.',
    home_view_all: 'VIEW ALL',
    home_syncing_grid: 'Syncing Grid',
    details_redeem_btn: 'REDEEM NOW',
    details_verifying: 'Verifying...',
    details_activating_for: 'Activating Reward For:',
    details_protocol: 'Campaign Protocol',
    details_visit_intel: 'Visit Intelligence',
    details_start_gps: 'Start GPS',
    details_coordinates: 'Store Coordinates',
    details_landmark: 'Proximity Landmark',
    details_op_window: 'Operational Window',
    details_verified_node: 'Verified DealPro Node',
    details_instance_id: 'INSTANCE ID',
    details_id_verified: 'Identity Verified',
    details_present_counter: 'Present at node counter',
    details_exit_btn: 'Exit Dashboard',
    history_title_1: 'Redemption',
    history_title_2: 'History',
    history_sub: 'Your Redemptions',
    history_active_nodes: 'results',
    history_rewards_label: 'Rewards',
    history_tab_all: 'All Rewards',
    history_tab_pending: 'Awaiting Visit',
    history_syncing: 'Syncing Redemptions...',
    history_empty_title: 'Vault Synchronized',
    history_empty_sub_pending: 'All deals are verified. No pending store visits detected.',
    history_empty_sub_all: 'No activation records found in this identity sector.',
    history_search_btn: 'Explore Grid',
    history_status_verified: 'Visit Verified',
    history_status_awaiting: 'Awaiting Visit',
    history_page_label: 'Page',
    history_of: 'of',
    history_ledger_end: 'Secure Grid Ledger End',
    history_voucher_security: 'Voucher Security',
    history_transaction_logged: 'Transaction Logged',
    history_present_counter: 'Present at counter',
    history_ref_label: 'REF',
    history_voucher_node: 'Voucher Node',
    history_rate_exp: 'Rate Experience',
    status_live: 'Live',
    status_expired: 'Expired',
    favorites_title_1: 'Your',
    favorites_title_2: 'Favorites',
    favorites_sub: 'Access your saved deals anytime',
    favorites_syncing: 'Syncing Vault Data',
    favorites_empty_title: 'Vault Empty',
    favorites_empty_sub: 'Capture exclusive deals by tapping the heart icon in discovery mode.',
    profile_elite_member: 'Elite Member',
    profile_verif_hub: 'Verification Hub',
    profile_verif_sub: 'Verify store visits',
    profile_edit: 'Edit Profile',
    profile_edit_store: 'Edit Store Profile',
    profile_favs: 'My Favorites',
    profile_invite_friend: 'Invite a Friend',
    profile_invite_partner: 'Invite a Partner',
    profile_invite_placeholder: 'Email or phone number',
    profile_invite_success: 'Invite sent to your friend',
    profile_help: 'Help & Feedback',
    profile_support_hub: 'Support Hub',
    profile_console: 'Store Console',
    profile_payments: 'Payments',
    profile_subscriptions: 'My Subscriptions',
    profile_bank_verification: 'Bank Verification', // NEW translation key
    profile_verified_merchant: 'Verified Merchant',
    store_search_title: 'Store', // NEW
    store_search_sub: 'Discovery', // NEW
    store_search_hint: 'Locate specific retail nodes', // NEW
    store_search_placeholder: 'Search store name or address', // NEW
    store_search_no_results: 'No stores found.', // NEW
    store_search_adjust_query: 'Try adjusting your search query.', // NEW
  },
  kn: {
    man_loading: 'ವಿಶ್ಲೇಷಣೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    man_error: 'ವಿಶ್ಲೇಷಣೆ ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    man_retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    man_ai_dashboard: 'AI ಒಳನೋಟ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    man_ai_dashboard_sub: 'ಪೂರ್ಣ AI ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಮುನ್ಸೂಚನೆ',
    man_title: 'ಅಭಿಯಾನ ವಿಶ್ಲೇಷಣೆ',
    man_my_insights: 'ನನ್ನ ಒಳನೋಟಗಳು',
    man_lifetime: 'ಒಟ್ಟಾರೆ',
    man_n_days: '{n} ದಿನಗಳು',
    man_campaigns: 'ಅಭಿಯಾನಗಳು',
    man_active: 'ಸಕ್ರಿಯ',
    man_redeemed: 'ಬಳಸಲಾಗಿದೆ',
    man_campaign_status: 'ಅಭಿಯಾನ ಸ್ಥಿತಿ',
    man_approved: 'ಅನುಮೋದಿತ',
    man_in_review: 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
    man_needs_review: 'ಪರಿಶೀಲನೆ ಬೇಕು',
    man_expired: 'ಅವಧಿ ಮುಗಿದಿದೆ',
    man_campaign_trend: 'ಅಭಿಯಾನ ಪ್ರವೃತ್ತಿ',
    man_lifetime_analytics: 'ಒಟ್ಟಾರೆ ವಿಶ್ಲೇಷಣೆ',
    man_loading_lifetime: 'ಒಟ್ಟಾರೆ ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    man_total_clicks: 'ಒಟ್ಟು ಕ್ಲಿಕ್‌ಗಳು',
    man_conversion_rate: 'ಪರಿವರ್ತನೆ ದರ',
    man_invites_sent: 'ಕಳುಹಿಸಿದ ಆಹ್ವಾನಗಳು',
    man_invites_accepted: 'ಸ್ವೀಕರಿಸಿದ ಆಹ್ವಾನಗಳು',
    man_customer_loyalty: 'ಗ್ರಾಹಕ ನಿಷ್ಠೆ',
    man_no_redemption: 'ಇನ್ನೂ ಬಳಕೆ ಡೇಟಾ ಇಲ್ಲ. ನಿಮ್ಮ ಕೊಡುಗೆ ಬಳಸುವ ಗ್ರಾಹಕರು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತಾರೆ.',
    man_total_customers: 'ಒಟ್ಟು ಗ್ರಾಹಕರು',
    man_repeat: 'ಪುನರಾವರ್ತಿತ',
    man_repeat_rate: 'ಪುನರಾವರ್ತನೆ ದರ',
    man_redemption_frequency: 'ಬಳಕೆ ಆವರ್ತನ',
    man_1_time: '1 ಬಾರಿ',
    man_2_times: '2 ಬಾರಿ',
    man_3_5_times: '3-5 ಬಾರಿ',
    man_6_plus_times: '6+ ಬಾರಿ',
    man_top_loyal: 'ಅತಿ ನಿಷ್ಠ ಗ್ರಾಹಕರು',
    man_customer: 'ಗ್ರಾಹಕ',
    man_n_different_deals: '{n} ವಿಭಿನ್ನ ಕೊಡುಗೆಗಳು',
    man_avg_redemptions: 'ಪ್ರತಿ ಗ್ರಾಹಕನಿಗೆ ಸರಾಸರಿ {n} ಬಳಕೆ',
    man_unable_customer: 'ಗ್ರಾಹಕ ಡೇಟಾ ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ.',
    man_product_catalogue: 'ಉತ್ಪನ್ನ ಪಟ್ಟಿ',
    man_products: 'ಉತ್ಪನ್ನಗಳು',
    man_views: 'ವೀಕ್ಷಣೆಗಳು',
    man_likes: 'ಇಷ್ಟಗಳು',
    man_top_performers: 'ಅಗ್ರ ಸಾಧಕರು',
    man_no_product_data: 'ಇನ್ನೂ ಉತ್ಪನ್ನ ಡೇಟಾ ಇಲ್ಲ',
    man_smart_insights: 'ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳು',
    man_top_category: 'ಅಗ್ರ ವರ್ಗ',
    man_top_category_tip: 'ಈ ವರ್ಗದಲ್ಲಿ ಹೆಚ್ಚು ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಲು ಗಮನಿಸಿ',
    man_avg_performance: 'ಸರಾಸರಿ ಸಾಧನೆ',
    man_views_per_product: 'ವೀಕ್ಷಣೆ/ಉತ್ಪನ್ನ',
    man_likes_per_product: 'ಇಷ್ಟ/ಉತ್ಪನ್ನ',
    man_needs_attention: 'ಗಮನ ಬೇಕು',
    man_n_products: '{n} ಉತ್ಪನ್ನಗಳು',
    man_needs_attention_tip: 'ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ ಹೆಚ್ಚಿಸಲು ಚಿತ್ರ ಅಥವಾ ವಿವರಣೆ ನವೀಕರಿಸಿ',
    man_performance_score: 'ಸಾಧನೆ ಅಂಕ',
    man_score_breakdown: 'ಅಂಕ ವಿವರ',
    man_quick_wins: 'ತ್ವರಿತ ಗೆಲುವುಗಳು',
    man_view_ai_dashboard: 'AI ಒಳನೋಟ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ನೋಡಿ',
    man_calculating_score: 'ನಿಮ್ಮ ಸಾಧನೆ ಅಂಕ ಲೆಕ್ಕ ಹಾಕುತ್ತಿದೆ...',
    man_ai_recommendations: 'AI ಶಿಫಾರಸುಗಳು',
    man_ai_analyzing: 'AI ನಿಮ್ಮ ಡೇಟಾ ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    man_ai_analyzing_sub: 'ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಿ ಕೊಡುಗೆ ರಚಿಸಿದಂತೆ ಒಳನೋಟಗಳು ಕಾಣಿಸುತ್ತವೆ',
    man_grade_excellent: 'ಅತ್ಯುತ್ತಮ',
    man_grade_good: 'ಉತ್ತಮ',
    man_grade_fair: 'ಸಾಧಾರಣ',
    man_grade_needs_improvement: 'ಸುಧಾರಣೆ ಬೇಕು',
    man_impact_high: 'ಹೆಚ್ಚು',
    man_impact_medium: 'ಮಧ್ಯಮ',
    man_impact_low: 'ಕಡಿಮೆ',
    mnav_console: 'ಕನ್ಸೋಲ್',
    mnav_campaigns: 'ಅಭಿಯಾನಗಳು',
    mnav_catalogue: 'ಕ್ಯಾಟಲಾಗ್',
    mnav_dotd: 'ಇಂದಿನ ಡೀಲ್',
    mnav_intel: 'ವಿಶ್ಲೇಷಣೆ',
    mnav_hub: 'ಪ್ರೊಫೈಲ್',
    app_name: 'ಡೀಲ್‌ಪ್ರೊ',
    login_header: 'ಸ್ಮಾರ್ಟ್ ಅನ್ವೇಷಣೆ',
    login_sub: 'ನಿಮ್ಮ ಹತ್ತಿರವಿರುವ ವಿಶೇಷ ಡೀಲ್‌ಗಳು ಮತ್ತು ರಿಯಾಯಿತಿಗಳನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಿ.',
    login_placeholder_id: 'ಬಳಕೆದಾರಹೆಸರು / ಇಮೇಲ್',
    login_placeholder_pass: 'ಪಾಸ್‌ವರ್ಡ್',
    login_btn: 'ಸೈನ್ ಇನ್',
    login_forgot: 'ರುಜುವಾತುಗಳನ್ನು ಮರೆತಿರುವಿರಾ?',
    login_register_hint: 'ಗ್ರಿಡ್‌ಗೆ ಹೊಸಬರೇ?',
    login_register_action: 'ಗುರುತನ್ನು ಸ್ಥಾಪಿಸಿ',
    home_deals: 'ಡೀಲ್‌ಗಳು',
    home_near_you: 'ನಿಮ್ಮ ಹತ್ತಿರ',
    home_daily_waves: 'ದೈನಂದಿನ ವೇವ್ಸ್',
    home_see_all: 'ಎಲ್ಲಾ ಡೀಲ್‌ಗಳನ್ನು ಇಲ್ಲಿ ನೋಡಿ',
    home_adjust_range: 'ಶ್ರೇಣಿಯನ್ನು ಹೊಂದಿಸಿ',
    lang_select_title: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    lang_select_sub: 'ಉತ್ತಮ ಅನುಭವಕ್ಕಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    reg_title: 'ಗ್ರಿಡ್‌ಗೆ ಸೇರಿ',
    reg_consumer: 'ಗ್ರಾಹಕ',
    reg_merchant: 'ವ್ಯಾಪಾರಿ',
    reg_choose_account: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಖಾತೆ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ',
    reg_consumer_desc: 'ಸ್ಥಳೀಯ ಡೀಲ್‌ಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಮತ್ತು ಹಣವನ್ನು ಉಳಿಸಲು ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ',
    reg_merchant_desc: 'DealPro ಡಿಜಿಟಲ್ ತರಂಗಗಳೊಂದಿಗೆ ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಸಬಲಗೊಳಿಸಿ',
    reg_have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
    reg_back_login: 'ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    reg_fullname: 'ಪೂರ್ಣ ಹೆಸರು',
    reg_username: 'ಬಳಕೆದಾರಹೆಸರು',
    reg_email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    reg_password: 'ಪಾಸ್‌ವರ್ಡ್',
    reg_is_owner: 'ನೀವು ಅಂಗಡಿ ಮಾಲೀಕರೆ?',
    reg_brand: 'ಮುಖ್ಯ ಅಂಗಡಿ ಹೆಸರು - GST ನೋಂದಾಯಿತ',
    reg_category: 'ವ್ಯಾಪಾರ ವರ್ಗ',
    reg_locations: 'ಚಿಲ್ಲರೆ ಅಂಗಡಿ ಸ್ಥಳಗಳು',
    reg_store_name_label: 'ಅಂಗಡಿ ಹೆಸರು (ಉದಾ. ಮುಖ್ಯ ರಸ್ತೆ ಶಾಖೆ)', // NEW
    reg_street: 'ಬೀದಿ ವಿಳಾಸ',
    reg_state: 'ರಾಜ್ಯ',
    reg_city: 'ನಗರ',
    reg_hours: 'ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಸಮಯ',
    reg_24h: '24 ಗಂಟೆ',
    reg_opens: 'ತೆರೆಯುತ್ತದೆ',
    reg_closes: 'ಮುಚ್ಚುತ್ತದೆ',
    reg_landmark: 'ಗುರುತು (ಐಚ್ಛಿಕ)',
    reg_use_my_loc: 'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ',
    reg_sync_verified: 'ಸಿಂಕ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    reg_add_outlet: 'ಇನ್ನೊಂದು ಮಳಿಗೆ ಸೇರಿಸಿ',
    reg_gstin: 'GSTIN',
    reg_pan: 'ಪ್ಯಾನ್ ಕಾರ್ಡ್',
    reg_submit: 'ನನ್ನ ಖಾತೆ ರಚಿಸಿ',
    reg_verify: 'ಪರಿಶೀಲಿಸಿ',
    loc_title: 'ಅನ್ವೇಷಣೆಯ ನಿಯತಾಂಕಗಳು',
    loc_sub: 'ಗ್ರಿಡ್ ಸ್ಕ್ಯಾನಿಂಗ್ ತರ್ಕ',
    loc_radius: 'ಹುಡುಕಾಟದ ತ್ರಿಜ್ಯ',
    loc_gps: 'ಜಿಪಿಎಸ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    loc_manual: 'ಮ್ಯಾನ್ಯುವಲ್ ಗ್ರಿಡ್',
    loc_region: 'ಪ್ರದೇಶವನ್ನು ಆರಿಸಿ',
    loc_city: 'ನಗರವನ್ನು ಆರಿಸಿ',
    loc_area: 'ಸ್ಥಳವನ್ನು ಆರಿಸಿ',
    loc_scan_btn: 'ಪ್ರದೇಶವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    loc_syncing: 'ಸಿಂಕ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    loc_resolving: 'ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ',
    loc_locked: 'ಸಿಗ್ನಲ್ ಲಾಕ್ ಆಗಿದೆ',
    loc_awaiting: 'ಸ್ಥಳಕ್ಕಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    onboarding_1_headline: "ಸ್ಥಳೀಯ ಅನ್ವೇಷಣೆ",
    onboarding_1_sub: "ನಿಖರವಾದ ಜಿಪಿಎಸ್ ತರ್ಕದೊಂದಿಗೆ ನಿಮ್ಮ ಸಮೀಪದಲ್ಲಿರುವ ವಿಶೇಷ ಚಿಲ್ಲರೆ ಅವಕಾಶಗಳನ್ನು ಗುರುತಿಸಿ.",
    onboarding_1_tag: "ಸ್ಥಳೀಯ ಬುದ್ಧಿವಂತಿಕೆ",
    onboarding_2_headline: "ತಕ್ಷಣದ ಮಾರಾಟ",
    onboarding_2_sub: "ಸಕ್ರಿಯ ವ್ಯಾಪಾರಿ ಕೊಡುಗೆಗಳೊಂದಿಗೆ ಸಿಂಕ್ ಮಾಡಿ ಮತ್ತು ಅವು ಮುಕ್ತಾಯಗೊಳ್ಳುವ ಮೊದಲೇ ಪಡೆದುಕೊಳ್ಳಿ.",
    onboarding_2_tag: "ಸಮಯದ ದಕ್ಷತೆ",
    onboarding_3_headline: "ಸಂಸ್ಥೆಯ ನಂಬಿಕೆ",
    onboarding_3_sub: "ಪರಿಶೀಲಿಸಿದ ನೋಡ್‌ಗಳು ಮತ್ತು ಸುರಕ್ಷಿತ ವೋಚರ್ ಪ್ರೋಟೋಕಾಲ್‌ಗಳು ಪ್ರೀಮಿಯಂ ಶಾಪಿಂಗ್ ಅನುಭವವನ್ನು ಖಚಿತಪಡಿಸುತ್ತವೆ.",
    onboarding_3_tag: "ಗ್ರಿಡ್ ಭದ್ರತೆ",
    home_daily: 'ಇಂದಿನ ಡೀಲ್',
    home_local_area: 'ಸ್ಥಳೀಯ ಪ್ರದೇಶ',
    home_your_area: 'ನಿಮ್ಮ ಪ್ರದೇಶ',
    home_your_city: 'ನಿಮ್ಮ ನಗರ',
    home_your_sector: 'ನಿಮ್ಮ ವಲಯ',
    home_for_you: 'ನಿಮಗಾಗಿ',
    home_nearby_deals: 'ಹತ್ತಿರದ ಕೊಡುಗೆಗಳು',
    home_all_deals: 'ಎಲ್ಲಾ ಕೊಡುಗೆಗಳು',
    home_your_insights: 'ನಿಮ್ಮ ಒಳನೋಟಗಳು',
    insight_love_category: 'ನೀವು {category} ಕೊಡುಗೆಗಳನ್ನು ಪ್ರೀತಿಸುತ್ತೀರಿ - {count} ಪಡೆದಿದ್ದೀರಿ!',
    insight_nearby_deals: 'ಈಗ ನಿಮ್ಮ ಹತ್ತಿರ {count} ಉತ್ತಮ ಕೊಡುಗೆಗಳು',
    insight_new_deals: 'ಈ ವಾರ ಹೊಸದಾಗಿ ಪ್ರಾರಂಭವಾದ {count} ಕೊಡುಗೆಗಳು',
    insight_redeemed: 'ನೀವು {count} ಕೊಡುಗೆಗಳನ್ನು ರಿಡೀಮ್ ಮಾಡಿದ್ದೀರಿ - ಅತ್ಯುತ್ತಮ ಉಳಿತಾಯಕಾರ!',
    insight_no_deals: 'ಈಗ ಯಾವುದೇ ಸಕ್ರಿಯ ಕೊಡುಗೆಗಳು ಲಭ್ಯವಿಲ್ಲ',
    home_deal_singular: 'ಕೊಡುಗೆ',
    home_deals_plural: 'ಕೊಡುಗೆಗಳು',
    home_in: 'ನಲ್ಲಿ',
    home_no_deals_sector: 'ಈ ವಲಯದಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ಕೊಡುಗೆಗಳಿಲ್ಲ.',
    home_view_all: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    home_syncing_grid: 'ಗ್ರಿಡ್ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ',
    details_redeem_btn: 'ಈಗಲೇ ಪಡೆದುಕೊಳ್ಳಿ',
    details_verifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    details_activating_for: 'ಬಹುಮಾನವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲಾಗುತ್ತಿದೆ:',
    details_protocol: 'ಕಾರ್ಯಕ್ರಮದ ಶಿಷ್ಟಾಚಾರ',
    details_visit_intel: 'ಸ್ಥಳದ ಮಾಹಿತಿ',
    details_start_gps: 'ಜಿಪಿಎಸ್ ಪ್ರಾರಂಭಿಸಿ',
    details_coordinates: 'ಅಂಗಡಿಯ ವಿಳಾಸ',
    details_landmark: 'ಹತ್ತಿರದ ಗುರುತು',
    details_op_window: 'ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಸಮಯ',
    details_verified_node: 'ಪರಿಶೀಲಿಸಿದ ಡೀಲ್‌ಪ್ರೊ ಕೇಂದ್ರ',
    details_instance_id: 'ಐಡಿ ಸಂಖ್ಯೆ',
    details_id_verified: 'ಗುರುತು ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    details_present_counter: 'ಕೌಂಟರ್‌ನಲ್ಲಿ ತೋರಿಸಿ',
    details_exit_btn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಧಿನಿಂದ ನಿರ್ಗಮಿಸಿ',
    history_title_1: 'ಪಡೆದುಕೊಂಡ',
    history_title_2: 'ಇತಿಹಾಸ',
    history_sub: 'ನಿಮ್ಮ ಕೊಡುಗೆಗಳು',
    history_active_nodes: 'ಫಲಿತಾಂಶಗಳು',
    history_rewards_label: 'ಬಹುಮಾನಗಳು',
    history_tab_all: 'ಎಲ್ಲಾ ಬಹುಮಾನಗಳು',
    history_tab_pending: 'ಭೇಟಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    history_syncing: 'ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    history_empty_title: 'ವಾಲ್ಟ್ ಸಿಂಕ್ ಆಗಿದೆ',
    history_empty_sub_pending: 'ಎಲ್ಲಾ ಡೀಲ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ. ಯಾವುದೇ ಬಾಕಿ ಇರುವ ಅಂಗಡಿ ಭೇಟಿಗಳಿಲ್ಲ.',
    history_empty_sub_all: 'ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಯಾವುದೇ ಬಹುಮಾನಗಳ ದಾಖಲೆ ಇಲ್ಲ.',
    history_search_btn: 'ಗ್ರಿಡ್ ಅನ್ವೇಷಿಸಿ',
    history_status_verified: 'ಭೇಟಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    history_status_awaiting: 'ಭೇಟಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    history_page_label: 'ಪುಟ',
    history_of: 'ರಲ್ಲಿ',
    history_ledger_end: 'ದಾಖಲೆ ಮುಕ್ತಾಯ',
    history_voucher_security: 'ವೋಚರ್ ಭದ್ರತೆ',
    history_transaction_logged: 'ವಹಿವಾಟು ದಾಖಲಾಗಿದೆ',
    history_present_counter: 'ಕೌಂಟರ್‌ನಲ್ಲಿ ತೋರಿಸಿ',
    history_ref_label: 'REF',
    history_voucher_node: 'ವೋಚರ್ ಕೇಂದ್ರ',
    history_rate_exp: 'ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ',
    status_live: 'ಲೈವ್',
    status_expired: 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
    favorites_title_1: 'ನಿಮ್ಮ',
    favorites_title_2: 'ಮೆಚ್ಚಿನವುಗಳು',
    favorites_sub: 'ನಿಮ್ಮ ಉಳಿಸಿದ ಕೊಡುಗೆಗಳನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ವೀಕ್ಷಿಸಿ',
    favorites_syncing: 'ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ',
    favorites_empty_title: 'ಯಾವುದೂ ಇಲ್ಲ',
    favorites_empty_sub: 'ಅನ್ವೇಷಣೆಯಲ್ಲಿ ಹಾರ್ಟ್ ಐಕಾನ್ ಒತ್ತುವ ಮೂಲಕ ಕೊಡುಗೆಗಳನ್ನು ಉಳಿಸಿ.',
    profile_elite_member: 'ಗಣ್ಯ ಸದಸ್ಯ',
    profile_verif_hub: 'ಪರಿಶೀಲನಾ ಹಬ್',
    profile_verif_sub: 'ಭೇಟಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    profile_edit: 'ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ',
    profile_edit_store: 'ಅಂಗಡಿ ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ',
    profile_favs: 'ನನ್ನ ಮೆಚ್ಚಿನವುಗಳು',
    profile_invite_friend: 'ಸ್ನೇಹಿತರನ್ನು ಆಹ್ವಾನಿಸಿ',
    profile_invite_partner: 'ಪಾಲುದಾರರನ್ನು ಆಹ್ವಾನಿಸಿ',
    profile_invite_placeholder: 'ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ',
    profile_invite_success: 'ಆಹ್ವಾನವನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ',
    profile_help: 'ಸಹಾಯ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ',
    profile_support_hub: 'ಬೆಂಬಲ ಕೇಂದ್ರ',
    profile_console: 'ಅಂಗಡಿ ಕನ್ಸೋಲ್',
    profile_payments: 'ಪಾವತಿಗಳು',
    profile_subscriptions: 'ನನ್ನ ಚಂದಾದಾರಿಕೆಗಳು',
    profile_bank_verification: 'ಬ್ಯಾಂಕ್ ಪರಿಶೀಲನೆ', // NEW translation key
    profile_verified_merchant: 'ಪರಿಶೀಲಿಸಿದ ವ್ಯಾಪಾರಿ',
    store_search_title: 'ಸ್ಟೋರ್', // NEW
    store_search_sub: 'ಅನ್ವೇಷಣೆ', // NEW
    store_search_hint: 'ನಿರ್ದಿಷ್ಟ ಚಿಲ್ಲರೆ ಕೇಂದ್ರಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ', // NEW
    store_search_placeholder: 'ಸ್ಟೋರ್ ಹೆಸರು ಅಥವಾ ವಿಳಾಸವನ್ನು ಹುಡುಕಿ', // NEW
    store_search_no_results: 'ಯಾವುದೇ ಅಂಗಡಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', // NEW
    store_search_adjust_query: 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಪ್ರಶ್ನೆಯನ್ನು ಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.', // NEW
  },
  hi: {
    man_loading: 'एनालिटिक्स लोड हो रहा है...',
    man_error: 'एनालिटिक्स लोड नहीं हो सका। कृपया फिर से कोशिश करें।',
    man_retry: 'फिर से करें',
    man_ai_dashboard: 'AI इनसाइट्स डैशबोर्ड',
    man_ai_dashboard_sub: 'पूर्ण AI-आधारित विश्लेषण और भविष्यवाणी',
    man_title: 'कैंपेन एनालिटिक्स',
    man_my_insights: 'मेरी इनसाइट्स',
    man_lifetime: 'आजीवन',
    man_n_days: '{n} दिन',
    man_campaigns: 'कैंपेन',
    man_active: 'सक्रिय',
    man_redeemed: 'रिडीम किए',
    man_campaign_status: 'कैंपेन स्थिति',
    man_approved: 'स्वीकृत',
    man_in_review: 'समीक्षा में',
    man_needs_review: 'समीक्षा चाहिए',
    man_expired: 'समाप्त',
    man_campaign_trend: 'कैंपेन रुझान',
    man_lifetime_analytics: 'आजीवन एनालिटिक्स',
    man_loading_lifetime: 'आजीवन डेटा लोड हो रहा है...',
    man_total_clicks: 'कुल क्लिक',
    man_conversion_rate: 'कन्वर्जन दर',
    man_invites_sent: 'भेजे गए निमंत्रण',
    man_invites_accepted: 'स्वीकृत निमंत्रण',
    man_customer_loyalty: 'ग्राहक वफादारी',
    man_no_redemption: 'अभी कोई रिडेम्पशन डेटा नहीं। आपके डील रिडीम करने वाले ग्राहक यहाँ दिखेंगे।',
    man_total_customers: 'कुल ग्राहक',
    man_repeat: 'दोहराने वाले',
    man_repeat_rate: 'रिपीट दर',
    man_redemption_frequency: 'रिडेम्पशन आवृत्ति',
    man_1_time: '1 बार',
    man_2_times: '2 बार',
    man_3_5_times: '3-5 बार',
    man_6_plus_times: '6+ बार',
    man_top_loyal: 'सबसे वफादार ग्राहक',
    man_customer: 'ग्राहक',
    man_n_different_deals: '{n} अलग-अलग डील',
    man_avg_redemptions: 'प्रति ग्राहक औसत {n} रिडेम्पशन',
    man_unable_customer: 'ग्राहक डेटा लोड नहीं हो सका।',
    man_product_catalogue: 'उत्पाद सूची',
    man_products: 'उत्पाद',
    man_views: 'व्यू',
    man_likes: 'लाइक',
    man_top_performers: 'टॉप परफॉर्मर',
    man_no_product_data: 'अभी कोई उत्पाद डेटा नहीं',
    man_smart_insights: 'स्मार्ट इनसाइट्स',
    man_top_category: 'टॉप श्रेणी',
    man_top_category_tip: 'इस श्रेणी में और उत्पाद जोड़ने पर ध्यान दें',
    man_avg_performance: 'औसत प्रदर्शन',
    man_views_per_product: 'व्यू/उत्पाद',
    man_likes_per_product: 'लाइक/उत्पाद',
    man_needs_attention: 'ध्यान चाहिए',
    man_n_products: '{n} उत्पाद',
    man_needs_attention_tip: 'एंगेजमेंट बढ़ाने के लिए इमेज या विवरण अपडेट करें',
    man_performance_score: 'प्रदर्शन स्कोर',
    man_score_breakdown: 'स्कोर विवरण',
    man_quick_wins: 'आसान सुधार',
    man_view_ai_dashboard: 'AI इनसाइट्स डैशबोर्ड देखें',
    man_calculating_score: 'आपका प्रदर्शन स्कोर निकाला जा रहा है...',
    man_ai_recommendations: 'AI सुझाव',
    man_ai_analyzing: 'AI आपका डेटा विश्लेषण कर रहा है...',
    man_ai_analyzing_sub: 'उत्पाद जोड़ने और डील बनाने पर इनसाइट्स दिखेंगी',
    man_grade_excellent: 'उत्कृष्ट',
    man_grade_good: 'अच्छा',
    man_grade_fair: 'ठीक-ठाक',
    man_grade_needs_improvement: 'सुधार चाहिए',
    man_impact_high: 'उच्च',
    man_impact_medium: 'मध्यम',
    man_impact_low: 'निम्न',
    mnav_console: 'कंसोल',
    mnav_campaigns: 'कैंपेन',
    mnav_catalogue: 'कैटलॉग',
    mnav_dotd: 'आज का डील',
    mnav_intel: 'एनालिटिक्स',
    mnav_hub: 'प्रोफ़ाइल',
    app_name: 'डीलप्रो',
    login_header: 'स्मार्ट खोज',
    login_sub: 'अपने पास के विशेष डील्स और छूट का लाभ उठाएं।',
    login_placeholder_id: 'यूजरनेम / ईमेल',
    login_placeholder_pass: 'पासवर्ड',
    login_btn: 'साइन इन',
    login_forgot: 'पासवर्ड भूल गए?',
    login_register_hint: 'ग्रिड पर नए हैं?',
    login_register_action: 'पहचान बनाएं',
    home_deals: 'डील्स',
    home_near_you: ' आपके पास',
    home_daily_waves: 'दैनिक वेव्स',
    home_see_all: 'सभी डील्स देखें',
    home_adjust_range: 'दूरी बदलें',
    lang_select_title: 'भाषा चुनें',
    lang_select_sub: 'बेहतर अनुभव के लिए अपनी भाषा चुनें',
    reg_title: 'ग्रिड से जुड़ें',
    reg_consumer: 'ग्राहक',
    reg_merchant: 'व्यापारी',
    reg_choose_account: 'शुरू करने के लिए अपना खाता प्रकार चुनें',
    reg_consumer_desc: 'स्थानीय डील्स खोजने और पैसे बचाने के लिए नेटवर्क से जुड़ें',
    reg_merchant_desc: 'DealPro डिजिटल वेव्स के साथ अपने व्यवसाय को सशक्त बनाएं',
    reg_have_account: 'पहले से खाता है?',
    reg_back_login: 'लॉगिन पर वापस जाएं',
    reg_fullname: 'पूरा नाम',
    reg_username: 'यूजरनेम',
    reg_email: 'ईमेल पता',
    reg_password: 'पासवर्ड',
    reg_is_owner: 'क्या आप स्टोर के मालिक हैं?',
    reg_brand: 'मुख्य स्टोर का नाम - GST रजिस्टर्ड',
    reg_category: 'व्यवसाय श्रेणी',
    reg_locations: 'स्टोर का स्थान',
    reg_store_name_label: 'स्टोर का नाम (उदा. मेन स्ट्रीट ब्रांच)', // NEW
    reg_street: 'पता',
    reg_state: 'राज्य',
    reg_city: 'शहर',
    reg_hours: 'कार्य का समय',
    reg_24h: '24 घंटे',
    reg_opens: 'खुलता है',
    reg_closes: 'बंद होता है',
    reg_landmark: 'लैंडमार्क (वैकल्पिक)',
    reg_use_my_loc: 'मेरे स्थान का उपयोग करें',
    reg_sync_verified: 'सिंक सत्यापित',
    reg_add_outlet: 'एक और आउटलेट जोड़ें',
    reg_gstin: 'GSTIN',
    reg_pan: 'पैन कार्ड',
    reg_submit: 'मेरा खाता बनाएं',
    reg_verify: 'सत्यापित करें',
    loc_title: 'खोज के मानक',
    loc_sub: 'ग्रिड स्कैनिंग लॉजिक',
    loc_radius: 'खोज का दायरा',
    loc_gps: 'जीपीएस ट्रैकिंग',
    loc_manual: 'मैन्युअल ग्रिड',
    loc_region: 'राज्य चुनें',
    loc_city: 'शहर चुनें',
    loc_area: 'इलाका चुनें',
    loc_scan_btn: 'क्षेत्र स्कैन करें',
    loc_syncing: 'इलाकों को सिंक कर रहे हैं...',
    loc_resolving: 'लोकेशन का पता लगा रहे हैं',
    loc_locked: 'सिग्नल लॉक',
    loc_awaiting: 'लोकेशन की प्रतीक्षा',
    onboarding_1_headline: "हाइपर-लोकल खोज",
    onboarding_1_sub: "सटीक जीपीएस लॉजिक के साथ अपने तत्काल क्षेत्र में विशेष खुदरा अवसरों का पता लगाएं।",
    onboarding_1_tag: "प्रोक्सिमिटी इंटेलिजेंस",
    onboarding_2_headline: "रीयल-टाइम फ्लैश सेल",
    onboarding_2_sub: "सक्रिय मर्चेंट वेव्स के साथ सिंक करें और समाप्त होने से पहले उच्च मूल्य के लाभ प्राप्त करें।",
    onboarding_2_tag: "समय की बचत",
    onboarding_3_headline: "संस्थागत विश्वास",
    onboarding_3_sub: "सत्यापित नोड्स और सुरक्षित वाउचर प्रोटोकॉल एक प्रीमियम स्थानीय खरीदारी अनुभव सुनिश्चित करते हैं।",
    onboarding_3_tag: "ग्रिड सुरक्षा",
    home_daily: 'आज का सौदा',
    home_local_area: 'स्थानीय क्षेत्र',
    home_your_area: 'आपका क्षेत्र',
    home_your_city: 'आपका शहर',
    home_your_sector: 'आपका क्षेत्र',
    home_for_you: 'आपके लिए',
    home_nearby_deals: 'पास की डील्स',
    home_all_deals: 'सभी डील्स',
    home_your_insights: 'आपकी जानकारी',
    insight_love_category: 'आप {category} डील्स पसंद करते हैं - {count} प्राप्त किए!',
    insight_nearby_deals: 'अभी आपके पास {count} बढ़िया डील्स',
    insight_new_deals: 'इस सप्ताह {count} नए डील्स शुरू हुए',
    insight_redeemed: 'आपने {count} डील्स रिडीम किए - बढ़िया बचतकर्ता!',
    insight_no_deals: 'अभी कोई सक्रिय डील उपलब्ध नहीं',
    home_deal_singular: 'डील',
    home_deals_plural: 'डील्स',
    home_in: 'में',
    home_no_deals_sector: 'इस क्षेत्र में कोई सक्रिय डील नहीं है।',
    home_view_all: 'सभी देखें',
    home_syncing_grid: 'ग्रिड सिंक हो रहा है',
    details_redeem_btn: 'अभी रिडीम करें',
    details_verifying: 'सत्यापित हो रहा है...',
    details_activating_for: 'रिवॉर्ड इसके लिए सक्रिय:',
    details_protocol: 'अभियान प्रोटोकॉल',
    details_visit_intel: 'विजिट इंटेलिजेंस',
    details_start_gps: 'जीपीएस शुरू करें',
    details_coordinates: 'स्टोर का पता',
    details_landmark: 'निकटतम स्थान',
    details_op_window: 'कार्य का समय',
    details_verified_node: 'सत्यापित डीलप्रो नोड',
    details_instance_id: 'आईडी नंबर',
    details_id_verified: 'पहचान सत्यापित',
    details_present_counter: 'काउंटर पर दिखाएं',
    details_exit_btn: 'डैशबोर्ड से बाहर निकलें',
    history_title_1: 'रिडेम्पशन',
    history_title_2: 'इतिहास',
    history_sub: 'आपके रिडेम्पशन',
    history_active_nodes: 'परिणाम',
    history_rewards_label: 'रिवॉर्ड्स',
    history_tab_all: 'सभी रिवॉर्ड्स',
    history_tab_pending: 'भेंट की प्रतीक्षा',
    history_syncing: 'जानकारी सिंक हो रही है...',
    history_empty_title: 'वॉल्ट सिंक हो गया',
    history_empty_sub_pending: 'सभी डील्स सत्यापित हैं। कोई भी दुकान भेंट लंबित नहीं है।',
    history_empty_sub_all: 'आपके खाते में कोई रिवॉर्ड रिकॉर्ड नहीं मिला।',
    history_search_btn: 'ग्रिड खोजें',
    history_status_verified: 'भेंट सत्यापित',
    history_status_awaiting: 'भेंट की प्रतीक्षा',
    history_page_label: 'पेज',
    history_of: 'का',
    history_ledger_end: 'रिकॉर्ड समाप्त',
    history_voucher_security: 'वाउचर सुरक्षा',
    history_transaction_logged: 'लेनदेन दर्ज',
    history_present_counter: 'काउंटर पर दिखाएं',
    history_ref_label: 'REF',
    history_voucher_node: 'वाउचर नोड',
    history_rate_exp: 'अनुभव को रेट करें',
    status_live: 'लाइव',
    status_expired: 'समाप्त',
    favorites_title_1: 'आपके',
    favorites_title_2: 'पसंदीदा',
    favorites_sub: 'अपने सहेजे गए डील्स कभी भी देखें',
    favorites_syncing: 'डेटा सिंक हो रहा है',
    favorites_empty_title: 'कोई पसंदीदा नहीं',
    favorites_empty_sub: 'खोज मोड में दिल के आइकन पर टैप करके डील्स सहेजें।',
    profile_elite_member: 'एलीट सदस्य',
    profile_verif_hub: 'सत्यापन हब',
    profile_verif_sub: 'दुकान की यात्राएं सत्यापित करें',
    profile_edit: 'प्रोफ़ाइल बदलें',
    profile_edit_store: 'स्टोर प्रोफ़ाइल बदलें',
    profile_favs: 'मेरी पसंदीदा सूची',
    profile_invite_friend: 'दोस्त को आमंत्रित करें',
    profile_invite_partner: 'पार्टनर को आमंत्रित करें',
    profile_invite_placeholder: 'ईमेल या फोन नंबर',
    profile_invite_success: 'आमंत्रण भेज दिया गया है',
    profile_help: 'सहायता और प्रतिक्रिया',
    profile_support_hub: 'सपोर्ट हब',
    profile_console: 'स्टोर कंसोल',
    profile_payments: 'भुगतान',
    profile_subscriptions: 'मेरी सदस्यताएं',
    profile_bank_verification: 'बैंक सत्यापन', // NEW translation key
    profile_verified_merchant: 'सत्यापित व्यापारी',
    store_search_title: 'स्टोर', // NEW
    store_search_sub: 'खोज', // NEW
    store_search_hint: 'विशिष्ट खुदरा नोड्स का पता लगाएं', // NEW
    store_search_placeholder: 'स्टोर का नाम या पता खोजें', // NEW
    store_search_no_results: 'कोई स्टोर नहीं मिला।', // NEW
    store_search_adjust_query: 'अपनी खोज क्वेरी को समायोजित करने का प्रयास करें।', // NEW
  },
  ta: {
    man_loading: 'பகுப்பாய்வு ஏற்றப்படுகிறது...',
    man_error: 'பகுப்பாய்வை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    man_retry: 'மீண்டும் முயற்சி',
    man_ai_dashboard: 'AI நுண்ணறிவு டாஷ்போர்டு',
    man_ai_dashboard_sub: 'முழு AI பகுப்பாய்வு & கணிப்புகள்',
    man_title: 'பிரச்சார பகுப்பாய்வு',
    man_my_insights: 'என் நுண்ணறிவுகள்',
    man_lifetime: 'மொத்தம்',
    man_n_days: '{n} நாட்கள்',
    man_campaigns: 'பிரச்சாரங்கள்',
    man_active: 'செயலில்',
    man_redeemed: 'மீட்கப்பட்டது',
    man_campaign_status: 'பிரச்சார நிலை',
    man_approved: 'அங்கீகரிக்கப்பட்டது',
    man_in_review: 'பரிசீலனையில்',
    man_needs_review: 'பரிசீலனை தேவை',
    man_expired: 'காலாவதி',
    man_campaign_trend: 'பிரச்சார போக்கு',
    man_lifetime_analytics: 'மொத்த பகுப்பாய்வு',
    man_loading_lifetime: 'மொத்த தரவு ஏற்றப்படுகிறது...',
    man_total_clicks: 'மொத்த கிளிக்குகள்',
    man_conversion_rate: 'மாற்று விகிதம்',
    man_invites_sent: 'அனுப்பிய அழைப்புகள்',
    man_invites_accepted: 'ஏற்ற அழைப்புகள்',
    man_customer_loyalty: 'வாடிக்கையாளர் விசுவாசம்',
    man_no_redemption: 'இன்னும் மீட்பு தரவு இல்லை. உங்கள் டீல்களை மீட்கும் வாடிக்கையாளர்கள் இங்கே தோன்றுவர்.',
    man_total_customers: 'மொத்த வாடிக்கையாளர்கள்',
    man_repeat: 'மீண்டும் வருபவர்',
    man_repeat_rate: 'மீண்டும் வரும் விகிதம்',
    man_redemption_frequency: 'மீட்பு அதிர்வெண்',
    man_1_time: '1 முறை',
    man_2_times: '2 முறை',
    man_3_5_times: '3-5 முறை',
    man_6_plus_times: '6+ முறை',
    man_top_loyal: 'சிறந்த விசுவாச வாடிக்கையாளர்கள்',
    man_customer: 'வாடிக்கையாளர்',
    man_n_different_deals: '{n} வெவ்வேறு டீல்கள்',
    man_avg_redemptions: 'ஒரு வாடிக்கையாளருக்கு சராசரி {n} மீட்புகள்',
    man_unable_customer: 'வாடிக்கையாளர் தரவை ஏற்ற முடியவில்லை.',
    man_product_catalogue: 'தயாரிப்பு பட்டியல்',
    man_products: 'தயாரிப்புகள்',
    man_views: 'பார்வைகள்',
    man_likes: 'விருப்பங்கள்',
    man_top_performers: 'சிறந்த செயல்திறன்',
    man_no_product_data: 'இன்னும் தயாரிப்பு தரவு இல்லை',
    man_smart_insights: 'ஸ்மார்ட் நுண்ணறிவுகள்',
    man_top_category: 'சிறந்த வகை',
    man_top_category_tip: 'இந்த வகையில் மேலும் தயாரிப்புகளைச் சேர்ப்பதில் கவனம் செலுத்துங்கள்',
    man_avg_performance: 'சராசரி செயல்திறன்',
    man_views_per_product: 'பார்வைகள்/தயாரிப்பு',
    man_likes_per_product: 'விருப்பங்கள்/தயாரிப்பு',
    man_needs_attention: 'கவனம் தேவை',
    man_n_products: '{n} தயாரிப்புகள்',
    man_needs_attention_tip: 'ஈடுபாட்டை அதிகரிக்க படங்கள் அல்லது விளக்கங்களைப் புதுப்பிக்கவும்',
    man_performance_score: 'செயல்திறன் மதிப்பெண்',
    man_score_breakdown: 'மதிப்பெண் விவரம்',
    man_quick_wins: 'விரைவு வெற்றிகள்',
    man_view_ai_dashboard: 'AI நுண்ணறிவு டாஷ்போர்டைப் பார்',
    man_calculating_score: 'உங்கள் செயல்திறன் மதிப்பெண் கணக்கிடப்படுகிறது...',
    man_ai_recommendations: 'AI பரிந்துரைகள்',
    man_ai_analyzing: 'AI உங்கள் தரவை பகுப்பாய்வு செய்கிறது...',
    man_ai_analyzing_sub: 'தயாரிப்புகளைச் சேர்த்து டீல்களை உருவாக்கும்போது நுண்ணறிவுகள் தோன்றும்',
    man_grade_excellent: 'மிகச்சிறந்தது',
    man_grade_good: 'நல்லது',
    man_grade_fair: 'சராசரி',
    man_grade_needs_improvement: 'மேம்பாடு தேவை',
    man_impact_high: 'அதிகம்',
    man_impact_medium: 'நடுத்தரம்',
    man_impact_low: 'குறைவு',
    mnav_console: 'கன்சோல்',
    mnav_campaigns: 'பிரச்சாரங்கள்',
    mnav_catalogue: 'பட்டியல்',
    mnav_dotd: 'இன்றைய டீல்',
    mnav_intel: 'பகுப்பாய்வு',
    mnav_hub: 'சுயவிவரம்',
    app_name: 'டீல்ப்ரோ',
    login_header: 'ஸ்மார்ட் தேடல்',
    login_sub: 'உங்களுக்கு அருகிலுள்ள பிரத்யேக சலுகைகள் மற்றும் தள்ளுபடிகளைத் திறக்கவும்.',
    login_placeholder_id: 'பயனர் பெயர் / மின்னஞ்சல்',
    login_placeholder_pass: 'கடவுச்சொல்',
    login_btn: 'உள்நுழைக',
    login_forgot: 'சான்றுகளை மறந்துவிட்டீர்களா?',
    login_register_hint: 'புதியவரா?',
    login_register_action: 'கணக்கை உருவாக்கவும்',
    home_deals: 'சலுகைகள்',
    home_near_you: 'உங்களுக்கு அருகில்',
    home_daily_waves: 'தினசரி அலைகள்',
    home_see_all: 'அனைத்து சலுகைகளையும் இங்கே பார்க்கவும்',
    home_adjust_range: 'தூரத்தை மாற்றவும்',
    lang_select_title: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    lang_select_sub: 'சிறந்த அனுபவத்திற்கு உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    reg_title: 'கிரிட்டில் இணையுங்கள்',
    reg_consumer: 'நுகர்வோர்',
    reg_merchant: 'வணிகர்',
    reg_choose_account: 'தொடங்க உங்கள் கணக்கு வகையைத் தேர்ந்தெடுக்கவும்',
    reg_consumer_desc: 'உள்ளூர் சலுகைகளைக் கண்டறிந்து பணத்தை சேமிக்க நெட்வொர்க்கில் சேரவும்',
    reg_merchant_desc: 'DealPro டிஜிட்டல் அலைகளால் உங்கள் வணிகத்தை வலுப்படுத்துங்கள்',
    reg_have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
    reg_back_login: 'உள்நுழைவுக்குத் திரும்பு',
    reg_fullname: 'முழு பெயர்',
    reg_username: 'யூனர் பெயர்',
    reg_email: 'மின்னஞ்சல் முகவரி',
    reg_password: 'கடவுச்சொல்',
    reg_is_owner: 'நீங்கள் கடை உரிமையாளரா?',
    reg_brand: 'முக்கிய கடை பெயர் - GST பதிவுசெய்யப்பட்டது',
    reg_category: 'வணிக வகை',
    reg_locations: 'கடை இருப்பிடங்கள்',
    reg_store_name_label: 'கடை பெயர் (எ.கா. மெயின் ஸ்ட்ரீட் கிளை)', // NEW
    reg_street: 'தெரு முகவரி',
    reg_state: 'மாநிலம்',
    reg_city: 'நகரம்',
    reg_hours: 'இயங்கும் நேரம்',
    reg_24h: '24 மணிநேரம்',
    reg_opens: 'திறக்கும் நேரம்',
    reg_closes: 'மூடும் நேரம்',
    reg_landmark: 'அடையாளம் (விருப்பம்)',
    reg_use_my_loc: 'எனது இருப்பிடத்தைப் பயன்படுத்தவும்',
    reg_sync_verified: 'ஒத்திசைவு சரிபார்க்கப்பட்டது',
    reg_add_outlet: 'மற்றொரு கடையைச் சேர்க்கவும்',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN கார்டு',
    reg_submit: 'கணக்கை உருவாக்கு',
    reg_verify: 'சரிபார்',
    loc_title: 'தேடல் அளவுருக்கள்',
    loc_sub: 'கிரிட் ஸ்கேனிங் லாஜிக்',
    loc_radius: 'தேடல் ஆரம்',
    loc_gps: 'ஜிபிஎஸ் டிராக்கிங்',
    loc_manual: 'மேனுவல் கிரிட்',
    loc_region: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    loc_city: 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
    loc_area: 'இடத்தைத் தேர்ந்தெடுக்கவும்',
    loc_scan_btn: 'ஸ்கேன் பகுதி',
    loc_syncing: 'ஒத்திசைக்கப்படுகிறது...',
    loc_resolving: 'அமைவிடத்தைக் கண்டறிகிறது',
    loc_locked: 'சிக்னல் லாக் செய்யப்பட்டது',
    loc_awaiting: 'இருப்பிடத்திற்காக காத்திருக்கிறது',
    onboarding_1_headline: "உள்ளூர் தேடல்",
    onboarding_1_sub: "துல்லியமான ஜிபிஎஸ் லாஜிக் மூலம் உங்களுக்கு அருகிலுள்ள பிரத்யேக சலுகைகளைக் கண்டறியவும்.",
    onboarding_1_tag: "அருகாமை நுண்ணறிவு",
    onboarding_2_headline: "ஃபிளாஷ் விற்பனை",
    onboarding_2_sub: "வணிகர் சலுகைகளுடன் ஒத்திசைந்து காலாவதியாகும் முன் பலன்களைப் பெறுங்கள்.",
    onboarding_2_tag: "நேர திறன்",
    onboarding_3_headline: "நம்பகத்தன்மை",
    onboarding_3_sub: "சரிபார்க்கப்பட்ட முனையங்கள் மற்றும் பாதுகாப்பான வவுச்சர் நெறிமுறைகள் பிரீமியம் அனுபவத்தை உறுதி செய்கின்றன.",
    onboarding_3_tag: "கிரிட் பாதுகாப்பு",
    home_daily: 'இன்றைய சலுகை',
    home_local_area: 'உள்ளூர் பகுதி',
    home_your_area: 'உங்கள் பகுதி',
    home_your_city: 'உங்கள் நகரம்',
    home_your_sector: 'உங்கள் துறை',
    home_for_you: 'உங்களுக்காக',
    home_nearby_deals: 'அருகிலுள்ள சலுகைகள்',
    home_all_deals: 'அனைத்து சலுகைகள்',
    home_your_insights: 'உங்கள் நுண்ணறிவுகள்',
    insight_love_category: 'நீங்கள் {category} சலுகைகளை விரும்புகிறீர்கள் - {count} பெற்றீர்கள்!',
    insight_nearby_deals: 'இப்போது உங்கள் அருகில் {count} சிறந்த சலுகைகள்',
    insight_new_deals: 'இந்த வாரம் புதிதாக {count} சலுகைகள் தொடங்கப்பட்டன',
    insight_redeemed: 'நீங்கள் {count} சலுகைகளை பெற்றீர்கள் - சிறந்த சேமிப்பாளர்!',
    insight_no_deals: 'தற்போது செயலில் உள்ள சலுகைகள் எதுவும் இல்லை',
    home_deal_singular: 'சலுகை',
    home_deals_plural: 'சலுகைகள்',
    home_in: 'இல்',
    home_no_deals_sector: 'இந்தத் துறையில் செயலில் உள்ள சலுகைகள் இல்லை.',
    home_view_all: 'அனைத்தையும் பார்',
    home_syncing_grid: 'கிரிட் ஒத்திசைக்கப்படுகிறது',
    details_redeem_btn: 'இப்போதே பெறுங்கள்',
    details_verifying: 'சரிபார்க்கப்படுகிறது...',
    details_activating_for: 'வெகுமதி செயல்படுத்தப்படுகிறது:',
    details_protocol: 'பிரச்சார நெறிமுறை',
    details_visit_intel: 'வருகை நுண்ணறிவு',
    details_start_gps: 'ஜிபிஎஸ் தொடங்கவும்',
    details_coordinates: 'கடை அமைவிடம்',
    details_landmark: 'அருகிலுள்ள அடையாளம்',
    details_op_window: 'இயங்கும் நேரம்',
    details_verified_node: 'சரிபார்க்கப்பட்ட டீல்ப்ரோ முனையம்',
    details_instance_id: 'ஐடி எண்',
    details_id_verified: 'அடையாளம் சரிபார்க்கப்பட்டது',
    details_present_counter: 'கவுண்டரில் காண்பிக்கவும்',
    details_exit_btn: 'வெளியேறு',
    history_title_1: 'மீட்பு',
    history_title_2: 'வரலாறு',
    history_sub: 'உங்கள் மீட்புகள்',
    history_active_nodes: 'முடிவுகள்',
    history_rewards_label: 'வெகுமதிகள்',
    history_tab_all: 'அனைத்து வெகுமதிகளும்',
    history_tab_pending: 'வருகைக்காக காத்திருக்கிறது',
    history_syncing: 'தகவல் ஒத்திசைக்கப்படுகிறது...',
    history_empty_title: 'வால்ட் ஒத்திசைக்கப்பட்டது',
    history_empty_sub_pending: 'அனைத்து சலுகைகளும் சரிபார்க்கப்பட்டன. நிலுவையில் உள்ள வருகைகள் இல்லை.',
    history_empty_sub_all: 'உங்கள் கணக்கில் மீட்பு பதிவுகள் எதுவும் இல்லை.',
    history_search_btn: 'கிரிட்டைத் தேடுங்கள்',
    history_status_verified: 'வருகை சரிபார்க்கப்பட்டது',
    history_status_awaiting: 'வருகைக்காக காத்திருக்கிறது',
    history_page_label: 'பக்கம்',
    history_of: 'இல்',
    history_ledger_end: 'பதிவு முடிவு',
    history_voucher_security: 'வவுச்சர் பாதுகாப்பு',
    history_transaction_logged: 'பரிவர்த்தனை பதிவு செய்யப்பட்டது',
    history_present_counter: 'கவுண்டரில் காண்பிக்கவும்',
    history_ref_label: 'REF',
    history_voucher_node: 'வவுச்சர் முனையம்',
    history_rate_exp: 'அனுபவத்தை மதிப்பிடுங்கள்',
    status_live: 'நேரலை',
    status_expired: 'காலாவதியானது',
    favorites_title_1: 'உங்கள்',
    favorites_title_2: 'விருப்பங்கள்',
    favorites_sub: 'சேமித்த சலுகைகளை எப்போது வேண்டுமானாலும் அணுகவும்',
    favorites_syncing: 'தரவு ஒத்திசைக்கப்படுகிறது',
    favorites_empty_title: 'விருப்பங்கள் காலியாக உள்ளன',
    favorites_empty_sub: 'இதய ஐகானைத் தட்டுவதன் மூலம் சலுகைகளைச் சேமிக்கவும்.',
    profile_elite_member: 'எலைட் உறுப்பினர்',
    profile_verif_hub: 'சரிபார்ப்பு மையம்',
    profile_verif_sub: 'வருகைகளைச் சரிபார்க்கவும்',
    profile_edit: 'சுயவிவரத்தைத் திருத்து',
    profile_edit_store: 'கடை சுயவிவரத்தைத் திருத்து',
    profile_favs: 'எனது விருப்பங்கள்',
    profile_invite_friend: 'நண்பரை அழை',
    profile_invite_partner: 'கூட்டாளரை அழை',
    profile_invite_placeholder: 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    profile_invite_success: 'அழைப்பு நண்பருக்கு அனுப்பப்பட்டது',
    profile_help: 'உதவி மற்றும் கருத்து',
    profile_support_hub: 'ஆதரவு மையம்',
    profile_console: 'ஸ்டோர் கன்சோல்',
    profile_payments: 'பணம் செலுத்துதல்',
    profile_subscriptions: 'எனது சந்தாக்கள்',
    profile_bank_verification: 'வங்கி சரிபார்ப்பு', // NEW translation key
    profile_verified_merchant: 'சரிபார்க்கப்பட்ட வணிகர்',
    store_search_title: 'கடை', // NEW
    store_search_sub: 'தேடல்', // NEW
    store_search_hint: 'குறிப்பிட்ட சில்லறை முனையங்களைக் கண்டறியவும்', // NEW
    store_search_placeholder: 'கடை பெயர் அல்லது முகவரியைத் தேடுங்கள்', // NEW
    store_search_no_results: 'கடைகள் எதுவும் கண்டறியப்படவில்லை.', // NEW
    store_search_adjust_query: 'உங்கள் தேடல் வினவலை சரிசெய்ய முயற்சிக்கவும்.', // NEW
  },
  te: {
    man_loading: 'అనలిటిక్స్ లోడ్ అవుతోంది...',
    man_error: 'అనలిటిక్స్ లోడ్ కాలేదు. మళ్లీ ప్రయత్నించండి.',
    man_retry: 'మళ్లీ ప్రయత్నించు',
    man_ai_dashboard: 'AI ఇన్‌సైట్స్ డాష్‌బోర్డ్',
    man_ai_dashboard_sub: 'పూర్తి AI ఆధారిత విశ్లేషణ & అంచనాలు',
    man_title: 'క్యాంపెయిన్ అనలిటిక్స్',
    man_my_insights: 'నా ఇన్‌సైట్స్',
    man_lifetime: 'మొత్తం',
    man_n_days: '{n} రోజులు',
    man_campaigns: 'క్యాంపెయిన్‌లు',
    man_active: 'యాక్టివ్',
    man_redeemed: 'రిడీమ్ చేయబడింది',
    man_campaign_status: 'క్యాంపెయిన్ స్థితి',
    man_approved: 'ఆమోదించబడింది',
    man_in_review: 'సమీక్షలో ఉంది',
    man_needs_review: 'సమీక్ష అవసరం',
    man_expired: 'గడువు ముగిసింది',
    man_campaign_trend: 'క్యాంపెయిన్ ట్రెండ్',
    man_lifetime_analytics: 'మొత్తం అనలిటిక్స్',
    man_loading_lifetime: 'మొత్తం డేటా లోడ్ అవుతోంది...',
    man_total_clicks: 'మొత్తం క్లిక్‌లు',
    man_conversion_rate: 'కన్వర్షన్ రేటు',
    man_invites_sent: 'పంపిన ఆహ్వానాలు',
    man_invites_accepted: 'ఆమోదించిన ఆహ్వానాలు',
    man_customer_loyalty: 'కస్టమర్ లాయల్టీ',
    man_no_redemption: 'ఇంకా రిడెంప్షన్ డేటా లేదు. మీ డీల్స్ రిడీమ్ చేసే కస్టమర్లు ఇక్కడ కనిపిస్తారు.',
    man_total_customers: 'మొత్తం కస్టమర్లు',
    man_repeat: 'రిపీట్',
    man_repeat_rate: 'రిపీట్ రేటు',
    man_redemption_frequency: 'రిడెంప్షన్ ఫ్రీక్వెన్సీ',
    man_1_time: '1 సారి',
    man_2_times: '2 సార్లు',
    man_3_5_times: '3-5 సార్లు',
    man_6_plus_times: '6+ సార్లు',
    man_top_loyal: 'టాప్ లాయల్ కస్టమర్లు',
    man_customer: 'కస్టమర్',
    man_n_different_deals: '{n} వేర్వేరు డీల్స్',
    man_avg_redemptions: 'కస్టమర్‌కు సగటున {n} రిడెంప్షన్‌లు',
    man_unable_customer: 'కస్టమర్ డేటా లోడ్ కాలేదు.',
    man_product_catalogue: 'ప్రొడక్ట్ కేటలాగ్',
    man_products: 'ప్రొడక్ట్‌లు',
    man_views: 'వ్యూలు',
    man_likes: 'లైక్‌లు',
    man_top_performers: 'టాప్ పెర్ఫార్మర్లు',
    man_no_product_data: 'ఇంకా ప్రొడక్ట్ డేటా లేదు',
    man_smart_insights: 'స్మార్ట్ ఇన్‌సైట్స్',
    man_top_category: 'టాప్ కేటగిరీ',
    man_top_category_tip: 'ఈ కేటగిరీలో మరిన్ని ప్రొడక్ట్‌లు జోడించడంపై దృష్టి పెట్టండి',
    man_avg_performance: 'సగటు పెర్ఫార్మెన్స్',
    man_views_per_product: 'వ్యూలు/ప్రొడక్ట్',
    man_likes_per_product: 'లైక్‌లు/ప్రొడక్ట్',
    man_needs_attention: 'శ్రద్ధ అవసరం',
    man_n_products: '{n} ప్రొడక్ట్‌లు',
    man_needs_attention_tip: 'ఎంగేజ్‌మెంట్ పెంచడానికి ఇమేజ్‌లు లేదా వివరణలు అప్‌డేట్ చేయండి',
    man_performance_score: 'పెర్ఫార్మెన్స్ స్కోర్',
    man_score_breakdown: 'స్కోర్ విభజన',
    man_quick_wins: 'త్వరిత విజయాలు',
    man_view_ai_dashboard: 'AI ఇన్‌సైట్స్ డాష్‌బోర్డ్ చూడండి',
    man_calculating_score: 'మీ పెర్ఫార్మెన్స్ స్కోర్ లెక్కిస్తోంది...',
    man_ai_recommendations: 'AI సిఫార్సులు',
    man_ai_analyzing: 'AI మీ డేటాను విశ్లేషిస్తోంది...',
    man_ai_analyzing_sub: 'మీరు ప్రొడక్ట్‌లు జోడించి డీల్స్ సృష్టించగానే ఇన్‌సైట్స్ కనిపిస్తాయి',
    man_grade_excellent: 'అద్భుతం',
    man_grade_good: 'బాగుంది',
    man_grade_fair: 'ఫర్వాలేదు',
    man_grade_needs_improvement: 'మెరుగుదల అవసరం',
    man_impact_high: 'ఎక్కువ',
    man_impact_medium: 'మధ్యస్థం',
    man_impact_low: 'తక్కువ',
    mnav_console: 'కన్సోల్',
    mnav_campaigns: 'క్యాంపెయిన్‌లు',
    mnav_catalogue: 'క్యాటలాగ్',
    mnav_dotd: 'నేటి డీల్',
    mnav_intel: 'విశ్లేషణ',
    mnav_hub: 'ప్రొఫైల్',
    app_name: 'డీల్‌ప్రో',
    login_header: 'స్మార్ట్ సెర్చ్',
    login_sub: 'మీకు సమీపంలోని ప్రత్యేక డీల్స్ మరియు డిస్కౌంట్‌లను పొందండి.',
    login_placeholder_id: 'యూజర్ పేరు / ఈమెయిల్',
    login_placeholder_pass: 'పాస్‌వర్డ్',
    login_btn: 'సైన్ ఇన్',
    login_forgot: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    login_register_hint: 'కొత్తవారా?',
    login_register_action: 'ఖాతా సృష్టించండి',
    home_deals: 'డీల్స్',
    home_near_you: 'మీకు దగ్గరలో',
    home_daily_waves: 'రోజువారీ ఆఫర్లు',
    home_see_all: 'అన్ని డీల్స్ ఇక్కడ చూడండి',
    home_adjust_range: 'దూరం మార్చండి',
    lang_select_title: 'భాషను ఎంచుకోండి',
    lang_select_sub: 'మంచి అనుభవం కోసం మీ భాషను ఎంచుకోండి',
    reg_title: 'గ్రిడ్‌లో చేరండి',
    reg_consumer: 'వినియోగదారుడు',
    reg_merchant: 'వ్యాపారి',
    reg_choose_account: 'ప్రారంభించడానికి మీ ఖాతా రకాన్ని ఎంచుకోండి',
    reg_consumer_desc: 'స్థానిక డీల్స్ కనుగొని డబ్బు ఆదా చేయడానికి నెట్వర్క్‌లో చేరండి',
    reg_merchant_desc: 'DealPro డిజిటల్ తరంగాలతో మీ వ్యాపారాన్ని శక్తివంతం చేయండి',
    reg_have_account: 'ఇప్పటికే ఖాతా ఉందా?',
    reg_back_login: 'లాగిన్‌కు తిరిగి వెళ్లండి',
    reg_fullname: 'పూర్తి పేరు',
    reg_username: 'యూజర్ పేరు',
    reg_email: 'ఈమెయిల్ చిరునామా',
    reg_password: 'పాస్‌వర్డ్',
    reg_is_owner: 'మీరు స్టోర్ యజమానినా?',
    reg_brand: 'ప్రధాన స్టోర్ పేరు - GST నమోదు చేయబడింది',
    reg_category: 'వ్యాపార వర్గం',
    reg_locations: 'స్టోర్ స్థానాలు',
    reg_store_name_label: 'స్టోర్ పేరు (ఉదా. మెయిన్ స్ట్రీట్ బ్రాంచ్)', // NEW
    reg_street: 'వీధి చిరునామా',
    reg_state: 'రాష్ట్రం',
    reg_city: 'నగరం',
    reg_hours: 'పని వేళలు',
    reg_24h: '24 గంటలు',
    reg_opens: 'తెరుచు సమయం',
    reg_closes: 'మూయు సమయం',
    reg_landmark: 'ల్యాండ్‌మార్క్ (అవసరం లేదు)',
    reg_use_my_loc: 'నా ప్రస్తుత స్థానాన్ని వాడు',
    reg_sync_verified: 'సింక్ వెరిఫై చేయబడింది',
    reg_add_outlet: 'మరో అవుట్‌లెట్ జోడించు',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN కార్డ్',
    reg_submit: 'ఖాతాను సృష్టించు',
    reg_verify: 'వెరిఫై',
    loc_title: 'సెర్చ్ పారామితులు',
    loc_sub: 'గ్రిడ్ స్కానింగ్ లాజిక్',
    loc_radius: 'సెర్చ్ పరిధి',
    loc_gps: 'GPS ట్రాకింగ్',
    loc_manual: 'మాన్యువల్ గ్రిడ్',
    loc_region: 'రాష్ట్రాన్ని ఎంచుకోండి',
    loc_city: 'నగరాన్ని ఎంచుకోండి',
    loc_area: 'ప్రాంతాన్ని ఎంచుకోండి',
    loc_scan_btn: 'స్కాన్ ఏరియా',
    loc_syncing: 'సింక్ అవుతోంది...',
    loc_resolving: 'స్థానాన్ని గుర్తిస్తోంది',
    loc_locked: 'సిగ్నల్ లాక్ చేయబడింది',
    loc_awaiting: 'స్థానం కోసం నిరీక్షణ',
    onboarding_1_headline: "స్థానిక అన్వేషణ",
    onboarding_1_sub: "ఖచ్చితమైన GPS లాజిక్‌తో మీ సమీపంలోని ప్రత్యేక ఆఫర్లను కనుగొనండి.",
    onboarding_1_tag: "సామీప్య మేధస్సు",
    onboarding_2_headline: "ఫ్లాష్ సేల్స్",
    onboarding_2_sub: "వ్యాపారి ఆఫర్లతో సింక్ అయ్యి అవి ముగిసేలోపే ప్రయోజనాలను పొందండి.",
    onboarding_2_tag: "సమయ సామర్థ్యం",
    onboarding_3_headline: "సంస్థాగత నమ్మకం",
    onboarding_3_sub: "ధృవీకరించబడిన నోడ్స్ మరియు సురక్షిత వోచర్ ప్రోటోకాల్స్ ప్రీమియం అనుభవాన్ని అందిస్తాయి.",
    onboarding_3_tag: "గ్రిడ్ భద్రత",
    home_daily: 'నేటి డీల్',
    home_local_area: 'స్థానిక ప్రాంతం',
    home_your_area: 'మీ ప్రాంతం',
    home_your_city: 'మీ నగరం',
    home_your_sector: 'మీ సెక్టార్',
    home_for_you: 'మీ కోసం',
    home_nearby_deals: 'సమీప డీల్స్',
    home_all_deals: 'అన్ని డీల్స్',
    home_your_insights: 'మీ అంతర్దృష్టులు',
    insight_love_category: 'మీరు {category} డీల్స్‌ని ఇష్టపడతారు - {count} క్లెయిమ్ చేశారు!',
    insight_nearby_deals: 'ఇప్పుడు మీ సమీపంలో {count} గొప్ప డీల్స్',
    insight_new_deals: 'ఈ వారం {count} కొత్త డీల్స్ ప్రారంభించబడ్డాయి',
    insight_redeemed: 'మీరు {count} డీల్స్ రిడీమ్ చేశారు - గొప్ప సేవర్!',
    insight_no_deals: 'ప్రస్తుతం యాక్టివ్ డీల్స్ అందుబాటులో లేవు',
    home_deal_singular: 'డీల్',
    home_deals_plural: 'డీల్స్',
    home_in: 'లో',
    home_no_deals_sector: 'ఈ సెక్టార్‌లో యాక్టివ్ ఆఫర్లు లేవు.',
    home_view_all: 'అన్నీ చూడండి',
    home_syncing_grid: 'గ్రిడ్ సింక్ అవుతోంది',
    details_redeem_btn: 'ఇప్పుడే పొందండి',
    details_verifying: 'వెరిఫై అవుతోంది...',
    details_activating_for: 'రివార్డ్ యాక్టివేట్ అవుతోంది:',
    details_protocol: 'క్యాంపెయిన్ ప్రోటోకాల్',
    details_visit_intel: 'విజిట్ ఇంటెలిజెన్స్',
    details_start_gps: 'GPS ప్రారంభించు',
    details_coordinates: 'స్టోర్ అడ్రస్',
    details_landmark: 'సమీప ల్యాండ్‌మార్క్',
    details_op_window: 'పని వేళలు',
    details_verified_node: 'ధృవీకరించబడిన డీల్‌ప్రో నోడ్',
    details_instance_id: 'ఐడీ నంబర్',
    details_id_verified: 'గుర్తింపు ధృవీకరించబడింది',
    details_present_counter: 'కౌంటర్ వద్ద చూపండి',
    details_exit_btn: 'నిష్క్రమించు',
    history_title_1: 'రిడెంప్షన్',
    history_title_2: 'చరిత్ర',
    history_sub: 'మీ రిడెంప్షన్లు',
    history_active_nodes: 'ఫలితాలు',
    history_rewards_label: 'రివార్డులు',
    history_tab_all: 'అన్ని రివార్డులు',
    history_tab_pending: 'సందర్శన కోసం నిరీక్షణ',
    history_syncing: 'సమాచారం సింక్ అవుతోంది...',
    history_empty_title: 'వాల్ట్ సింక్ చేయబడింది',
    history_empty_sub_pending: 'అన్ని డీల్స్ వెరిఫై చేయబడ్డాయి. పెండింగ్ సందర్శనలు లేవు.',
    history_empty_sub_all: 'మీ ఖాతాలో రిడెంప్షన్ రికార్డులు లేవు.',
    history_search_btn: 'గ్రిడ్‌ను అన్వేషించండి',
    history_status_verified: 'సందర్శన ధృవీకరించబడింది',
    history_status_awaiting: 'సందర్శన కోసం నిరీక్షణ',
    history_page_label: 'పేజీ',
    history_of: 'లో',
    history_ledger_end: 'రికార్డు ముగింపు',
    history_voucher_security: 'వోచర్ భద్రత',
    history_transaction_logged: 'లావాదేవీ రికార్డు చేయబడింది',
    history_present_counter: 'కౌంటర్ వద్ద చూపండి',
    history_ref_label: 'REF',
    history_voucher_node: 'వోచర్ నోడ్',
    history_rate_exp: 'అనుభవాన్ని రేట్ చేయండి',
    status_live: 'లైవ్',
    status_expired: 'గడువు ముగిసింది',
    favorites_title_1: 'మీ',
    favorites_title_2: 'ఇష్టమైనవి',
    favorites_sub: 'సేవ్ చేసిన డీల్స్ ఎప్పుడైనా చూడండి',
    favorites_syncing: 'డేటా సింక్ అవుతోంది',
    favorites_empty_title: 'ఇష్టమైనవి ఏమీ లేవు',
    favorites_empty_sub: 'హార్ట్ ఐకాన్ నొక్కడం ద్వారా డీల్స్ సేవ్ చేయండి.',
    profile_elite_member: 'ఎలైట్ సభ్యుడు',
    profile_verif_hub: 'ధృవీకరణ హబ్',
    profile_verif_sub: 'స్టోర్ విజిట్స్ వెరిఫై చేయండి',
    profile_edit: 'ప్రొఫైల్ ఎడిట్ చేయండి',
    profile_edit_store: 'స్టోర్ ప్రొఫైల్ ఎడిట్ చేయండి',
    profile_favs: 'నా ఇష్టమైనవి',
    profile_invite_friend: 'స్నేహితుడిని ఆహ్వానించండి',
    profile_invite_partner: 'భాగస్వామిని ఆహ్వానించండి',
    profile_invite_placeholder: 'ఈమెయిల్ లేదా ఫోన్ నంబర్',
    profile_invite_success: 'ఆహ్వానం పంపబడింది',
    profile_help: 'సహాయం మరియు ఫీడ్‌బ్యాక్',
    profile_support_hub: 'సపోర్ట్ హబ్',
    profile_console: 'స్టోర్ కన్సోల్',
    profile_payments: 'చెల్లింపులు',
    profile_subscriptions: 'నా సబ్‌స్క్రిప్షన్లు',
    profile_bank_verification: 'బ్యాంక్ ధృవీకరణ', // NEW translation key
    profile_verified_merchant: 'ధృవీకరించబడిన వ్యాపారి',
    store_search_title: 'స్టోర్', // NEW
    store_search_sub: 'అన్వేషణ', // NEW
    store_search_hint: 'నిర్దిష్ట రిటైల్ నోడ్స్‌ను గుర్తించండి', // NEW
    store_search_placeholder: 'స్టోర్ పేరు లేదా చిరునామాను శోధించండి', // NEW
    store_search_no_results: 'స్టోర్‌లు ఏమీ కనుగొనబడలేదు.', // NEW
    store_search_adjust_query: 'మీ శోధన క్వెరీని సర్దుబాటు చేయడానికి ప్రయత్నించండి.', // NEW
  },
  ml: {
    man_loading: 'അനലിറ്റിക്സ് ലോഡ് ചെയ്യുന്നു...',
    man_error: 'അനലിറ്റിക്സ് ലോഡ് ചെയ്യാനായില്ല. വീണ്ടും ശ്രമിക്കുക.',
    man_retry: 'വീണ്ടും ശ്രമിക്കുക',
    man_ai_dashboard: 'AI ഇൻസൈറ്റ്സ് ഡാഷ്ബോർഡ്',
    man_ai_dashboard_sub: 'പൂർണ്ണ AI വിശകലനവും പ്രവചനങ്ങളും',
    man_title: 'ക്യാമ്പെയ്ൻ അനലിറ്റിക്സ്',
    man_my_insights: 'എന്റെ ഇൻസൈറ്റ്സ്',
    man_lifetime: 'ആജീവനാന്തം',
    man_n_days: '{n} ദിവസം',
    man_campaigns: 'ക്യാമ്പെയ്നുകൾ',
    man_active: 'സജീവം',
    man_redeemed: 'റിഡീം ചെയ്തു',
    man_campaign_status: 'ക്യാമ്പെയ്ൻ നില',
    man_approved: 'അംഗീകരിച്ചു',
    man_in_review: 'പരിശോധനയിൽ',
    man_needs_review: 'പരിശോധന വേണം',
    man_expired: 'കാലഹരണപ്പെട്ടു',
    man_campaign_trend: 'ക്യാമ്പെയ്ൻ ട്രെൻഡ്',
    man_lifetime_analytics: 'ആജീവനാന്ത അനലിറ്റിക്സ്',
    man_loading_lifetime: 'ആജീവനാന്ത ഡാറ്റ ലോഡ് ചെയ്യുന്നു...',
    man_total_clicks: 'ആകെ ക്ലിക്കുകൾ',
    man_conversion_rate: 'കൺവേർഷൻ നിരക്ക്',
    man_invites_sent: 'അയച്ച ക്ഷണങ്ങൾ',
    man_invites_accepted: 'സ്വീകരിച്ച ക്ഷണങ്ങൾ',
    man_customer_loyalty: 'ഉപഭോക്തൃ വിശ്വസ്തത',
    man_no_redemption: 'ഇതുവരെ റിഡംപ്ഷൻ ഡാറ്റയില്ല. നിങ്ങളുടെ ഡീലുകൾ റിഡീം ചെയ്യുന്ന ഉപഭോക്താക്കൾ ഇവിടെ കാണിക്കും.',
    man_total_customers: 'ആകെ ഉപഭോക്താക്കൾ',
    man_repeat: 'ആവർത്തിക്കുന്നവർ',
    man_repeat_rate: 'ആവർത്തന നിരക്ക്',
    man_redemption_frequency: 'റിഡംപ്ഷൻ ആവൃത്തി',
    man_1_time: '1 തവണ',
    man_2_times: '2 തവണ',
    man_3_5_times: '3-5 തവണ',
    man_6_plus_times: '6+ തവണ',
    man_top_loyal: 'ഏറ്റവും വിശ്വസ്ത ഉപഭോക്താക്കൾ',
    man_customer: 'ഉപഭോക്താവ്',
    man_n_different_deals: '{n} വ്യത്യസ്ത ഡീലുകൾ',
    man_avg_redemptions: 'ഒരു ഉപഭോക്താവിന് ശരാശരി {n} റിഡംപ്ഷൻ',
    man_unable_customer: 'ഉപഭോക്തൃ ഡാറ്റ ലോഡ് ചെയ്യാനായില്ല.',
    man_product_catalogue: 'ഉൽപ്പന്ന കാറ്റലോഗ്',
    man_products: 'ഉൽപ്പന്നങ്ങൾ',
    man_views: 'കാഴ്ചകൾ',
    man_likes: 'ലൈക്കുകൾ',
    man_top_performers: 'മികച്ച പ്രകടനം',
    man_no_product_data: 'ഇതുവരെ ഉൽപ്പന്ന ഡാറ്റയില്ല',
    man_smart_insights: 'സ്മാർട്ട് ഇൻസൈറ്റ്സ്',
    man_top_category: 'മുൻനിര വിഭാഗം',
    man_top_category_tip: 'ഈ വിഭാഗത്തിൽ കൂടുതൽ ഉൽപ്പന്നങ്ങൾ ചേർക്കുന്നതിൽ ശ്രദ്ധിക്കുക',
    man_avg_performance: 'ശരാശരി പ്രകടനം',
    man_views_per_product: 'കാഴ്ചകൾ/ഉൽപ്പന്നം',
    man_likes_per_product: 'ലൈക്കുകൾ/ഉൽപ്പന്നം',
    man_needs_attention: 'ശ്രദ്ധ വേണം',
    man_n_products: '{n} ഉൽപ്പന്നങ്ങൾ',
    man_needs_attention_tip: 'ഇടപഴകൽ കൂട്ടാൻ ചിത്രങ്ങളോ വിവരണങ്ങളോ അപ്ഡേറ്റ് ചെയ്യുക',
    man_performance_score: 'പ്രകടന സ്കോർ',
    man_score_breakdown: 'സ്കോർ വിശദാംശം',
    man_quick_wins: 'പെട്ടെന്നുള്ള നേട്ടങ്ങൾ',
    man_view_ai_dashboard: 'AI ഇൻസൈറ്റ്സ് ഡാഷ്ബോർഡ് കാണുക',
    man_calculating_score: 'നിങ്ങളുടെ പ്രകടന സ്കോർ കണക്കാക്കുന്നു...',
    man_ai_recommendations: 'AI ശുപാർശകൾ',
    man_ai_analyzing: 'AI നിങ്ങളുടെ ഡാറ്റ വിശകലനം ചെയ്യുന്നു...',
    man_ai_analyzing_sub: 'ഉൽപ്പന്നങ്ങൾ ചേർക്കുകയും ഡീലുകൾ ഉണ്ടാക്കുകയും ചെയ്യുമ്പോൾ ഇൻസൈറ്റ്സ് കാണിക്കും',
    man_grade_excellent: 'മികച്ചത്',
    man_grade_good: 'നല്ലത്',
    man_grade_fair: 'സാധാരണം',
    man_grade_needs_improvement: 'മെച്ചപ്പെടുത്തണം',
    man_impact_high: 'ഉയർന്നത്',
    man_impact_medium: 'ഇടത്തരം',
    man_impact_low: 'കുറവ്',
    mnav_console: 'കൺസോൾ',
    mnav_campaigns: 'കാമ്പെയ്‌നുകൾ',
    mnav_catalogue: 'കാറ്റലോഗ്',
    mnav_dotd: 'ഇന്നത്തെ ഡീൽ',
    mnav_intel: 'വിശകലനം',
    mnav_hub: 'പ്രൊഫൈൽ',
    app_name: 'ഡീൽപ്രോ',
    login_header: 'സ്മാർട്ട് സെർച്ച്',
    login_sub: 'നിങ്ങൾക്ക് അടുത്തുള്ള സവിശേഷമായ ഡീലുകളും ഡിസ്കൗണ്ടുകളും നേടൂ.',
    login_placeholder_id: 'യൂസർ നെയിം / ഇമെയിൽ',
    login_placeholder_pass: 'പാസ്‌വേഡ്',
    login_btn: 'സൈൻ ഇൻ',
    login_forgot: 'രഹസ്യവാക്ക് മറന്നോ?',
    login_register_hint: 'പുതിയ ആളാണോ?',
    login_register_action: 'അക്കൗണ്ട് തുടങ്ങാം',
    home_deals: 'ഡീലുകൾ',
    home_near_you: 'നിങ്ങൾക്ക് അടുത്ത്',
    home_daily_waves: 'പ്രതിദിന ഓഫറുകൾ',
    home_see_all: 'എല്ലാ ഡീലുകളും ഇവിടെ കാണാം',
    home_adjust_range: 'ദൂരം ക്രമീകരിക്കുക',
    lang_select_title: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    lang_select_sub: 'മികച്ച അനുഭവത്തിനായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    reg_title: 'ഗ്രിഡിൽ ചേരൂ',
    reg_consumer: 'ഉപഭോക്താവ്',
    reg_merchant: 'വ്യാപാരി',
    reg_choose_account: 'ആരംഭിക്കാൻ നിങ്ങളുടെ അക്കൗണ്ട് തരം തിരഞ്ഞെടുക്കുക',
    reg_consumer_desc: 'പ്രാദേശിക ഡീലുകൾ കണ്ടെത്താനും പണം ലാഭിക്കാനും നെറ്റ്‌വർക്കിൽ ചേരൂ',
    reg_merchant_desc: 'DealPro ഡിജിറ്റൽ തരംഗങ്ങളിലൂടെ നിങ്ങളുടെ ബിസിനസ് ശക്തിപ്പെടുത്തുക',
    reg_have_account: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    reg_back_login: 'ലോഗിനിലേക്ക് മടങ്ങുക',
    reg_fullname: 'മുഴുവൻ പേര്',
    reg_username: 'യൂസർ നെയിം',
    reg_email: 'ഇമെയിൽ വിലാസം',
    reg_password: 'പാസ്‌വേഡ്',
    reg_is_owner: 'നിങ്ങൾ കടയുടെ ഉടമയാണോ?',
    reg_brand: 'പ്രധാന കടയുടെ പേര് - GST രജിസ്റ്റർ ചെയ്തത്',
    reg_category: 'ബിസിനസ് വിഭാഗം',
    reg_locations: 'കടയുടെ ലൊക്കേഷനുകൾ',
    reg_store_name_label: 'കടയുടെ പേര് (ഉദാ. മെയിൻ സ്ട്രീറ്റ് ബ്രാഞ്ച്)', // NEW
    reg_street: 'മേൽവിലാസം',
    reg_state: 'സംസ്ഥാനം',
    reg_city: 'നഗരം',
    reg_hours: 'പ്രവൃത്തി സമയം',
    reg_24h: '24 മണിക്കൂർ',
    reg_opens: 'തുറക്കുന്ന സമയം',
    reg_closes: 'അടയ്ക്കുന്ന സമയം',
    reg_landmark: 'അടയാളം (നിർബന്ധമില്ല)',
    reg_use_my_loc: 'എന്റെ ലൊക്കേഷൻ ഉപയോഗിക്കൂ',
    reg_sync_verified: 'സിങ്ക് സ്ഥിരീകരിച്ചു',
    reg_add_outlet: 'മറ്റൊരു കട ചേർക്കുക',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN കാർഡ്',
    reg_submit: 'അക്കൗണ്ട് ക്രിയേറ്റ് ചെയ്യൂ',
    reg_verify: 'വെരിഫൈ ചെയ്യൂ',
    loc_title: 'സെർച്ച് പാരാമീറ്ററുകൾ',
    loc_sub: 'ഗ്രിഡ് സ്കാനിംഗ് ലോജിക്',
    loc_radius: 'സെർച്ച് പരിധി',
    loc_gps: 'GPS ട്രാക്കിംഗ്',
    loc_manual: 'മാനുവൽ ഗ്രിഡ്',
    loc_region: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    loc_city: 'നഗരം തിരഞ്ഞെടുക്കുക',
    loc_area: 'സ്ഥലം തിരഞ്ഞെടുക്കുക',
    loc_scan_btn: 'സ്കാൻ ഏരിയ',
    loc_syncing: 'സിങ്ക് ചെയ്യുന്നു...',
    loc_resolving: 'സ്ഥലം കണ്ടെത്തുന്നു',
    loc_locked: 'സിഗ്നൽ ലോക്ക് ചെയ്തു',
    loc_awaiting: 'ലൊക്കേഷനായി കാത്തിരിക്കുന്നു',
    onboarding_1_headline: "പ്രാദേശിക തിരച്ചിൽ",
    onboarding_1_sub: "കൃത്യമായ GPS ലോജിക് ഉപയോഗിച്ച് അടുത്തുള്ള മികച്ച ഓഫറുകൾ കണ്ടെത്തൂ.",
    onboarding_1_tag: "ലൊക്കേഷൻ ഇന്റലിജൻസ്",
    onboarding_2_headline: "ഫ്ലാഷ് സെയിൽസ്",
    onboarding_2_sub: "വ്യാപാരികളുടെ ഓഫറുകൾ അവസാനിക്കുന്നതിന് മുൻപ് തന്നെ നേടിയെടുക്കൂ.",
    onboarding_2_tag: "സമയ ലാഭം",
    onboarding_3_headline: "വിശ്വാസ്യത",
    onboarding_3_sub: "സ്ഥിരീകരിക്കപ്പെട്ട നോഡുകളും സുരക്ഷിത വൗച്ചർ പ്രോട്ടോക്കോളുകളും മികച്ച അനുഭവം നൽകുന്നു.",
    onboarding_3_tag: "ഗ്രിഡ് സെക്യൂരിറ്റി",
    home_daily: 'ഇന്നത്തെ ഡീൽ',
    home_local_area: 'പ്രാദേശിക മേഖല',
    home_your_area: 'നിങ്ങളുടെ പ്രദേശം',
    home_your_city: 'നിങ്ങളുടെ നഗരം',
    home_your_sector: 'നിങ്ങളുടെ സെക്ടർ',
    home_for_you: 'നിങ്ങൾക്കായി',
    home_nearby_deals: 'സമീപത്തെ ഡീലുകൾ',
    home_all_deals: 'എല്ലാ ഡീലുകളും',
    home_your_insights: 'നിങ്ങളുടെ ഉൾക്കാഴ്ചകൾ',
    insight_love_category: 'നിങ്ങൾ {category} ഡീലുകൾ ഇഷ്ടപ്പെടുന്നു - {count} ക്ലെയിം ചെയ്തു!',
    insight_nearby_deals: 'ഇപ്പോൾ നിങ്ങളുടെ സമീപം {count} മികച്ച ഡീലുകൾ',
    insight_new_deals: 'ഈ ആഴ്ച {count} പുതിയ ഡീലുകൾ ആരംഭിച്ചു',
    insight_redeemed: 'നിങ്ങൾ {count} ഡീലുകൾ റിഡീം ചെയ്തു - മികച്ച സേവർ!',
    insight_no_deals: 'ഇപ്പോൾ സജീവമായ ഡീലുകളൊന്നുമില്ല',
    home_deal_singular: 'ഡീൽ',
    home_deals_plural: 'ഡീലുകൾ',
    home_in: 'ൽ',
    home_no_deals_sector: 'ഈ സെക്ടറിൽ ഓഫറുകൾ ലഭ്യമല്ല.',
    home_view_all: 'എല്ലാം കാണുക',
    home_syncing_grid: 'ഗ്രിഡ് സിങ്ക് ചെയ്യുന്നു',
    details_redeem_btn: 'ഇപ്പോൾ നേടൂ',
    details_verifying: 'സ്ഥിരീകരിക്കുന്നു...',
    details_activating_for: 'ഓഫർ സജീവമാക്കുന്നു:',
    details_protocol: 'ക്യാമ്പയിൻ പ്രോട്ടോക്കോൾ',
    details_visit_intel: 'സന്ദർശന വിവരം',
    details_start_gps: 'GPS തുടങ്ങൂ',
    details_coordinates: 'കടയുടെ വിലാസം',
    details_landmark: 'അടുത്തുള്ള അടയാളം',
    details_op_window: 'പ്രവൃത്തി സമയം',
    details_verified_node: 'സ്ഥിരീകരിക്കപ്പെട്ട ഡീൽപ്രോ നോഡ്',
    details_instance_id: 'ഐഡി നമ്പർ',
    details_id_verified: 'തിരിച്ചറിയൽ രേഖ സ്ഥിരീകരിച്ചു',
    details_present_counter: 'കൗണ്ടറിൽ കാണിക്കുക',
    details_exit_btn: 'പുറത്തുകടക്കുക',
    history_title_1: 'റിഡംപ്ഷൻ',
    history_title_2: 'ചരിത്രം',
    history_sub: 'നിങ്ങളുടെ ഓഫറുകൾ',
    history_active_nodes: 'ഫലങ്ങൾ',
    history_rewards_label: 'റിവാർഡുകൾ',
    history_tab_all: 'എല്ലാ റിവാർഡുകളും',
    history_tab_pending: 'സന്ദർശനത്തിനായി കാക്കുന്നു',
    history_syncing: 'വിവരങ്ങൾ സിങ്ക് ചെയ്യുന്നു...',
    history_empty_title: 'വാൽട്ട് സിങ്ക് ചെയ്തു',
    history_empty_sub_pending: 'എല്ലാ ഡീലുകളും സ്ഥിരീകരിച്ചു. സന്ദർശനങ്ങൾ ബാക്കിയില്ല.',
    history_empty_sub_all: 'നിങ്ങളുടെ അക്കൗണ്ടിൽ റിഡംപ്ഷൻ വിവരങ്ങൾ ലഭ്യമല്ല.',
    history_search_btn: 'ഗ്രിഡ് തിരയുക',
    history_status_verified: 'സന്ദർശനം സ്ഥിരീകരിച്ചു',
    history_status_awaiting: 'സന്ദർശനത്തിനായി കാക്കുന്നു',
    history_page_label: 'പേജ്',
    history_of: 'ൽ',
    history_ledger_end: 'റെക്കോർഡ് അവസാനിച്ചു',
    history_voucher_security: 'വൗച്ചർ സുരക്ഷ',
    history_transaction_logged: 'ഇടപാട് രേഖപ്പെടുത്തി',
    history_present_counter: 'കൗണ്ടറിൽ കാണിക്കുക',
    history_ref_label: 'REF',
    history_voucher_node: 'വൗച്ചർ നോഡ്',
    history_rate_exp: 'അനുഭവം വിലയിരുത്തുക',
    status_live: 'ലൈവ്',
    status_expired: 'കാലഹരണപ്പെട്ടു',
    favorites_title_1: 'നിങ്ങളുടെ',
    favorites_title_2: 'ഇഷ്ടങ്ങൾ',
    favorites_sub: 'സേവ് ചെയ്ത ഡീലുകൾ എപ്പോൾ വേണമെങ്കിലും കാണാം',
    favorites_syncing: 'ഡാറ്റ സിങ്ക് ചെയ്യുന്നു',
    favorites_empty_title: 'ലിസ്റ്റ് കാലിയാണ്',
    favorites_empty_sub: 'ഹാർട്ട് ഐക്കൺ ക്ലിക്ക് ചെയ്ത് ഡീലുകൾ സേവ് ചെയ്യൂ.',
    profile_elite_member: 'എലൈറ്റ് മെമ്പർ',
    profile_verif_hub: 'വെരിഫിക്കേഷൻ ഹബ്',
    profile_verif_sub: 'സന്ദർശനങ്ങൾ സ്ഥിരീകരിക്കുക',
    profile_edit: 'പ്രൊഫൈൽ തിരുത്തുക',
    profile_edit_store: 'കടയുടെ പ്രൊഫൈൽ തിരുത്തുക',
    profile_favs: 'എനിക്ക് ഇഷ്ടപ്പെട്ടവ',
    profile_invite_friend: 'സുഹൃത്തിനെ ക്ഷണിക്കുക',
    profile_invite_partner: 'പങ്കാളിയെ ക്ഷണിക്കുക',
    profile_invite_placeholder: 'ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ നമ്പർ',
    profile_invite_success: 'ക്ഷണം സുഹൃത്തിന് അയച്ചു',
    profile_help: 'സഹായവും അഭിപ്രായങ്ങളും',
    profile_support_hub: 'സപ്പോർട്ട് ഹബ്',
    profile_console: 'സ്റ്റോർ കൺസോൾ',
    profile_payments: 'പേയ്‌മെന്റുകൾ',
    profile_subscriptions: 'സബ്‌സ്‌ക്രിപ്‌ഷനുകൾ',
    profile_bank_verification: 'ബാങ്ക് സ്ഥിരീകരണം', // NEW translation key
    profile_verified_merchant: 'സ്ഥിരീകരിക്കപ്പെട്ട വ്യാപാരി',
    store_search_title: 'സ്റ്റോർ', // NEW
    store_search_sub: 'അന്വേഷണം', // NEW
    store_search_hint: 'നിർദ്ദിഷ്ട റീട്ടെയിൽ നോഡുകൾ കണ്ടെത്തുക', // NEW
    store_search_placeholder: 'സ്റ്റോർ പേര് അല്ലെങ്കിൽ വിലാസം തിരയുക', // NEW
    store_search_no_results: 'സ്റ്റോറുകളൊന്നും കണ്ടെത്തിയില്ല.', // NEW
    store_search_adjust_query: 'നിങ്ങളുടെ തിരയൽ ക്വറി ക്രമീകരിക്കാൻ ശ്രമിക്കുക.', // NEW
  },
  bn: {
    man_loading: 'অ্যানালিটিক্স লোড হচ্ছে...',
    man_error: 'অ্যানালিটিক্স লোড করা যায়নি। আবার চেষ্টা করুন।',
    man_retry: 'আবার চেষ্টা',
    man_ai_dashboard: 'AI ইনসাইট ড্যাশবোর্ড',
    man_ai_dashboard_sub: 'সম্পূর্ণ AI-চালিত বিশ্লেষণ ও পূর্বাভাস',
    man_title: 'ক্যাম্পেইন অ্যানালিটিক্স',
    man_my_insights: 'আমার ইনসাইট',
    man_lifetime: 'সর্বকালীন',
    man_n_days: '{n} দিন',
    man_campaigns: 'ক্যাম্পেইন',
    man_active: 'সক্রিয়',
    man_redeemed: 'রিডিম হয়েছে',
    man_campaign_status: 'ক্যাম্পেইন স্ট্যাটাস',
    man_approved: 'অনুমোদিত',
    man_in_review: 'পর্যালোচনায়',
    man_needs_review: 'পর্যালোচনা প্রয়োজন',
    man_expired: 'মেয়াদ শেষ',
    man_campaign_trend: 'ক্যাম্পেইন প্রবণতা',
    man_lifetime_analytics: 'সর্বকালীন অ্যানালিটিক্স',
    man_loading_lifetime: 'সর্বকালীন ডেটা লোড হচ্ছে...',
    man_total_clicks: 'মোট ক্লিক',
    man_conversion_rate: 'কনভার্সন রেট',
    man_invites_sent: 'আমন্ত্রণ পাঠানো',
    man_invites_accepted: 'আমন্ত্রণ গৃহীত',
    man_customer_loyalty: 'গ্রাহক আনুগত্য',
    man_no_redemption: 'এখনও কোনো রিডেম্পশন ডেটা নেই। যারা আপনার ডিল রিডিম করবেন তারা এখানে দেখা যাবেন।',
    man_total_customers: 'মোট গ্রাহক',
    man_repeat: 'পুনরাবৃত্ত',
    man_repeat_rate: 'পুনরাবৃত্তি হার',
    man_redemption_frequency: 'রিডেম্পশন ফ্রিকোয়েন্সি',
    man_1_time: '১ বার',
    man_2_times: '২ বার',
    man_3_5_times: '৩-৫ বার',
    man_6_plus_times: '৬+ বার',
    man_top_loyal: 'শীর্ষ অনুগত গ্রাহক',
    man_customer: 'গ্রাহক',
    man_n_different_deals: '{n}টি ভিন্ন ডিল',
    man_avg_redemptions: 'গ্রাহকপ্রতি গড়ে {n} রিডেম্পশন',
    man_unable_customer: 'গ্রাহক ডেটা লোড করা যায়নি।',
    man_product_catalogue: 'পণ্য ক্যাটালগ',
    man_products: 'পণ্য',
    man_views: 'ভিউ',
    man_likes: 'লাইক',
    man_top_performers: 'শীর্ষ পারফর্মার',
    man_no_product_data: 'এখনও কোনো পণ্য ডেটা নেই',
    man_smart_insights: 'স্মার্ট ইনসাইট',
    man_top_category: 'শীর্ষ ক্যাটাগরি',
    man_top_category_tip: 'এই ক্যাটাগরিতে আরও পণ্য যোগ করায় মন দিন',
    man_avg_performance: 'গড় পারফরম্যান্স',
    man_views_per_product: 'ভিউ/পণ্য',
    man_likes_per_product: 'লাইক/পণ্য',
    man_needs_attention: 'মনোযোগ প্রয়োজন',
    man_n_products: '{n}টি পণ্য',
    man_needs_attention_tip: 'এনগেজমেন্ট বাড়াতে ছবি বা বিবরণ আপডেট করুন',
    man_performance_score: 'পারফরম্যান্স স্কোর',
    man_score_breakdown: 'স্কোর বিশ্লেষণ',
    man_quick_wins: 'দ্রুত সাফল্য',
    man_view_ai_dashboard: 'AI ইনসাইট ড্যাশবোর্ড দেখুন',
    man_calculating_score: 'আপনার পারফরম্যান্স স্কোর গণনা হচ্ছে...',
    man_ai_recommendations: 'AI সুপারিশ',
    man_ai_analyzing: 'AI আপনার ডেটা বিশ্লেষণ করছে...',
    man_ai_analyzing_sub: 'পণ্য যোগ ও ডিল তৈরি করলে ইনসাইট দেখা যাবে',
    man_grade_excellent: 'চমৎকার',
    man_grade_good: 'ভালো',
    man_grade_fair: 'মোটামুটি',
    man_grade_needs_improvement: 'উন্নতি প্রয়োজন',
    man_impact_high: 'উচ্চ',
    man_impact_medium: 'মাঝারি',
    man_impact_low: 'নিম্ন',
    mnav_console: 'কনসোল',
    mnav_campaigns: 'ক্যাম্পেইন',
    mnav_catalogue: 'ক্যাটালগ',
    mnav_dotd: 'আজকের ডিল',
    mnav_intel: 'বিশ্লেষণ',
    mnav_hub: 'প্রোফাইল',
    app_name: 'ডিলপ্রো',
    login_header: 'স্মার্ট ডিসকভারি',
    login_sub: 'আপনার কাছের বিশেষ ডিল এবং ডিসকাউন্টগুলি আনলক করুন।',
    login_placeholder_id: 'ইউজারনেম / ইমেল',
    login_placeholder_pass: 'পাসওয়ার্ড',
    login_btn: 'সাইন ইন',
    login_forgot: 'পাসওয়ার্ড ভুলে গেছেন?',
    login_register_hint: 'গ্রিডে নতুন?',
    login_register_action: 'পরিচয় তৈরি করুন',
    home_deals: 'ডিলস',
    home_near_you: 'আপনার কাছে',
    home_daily_waves: 'প্রতিদিনের অফার',
    home_see_all: 'সব ডিল এখানে দেখুন',
    home_adjust_range: 'দূরত্ব পরিবর্তন করুন',
    lang_select_title: 'ভাষা নির্বাচন করুন',
    lang_select_sub: 'ভালো অভিজ্ঞতার জন্য আপনার ভাষা বেছে নিন',
    reg_title: 'গ্রিডে যোগ দিন',
    reg_consumer: 'গ্রাহক',
    reg_merchant: 'বিক্রেতা',
    reg_choose_account: 'শুরু করতে আপনার অ্যাকাউন্টের ধরন নির্বাচন করুন',
    reg_consumer_desc: 'স্থানীয় ডিল খুঁজে পেতে এবং অর্থ সাশ্রয় করতে নেটওয়ার্কে যোগ দিন',
    reg_merchant_desc: 'DealPro ডিজিটাল তরঙ্গ দিয়ে আপনার ব্যবসাকে ক্ষমতায়িত করুন',
    reg_have_account: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    reg_back_login: 'লগইনে ফিরে যান',
    reg_fullname: 'পুরো নাম',
    reg_username: 'ইউজারনেম',
    reg_email: 'ইমেল ঠিকানা',
    reg_password: 'পাসওয়ার্ড',
    reg_is_owner: 'আপনি কি দোকানের মালিক?',
    reg_brand: 'প্রধান দোকানের নাম - GST রেজিস্টার্ড',
    reg_category: 'ব্যবসার বিভাগ',
    reg_locations: 'দোকানের অবস্থান',
    reg_store_name_label: 'দোকানের নাম (যেমন: মেন স্ট্রিট শাখা)', // NEW
    reg_street: 'ঠিকানা',
    reg_state: 'রাজ্য',
    reg_city: 'শহর',
    reg_hours: 'কাজের সময়',
    reg_24h: '২৪ ঘন্টা',
    reg_opens: 'খোলার সময়',
    reg_closes: 'বন্ধের সময়',
    reg_landmark: 'ল্যান্ডমার্ক (ঐচ্ছিক)',
    reg_use_my_loc: 'আমার অবস্থান ব্যবহার করুন',
    reg_sync_verified: 'সিঙ্ক যাচাই করা হয়েছে',
    reg_add_outlet: 'অন্য আউটলেট যোগ করুন',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN কার্ড',
    reg_submit: 'অ্যাকাউন্ট তৈরি করুন',
    reg_verify: 'যাচাই করুন',
    loc_title: 'সার্চ প্যারামিটার',
    loc_sub: 'গ্রিড স্ক্যানিং লজিক',
    loc_radius: 'সার্চ রেডিয়াস',
    loc_gps: 'জিপিএস ট্র্যাকিং',
    loc_manual: 'ম্যানুয়াল গ্রিড',
    loc_region: 'রাজ্য নির্বাচন করুন',
    loc_city: 'শহর নির্বাচন করুন',
    loc_area: 'এলাকা নির্বাচন করুন',
    loc_scan_btn: 'এলাকা স্ক্যান করুন',
    loc_syncing: 'সিঙ্ক হচ্ছে...',
    loc_resolving: 'অবস্থান খুঁজছে',
    loc_locked: 'সিগন্যাল লক করা হয়েছে',
    loc_awaiting: 'অবস্থানের অপেক্ষা',
    onboarding_1_headline: "স্থানীয় ডিসকভারি",
    onboarding_1_sub: "সঠিক জিপিএস লজিকের মাধ্যমে আপনার কাছের বিশেষ ডিলগুলি খুঁজুন।",
    onboarding_1_tag: "প্রক্সিমিটি ইন্টেলিজেন্স",
    onboarding_2_headline: "ফ্ল্যাশ সেলস",
    onboarding_2_sub: "বিক্রেতাদের অফারের সাথে সিঙ্ক করুন এবং শেষ হওয়ার আগেই সুবিধা নিন।",
    onboarding_2_tag: "সময়ের সঠিক ব্যবহার",
    onboarding_3_headline: "নির্ভরযোগ্যতা",
    onboarding_3_sub: "যাচাইকৃত নোড এবং নিরাপদ ভাউচার প্রোটোকল আপনাকে সেরা অভিজ্ঞতা দেবে।",
    onboarding_3_tag: "গ্রিড সিকিউরিটি",
    home_daily: 'আজকের ডিল',
    home_local_area: 'স্থানীয় এলাকা',
    home_your_area: 'আপনার এলাকা',
    home_your_city: 'আপনার শহর',
    home_your_sector: 'আপনার সেক্টর',
    home_for_you: 'আপনার জন্য',
    home_nearby_deals: 'কাছাকাছি ডিল',
    home_all_deals: 'সব ডিল',
    home_your_insights: 'আপনার অন্তর্দৃষ্টি',
    insight_love_category: 'আপনি {category} ডিল পছন্দ করেন - {count} দাবি করেছেন!',
    insight_nearby_deals: 'এখন আপনার কাছে {count} দুর্দান্ত ডিল',
    insight_new_deals: 'এই সপ্তাহে {count} নতুন ডিল চালু হয়েছে',
    insight_redeemed: 'আপনি {count} ডিল রিডিম করেছেন - দুর্দান্ত সেভার!',
    insight_no_deals: 'এখন কোনও সক্রিয় ডিল উপলব্ধ নেই',
    home_deal_singular: 'ডিল',
    home_deals_plural: 'ডিলস',
    home_in: 'এ',
    home_no_deals_sector: 'এই সেক্টরে কোনো সক্রিয় অফার নেই।',
    home_view_all: 'সব দেখুন',
    home_syncing_grid: 'গ্রিড সিঙ্ক হচ্ছে',
    details_redeem_btn: 'এখনই নিন',
    details_verifying: 'যাচাই করা হচ্ছে...',
    details_activating_for: 'রিওয়ার্ড সক্রিয় হচ্ছে:',
    details_protocol: 'ক্যাম্পেইন প্রোটোকল',
    details_visit_intel: 'ভিজিট ইন্টেলিজেন্স',
    details_start_gps: 'জিপিএস শুরু করুন',
    details_coordinates: 'দোকানের ঠিকানা',
    details_landmark: 'কাছের ল্যান্ডমার্ক',
    details_op_window: 'কাজের সময়',
    details_verified_node: 'যাচাইকৃত ডিলপ্রো নোড',
    details_instance_id: 'আইডি নম্বর',
    details_id_verified: 'পরিচয় যাচাই করা হয়েছে',
    details_present_counter: 'কাউন্টারে দেখান',
    details_exit_btn: 'প্রস্থান করুন',
    history_title_1: 'রিডেম্পশন',
    history_title_2: 'ইতিহাস',
    history_sub: 'আপনার রিডেম্পশনগুলি',
    history_active_nodes: 'ফলাফল',
    history_rewards_label: 'রিওয়ার্ডস',
    history_tab_all: 'সব রিওয়ার্ড',
    history_tab_pending: 'পরিদর্শনের অপেক্ষা',
    history_syncing: 'তথ্য সিঙ্ক হচ্ছে...',
    history_empty_title: 'ভল্ট সিঙ্ক করা হয়েছে',
    history_empty_sub_pending: 'সব ডিল যাচাই করা হয়েছে। কোনো ভিজিট বাকি নেই।',
    history_empty_sub_all: 'আপনার অ্যাকাউন্টে কোনো রিডেম্পशन रिकॉर्ड নেই।',
    history_search_btn: 'গ্রিড এক্সপ্লোर করুন',
    history_status_verified: 'ভিজিট যাচাইকৃত',
    history_status_awaiting: 'পরিদর্শনের অপেক্ষা',
    history_page_label: 'পেজ',
    history_of: 'এর',
    history_ledger_end: 'রেকর্ড শেষ',
    history_voucher_security: 'ভাউচার সিকিউরিটি',
    history_transaction_logged: 'লেনদেন নথিভুক্ত',
    history_present_counter: 'কাউন্টারে দেখান',
    history_ref_label: 'REF',
    history_voucher_node: 'ভাউচার নোড',
    history_rate_exp: 'অভিজ্ঞতা রেট করুন',
    status_live: 'লাইভ',
    status_expired: 'মেয়াদ শেষ',
    favorites_title_1: 'আপনার',
    favorites_title_2: 'প্রিয়',
    favorites_sub: 'সেভ করা ডিলগুলি যেকোনো সময় দেখুন',
    favorites_syncing: 'ডেটা সিঙ্ক হচ্ছে',
    favorites_empty_title: 'লিস্ট খালি',
    favorites_empty_sub: 'হার্ট আইকনে ক্লিক করে ডিলগুলি সেভ করুন।',
    profile_elite_member: 'এলিট মেম্বার',
    profile_verif_hub: 'ভেরিফিকেশন হাব',
    profile_verif_sub: 'ভিজিট যাচাই করুন',
    profile_edit: 'প্রোফাইল পরিবর্তন',
    profile_edit_store: 'দোকানের প্রোফাইল পরিবর্তন',
    profile_favs: 'আমার প্রিয় ডিলস',
    profile_invite_friend: 'বন্ধুকে আমন্ত্রণ জানান',
    profile_invite_partner: 'পার্টনারকে আমন্ত্রণ জানান',
    profile_invite_placeholder: 'ইমেল বা ফোন নম্বর',
    profile_invite_success: 'আমন্ত্রণ পাঠানো হয়েছে',
    profile_help: 'সাহায্য ও মতামত',
    profile_support_hub: 'সাপোর্ট হাব',
    profile_console: 'স্টোর কনসোল',
    profile_payments: 'পেমেন্ট',
    profile_subscriptions: 'আমার সাবস্ক্রিপশন',
    profile_bank_verification: 'ব্যাংক যাচাইকরণ', // NEW translation key
    profile_verified_merchant: 'যাচাইকৃত বিক্রেতা',
    store_search_title: 'দোকান', // NEW
    store_search_sub: 'সন্ধান', // NEW
    store_search_hint: 'নির্দিষ্ট খুচরা নোড খুঁজুন', // NEW
    store_search_placeholder: 'দোকানের নাম বা ঠিকানা খুঁজুন', // NEW
    store_search_no_results: 'কোনো দোকান পাওয়া যায়নি।', // NEW
    store_search_adjust_query: 'আপনার অনুসন্ধান ক্যোয়ারী সামঞ্জস্য করার চেষ্টা করুন।', // NEW
  },
  mr: {
    man_loading: 'अ‍ॅनालिटिक्स लोड होत आहे...',
    man_error: 'अ‍ॅनालिटिक्स लोड करता आले नाही. पुन्हा प्रयत्न करा.',
    man_retry: 'पुन्हा प्रयत्न',
    man_ai_dashboard: 'AI इनसाइट्स डॅशबोर्ड',
    man_ai_dashboard_sub: 'संपूर्ण AI विश्लेषण आणि अंदाज',
    man_title: 'मोहीम विश्लेषण',
    man_my_insights: 'माझे इनसाइट्स',
    man_lifetime: 'एकूण कालावधी',
    man_n_days: '{n} दिवस',
    man_campaigns: 'मोहिमा',
    man_active: 'सक्रिय',
    man_redeemed: 'वापरले',
    man_campaign_status: 'मोहीम स्थिती',
    man_approved: 'मंजूर',
    man_in_review: 'पडताळणीत',
    man_needs_review: 'पडताळणी आवश्यक',
    man_expired: 'मुदत संपली',
    man_campaign_trend: 'मोहीम कल',
    man_lifetime_analytics: 'एकूण विश्लेषण',
    man_loading_lifetime: 'एकूण डेटा लोड होत आहे...',
    man_total_clicks: 'एकूण क्लिक्स',
    man_conversion_rate: 'रूपांतर दर',
    man_invites_sent: 'पाठवलेली आमंत्रणे',
    man_invites_accepted: 'स्वीकारलेली आमंत्रणे',
    man_customer_loyalty: 'ग्राहक निष्ठा',
    man_no_redemption: 'अद्याप वापराचा डेटा नाही. तुमचे डील वापरणारे ग्राहक येथे दिसतील.',
    man_total_customers: 'एकूण ग्राहक',
    man_repeat: 'पुनरागत',
    man_repeat_rate: 'पुनरागत दर',
    man_redemption_frequency: 'वापर वारंवारता',
    man_1_time: '१ वेळा',
    man_2_times: '२ वेळा',
    man_3_5_times: '३-५ वेळा',
    man_6_plus_times: '६+ वेळा',
    man_top_loyal: 'सर्वाधिक निष्ठावान ग्राहक',
    man_customer: 'ग्राहक',
    man_n_different_deals: '{n} वेगवेगळे डील',
    man_avg_redemptions: 'प्रति ग्राहक सरासरी {n} वापर',
    man_unable_customer: 'ग्राहक डेटा लोड करता आला नाही.',
    man_product_catalogue: 'उत्पादन सूची',
    man_products: 'उत्पादने',
    man_views: 'पाहणी',
    man_likes: 'लाइक्स',
    man_top_performers: 'अव्वल उत्पादने',
    man_no_product_data: 'अद्याप उत्पादन डेटा नाही',
    man_smart_insights: 'स्मार्ट इनसाइट्स',
    man_top_category: 'अव्वल श्रेणी',
    man_top_category_tip: 'या श्रेणीत अधिक उत्पादने जोडण्यावर लक्ष द्या',
    man_avg_performance: 'सरासरी कामगिरी',
    man_views_per_product: 'पाहणी/उत्पादन',
    man_likes_per_product: 'लाइक्स/उत्पादन',
    man_needs_attention: 'लक्ष आवश्यक',
    man_n_products: '{n} उत्पादने',
    man_needs_attention_tip: 'सहभाग वाढवण्यासाठी चित्रे किंवा वर्णने अपडेट करा',
    man_performance_score: 'कामगिरी गुण',
    man_score_breakdown: 'गुण तपशील',
    man_quick_wins: 'झटपट सुधारणा',
    man_view_ai_dashboard: 'AI इनसाइट्स डॅशबोर्ड पहा',
    man_calculating_score: 'तुमचे कामगिरी गुण मोजत आहे...',
    man_ai_recommendations: 'AI शिफारसी',
    man_ai_analyzing: 'AI तुमचा डेटा विश्लेषण करत आहे...',
    man_ai_analyzing_sub: 'उत्पादने जोडल्यावर आणि डील तयार केल्यावर इनसाइट्स दिसतील',
    man_grade_excellent: 'उत्कृष्ट',
    man_grade_good: 'चांगले',
    man_grade_fair: 'बरे',
    man_grade_needs_improvement: 'सुधारणा आवश्यक',
    man_impact_high: 'उच्च',
    man_impact_medium: 'मध्यम',
    man_impact_low: 'कमी',
    mnav_console: 'कन्सोल',
    mnav_campaigns: 'मोहिमा',
    mnav_catalogue: 'कॅटलॉग',
    mnav_dotd: 'आजची डील',
    mnav_intel: 'विश्लेषण',
    mnav_hub: 'प्रोफाइल',
    app_name: 'डीलप्रो',
    login_header: 'स्मार्ट डिस्कव्हरी',
    login_sub: 'तुमच्या जवळचे विशेष डील्स आणि सवलती मिळवा.',
    login_placeholder_id: 'युजरनेम / ईमेल',
    login_placeholder_pass: 'पासवर्ड',
    login_btn: 'साइन इन',
    login_forgot: 'पासवर्ड विसरलात?',
    login_register_hint: 'ग्रिडवर नवीन आहात?',
    login_register_action: 'ओळख तयार करा',
    home_deals: 'डील्स',
    home_near_you: 'तुमच्या जवळ',
    home_daily_waves: 'दैनंदिन ऑफर्स',
    home_see_all: 'सर्व डील्स येथे पहा',
    home_adjust_range: 'क्षेत्र बदला',
    lang_select_title: 'भाषा निवडा',
    lang_select_sub: 'उत्तम अनुभवासाठी तुमची भाषा निवडा',
    reg_title: 'ग्रिडमध्ये सामील व्हा',
    reg_consumer: 'ग्राहक',
    reg_merchant: 'व्यापारी',
    reg_choose_account: 'सुरू करण्यासाठी तुमचा खाते प्रकार निवडा',
    reg_consumer_desc: 'स्थानिक डील्स शोधण्यासाठी आणि पैसे वाचवण्यासाठी नेटवर्कमध्ये सामील व्हा',
    reg_merchant_desc: 'DealPro डिजिटल लहरींसह तुमचा व्यवसाय सशक्त करा',
    reg_have_account: 'आधीपासूनच खाते आहे?',
    reg_back_login: 'लॉगिनवर परत या',
    reg_fullname: 'पूर्ण नाव',
    reg_username: 'युजरनेम',
    reg_email: 'ईमेल पत्ता',
    reg_password: 'पासवर्ड',
    reg_is_owner: 'तुम्ही दुकानाचे मालक आहात का?',
    reg_brand: 'मुख्य दुकानाचे नाव - GST नोंदणीकृत',
    reg_category: 'व्यवसाय श्रेणी',
    reg_locations: 'दुकानाचे ठिकाण',
    reg_store_name_label: 'दुकानाचे नाव (उदा. मेन स्ट्रीट ब्रांच)', // NEW
    reg_street: 'पत्ता',
    reg_state: 'राज्य',
    reg_city: 'शहर',
    reg_hours: 'कामकाजाची वेळ',
    reg_24h: '२४ तास',
    reg_opens: 'उघडण्याची वेळ',
    reg_closes: 'बंद होण्याची वेळ',
    reg_landmark: 'लँडमार्क (पर्यायी)',
    reg_use_my_loc: 'माझे लोकेशन वापरा',
    reg_sync_verified: 'सिंक यशस्वी',
    reg_add_outlet: 'दुसरे आउटलेट जोडा',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN कार्ड',
    reg_submit: 'खाते तयार करा',
    reg_verify: 'पडताळणी करा',
    loc_title: 'शोध निकष',
    loc_sub: 'ग्रिड स्कॅनिंग लॉजिक',
    loc_radius: 'शोध त्रिज्या',
    loc_gps: 'जीपीएस ट्रॅकिंग',
    loc_manual: 'मॅन्युअल ग्रिড',
    loc_region: 'राज्य निवडा',
    loc_city: 'शहर निवडा',
    loc_area: 'परिसर निवडा',
    loc_scan_btn: 'परिसर स्कॅन करा',
    loc_syncing: 'सिंक होत आहे...',
    loc_resolving: 'लोकेशन शोधत आहे',
    loc_locked: 'सिग्नल लॉक झाले',
    loc_awaiting: 'लोकेशनची प्रतीक्षा',
    onboarding_1_headline: "स्थानिक शोध",
    onboarding_1_sub: "अचूक जीपीएस लॉजिकसह तुमच्या जवळच्या विशेष ऑफर्स शोधा.",
    onboarding_1_tag: "प्रॉक्सिमिटी इंटेलिजन्स",
    onboarding_2_headline: "फ्लॅश सेल्स",
    onboarding_2_sub: "व्यापाऱ्यांच्या ऑफर्स संपण्यापूर्वीच त्यांचा लाभ घ्या.",
    onboarding_2_tag: "वेळेची बचत",
    onboarding_3_headline: "विश्वासार्हता",
    onboarding_3_sub: "व्हेरिफाईड नोड्स आणि सुरक्षित व्हाउचर प्रोटोकॉल तुम्हाला सर्वोत्तम अनुभव देतील.",
    onboarding_3_tag: "ग्रिड सुरक्षा",
    home_daily: 'आजचा सौदा',
    home_local_area: 'स्थानिक परिसर',
    home_your_area: 'तुमचा परिसर',
    home_your_city: 'तुमचे शहर',
    home_your_sector: 'तुमचा सेक्टर',
    home_for_you: 'तुमच्यासाठी',
    home_nearby_deals: 'जवळपासच्या डील्स',
    home_all_deals: 'सर्व डील्स',
    home_your_insights: 'तुमची अंतर्दृष्टी',
    insight_love_category: 'तुम्हाला {category} डील्स आवडतात - {count} क्लेम केले!',
    insight_nearby_deals: 'आत्ता तुमच्या जवळ {count} उत्तम डील्स',
    insight_new_deals: 'या आठवड्यात {count} नवीन डील्स सुरू झाले',
    insight_redeemed: 'तुम्ही {count} डील्स रिडीम केले - उत्तम सेव्हर!',
    insight_no_deals: 'सध्या कोणतीही सक्रिय डील उपलब्ध नाहीत',
    home_deal_singular: 'डील',
    home_deals_plural: 'डील्स',
    home_in: 'मध्ये',
    home_no_deals_sector: 'या सेक्टरमध्ये सध्या ऑफर्स नाहीत.',
    home_view_all: 'सर्व पहा',
    home_syncing_grid: 'ग्रिड सिंक होत आहे',
    details_redeem_btn: 'आत्ता मिळवा',
    details_verifying: 'पडताळणी होत आहे...',
    details_activating_for: 'रिवॉर्ड सक्रिय होत आहे:',
    details_protocol: 'कॅम्पेन प्रोटोकॉल',
    details_visit_intel: 'व्हिजिट इंटेलिजन्स',
    details_start_gps: 'जीपीएस सुरू करा',
    details_coordinates: 'दुकानाचे लोकेशन',
    details_landmark: 'जवळपासची खुण',
    details_op_window: 'कामकाजाची वेळ',
    details_verified_node: 'व्हेरिफाईड डीलप्रो नोड',
    details_instance_id: 'आयडी नंबर',
    details_id_verified: 'ओळख पटली आहे',
    details_present_counter: 'काउंटरवर दाखवा',
    details_exit_btn: 'बाहेर पडा',
    history_title_1: 'रिडेम्पशन',
    history_title_2: 'इतिहास',
    history_sub: 'तुमची रिदेम्पशन',
    history_active_nodes: 'निकाल',
    history_rewards_label: 'रिवॉर्ड्स',
    history_tab_all: 'सर्व रिवॉर्ड्स',
    history_tab_pending: 'भेटीची प्रतीक्षा',
    history_syncing: 'माहिती सिंक होत आहे...',
    history_empty_title: 'व्हॉल्ट सिंक झाले',
    history_empty_sub_pending: 'सर्व डील्स सत्यापित आहेत. कोणतीही भेट प्रलंबित नाही.',
    history_empty_sub_all: 'तुमच्या खात्यात रिदेम्पशन रेकॉर्ड नाहीत.',
    history_search_btn: 'ग्रिड एक्सप्लोर करा',
    history_status_verified: 'व्हिजिट व्हेरिफाईड',
    history_status_awaiting: 'भेटीची प्रतीक्षा',
    history_page_label: 'पेज',
    history_of: 'चे',
    history_ledger_end: 'रेकॉर्ड समाप्त',
    history_voucher_security: 'व्हाउचर सुरक्षा',
    history_transaction_logged: 'व्यवहार नोंदवला',
    history_present_counter: 'काउंटरवर दाखवा',
    history_ref_label: 'REF',
    history_voucher_node: 'व्हाउचर नोड',
    history_rate_exp: 'अनुभव रेट करा',
    status_live: 'लाईव्ह',
    status_expired: 'मुदत संपली',
    favorites_title_1: 'तुमचे',
    favorites_title_2: 'आवडते',
    favorites_sub: 'सेव्ह केलेले डील्स कधीही पहा',
    favorites_syncing: 'डेटा सिंक होत आहे',
    favorites_empty_title: 'लिस्ट रिकामी आहे',
    favorites_empty_sub: 'हार्ट आयकॉनवर क्लिक करून डील्स सेव्ह करा.',
    profile_elite_member: 'एलिट मेंबर',
    profile_verif_hub: 'व्हेरिफिकेशन हब',
    profile_verif_sub: 'व्हिजिट्स व्हेरिफाय करा',
    profile_edit: 'प्रोफाईल संपादित करा',
    profile_edit_store: 'दुकानाची माहिती संपादित करा',
    profile_favs: 'माझे आवडते डील्स',
    profile_invite_friend: 'मित्राला आमंत्रित करा',
    profile_invite_partner: 'भागीदाराला आमंत्रित करा',
    profile_invite_placeholder: 'ईमेल किंवा फोन नंबर',
    profile_invite_success: 'आमंत्रण पाठवण्यात आले',
    profile_help: 'मदत आणि अभिप्राय',
    profile_support_hub: 'सपोर्ट हब',
    profile_console: 'स्टोर कन्सोल',
    profile_payments: 'पमेंट',
    profile_subscriptions: 'माझे सबस्क्रिप्शन',
    profile_bank_verification: 'बँक पडताळणी', // NEW translation key
    profile_verified_merchant: 'व्हेरिफाईड व्यापारी',
    store_search_title: 'स्टोअर', // NEW
    store_search_sub: 'शोध', // NEW
    store_search_hint: 'विशिष्ट रिटेल नोड्स शोधा', // NEW
    store_search_placeholder: 'स्टोअरचे नाव किंवा पत्ता शोधा', // NEW
    store_search_no_results: 'કોઈ સ્ટોર મળ્યું નથી.', // NEW
    store_search_adjust_query: 'तुमची शोध क्वेरी समायोजित करण्याचा प्रयत्न करा.', // NEW
  },
  gu: {
    man_loading: 'એનાલિટિક્સ લોડ થાય છે...',
    man_error: 'એનાલિટિક્સ લોડ થઈ શક્યું નહીં. ફરી પ્રયાસ કરો.',
    man_retry: 'ફરી પ્રયાસ કરો',
    man_ai_dashboard: 'AI ઇનસાઇટ્સ ડેશબોર્ડ',
    man_ai_dashboard_sub: 'સંપૂર્ણ AI-આધારિત વિશ્લેષણ અને આગાહી',
    man_title: 'કેમ્પેન એનાલિટિક્સ',
    man_my_insights: 'મારા ઇનસાઇટ્સ',
    man_lifetime: 'આજીવન',
    man_n_days: '{n} દિવસ',
    man_campaigns: 'કેમ્પેન',
    man_active: 'સક્રિય',
    man_redeemed: 'રિડીમ થયું',
    man_campaign_status: 'કેમ્પેન સ્થિતિ',
    man_approved: 'મંજૂર',
    man_in_review: 'સમીક્ષામાં',
    man_needs_review: 'સમીક્ષા જરૂરી',
    man_expired: 'સમાપ્ત',
    man_campaign_trend: 'કેમ્પેન ટ્રેન્ડ',
    man_lifetime_analytics: 'આજીવન એનાલિટિક્સ',
    man_loading_lifetime: 'આજીવન ડેટા લોડ થાય છે...',
    man_total_clicks: 'કુલ ક્લિક',
    man_conversion_rate: 'કન્વર્ઝન રેટ',
    man_invites_sent: 'મોકલેલા આમંત્રણ',
    man_invites_accepted: 'સ્વીકારેલા આમંત્રણ',
    man_customer_loyalty: 'ગ્રાહક વફાદારી',
    man_no_redemption: 'હજી કોઈ રિડેમ્પશન ડેટા નથી. તમારી ડીલ રિડીમ કરનારા ગ્રાહકો અહીં દેખાશે.',
    man_total_customers: 'કુલ ગ્રાહકો',
    man_repeat: 'પુનરાવર્તિત',
    man_repeat_rate: 'પુનરાવર્તન દર',
    man_redemption_frequency: 'રિડેમ્પશન વારંવારતા',
    man_1_time: '1 વાર',
    man_2_times: '2 વાર',
    man_3_5_times: '3-5 વાર',
    man_6_plus_times: '6+ વાર',
    man_top_loyal: 'ટોચના વફાદાર ગ્રાહકો',
    man_customer: 'ગ્રાહક',
    man_n_different_deals: '{n} અલગ ડીલ',
    man_avg_redemptions: 'ગ્રાહક દીઠ સરેરાશ {n} રિડેમ્પશન',
    man_unable_customer: 'ગ્રાહક ડેટા લોડ થઈ શક્યો નહીં.',
    man_product_catalogue: 'પ્રોડક્ટ કૅટલૉગ',
    man_products: 'પ્રોડક્ટ',
    man_views: 'વ્યૂ',
    man_likes: 'લાઇક',
    man_top_performers: 'ટોચના પર્ફોર્મર',
    man_no_product_data: 'હજી કોઈ પ્રોડક્ટ ડેટા નથી',
    man_smart_insights: 'સ્માર્ટ ઇનસાઇટ્સ',
    man_top_category: 'ટોચની શ્રેણી',
    man_top_category_tip: 'આ શ્રેણીમાં વધુ પ્રોડક્ટ ઉમેરવા પર ધ્યાન આપો',
    man_avg_performance: 'સરેરાશ પ્રદર્શન',
    man_views_per_product: 'વ્યૂ/પ્રોડક્ટ',
    man_likes_per_product: 'લાઇક/પ્રોડક્ટ',
    man_needs_attention: 'ધ્યાન જરૂરી',
    man_n_products: '{n} પ્રોડક્ટ',
    man_needs_attention_tip: 'એંગેજમેન્ટ વધારવા છબીઓ કે વર્ણન અપડેટ કરો',
    man_performance_score: 'પ્રદર્શન સ્કોર',
    man_score_breakdown: 'સ્કોર વિગત',
    man_quick_wins: 'ઝડપી લાભ',
    man_view_ai_dashboard: 'AI ઇનસાઇટ્સ ડેશબોર્ડ જુઓ',
    man_calculating_score: 'તમારો પ્રદર્શન સ્કોર ગણાય છે...',
    man_ai_recommendations: 'AI ભલામણો',
    man_ai_analyzing: 'AI તમારો ડેટા વિશ્લેષણ કરે છે...',
    man_ai_analyzing_sub: 'તમે પ્રોડક્ટ ઉમેરશો અને ડીલ બનાવશો તેમ ઇનસાઇટ્સ દેખાશે',
    man_grade_excellent: 'ઉત્તમ',
    man_grade_good: 'સારું',
    man_grade_fair: 'ઠીક',
    man_grade_needs_improvement: 'સુધારો જરૂરી',
    man_impact_high: 'ઉચ્ચ',
    man_impact_medium: 'મધ્યમ',
    man_impact_low: 'નીચું',
    mnav_console: 'કન્સોલ',
    mnav_campaigns: 'ઝુંબેશો',
    mnav_catalogue: 'કૅટલોગ',
    mnav_dotd: 'આજની ડીલ',
    mnav_intel: 'વિશ્લેષણ',
    mnav_hub: 'પ્રોફાઇલ',
    app_name: 'ડીલપ્રો',
    login_header: 'સ્માર્ટ ડિસ્કવરી',
    login_sub: 'તમારી નજીકના વિશિષ્ટ ડીલ્સ અને ડિસ્કવન્ટ મેળવો.',
    login_placeholder_id: 'યુઝરનેમ / ઇમેઇલ',
    login_placeholder_pass: 'પાસવર્ડ',
    login_btn: 'સાઇન ઇન',
    login_forgot: 'પાસવર્ડ ભૂલી ગયા છો?',
    login_register_hint: 'ગ્રીડ પર નવા છો?',
    login_register_action: 'ઓળખ બનાવો',
    home_deals: 'ડીલ્સ',
    home_near_you: 'તમારી નજીક',
    home_daily_waves: 'દૈનિક ઓફર્સ',
    home_see_all: 'બધા ડીલ્સ અહીં જુઓ',
    home_adjust_range: 'વિસ્તાર બદલો',
    lang_select_title: 'ભાષા પસંદ કરો',
    lang_select_sub: 'સારા અનુભવ માટે તમારી ભાષા પસંદ કરો',
    reg_title: 'ગ્રીડમાં જોડાઓ',
    reg_consumer: 'ગ્રાહક',
    reg_merchant: 'વેપારી',
    reg_choose_account: 'શરૂ કરવા માટે તમારા ખાતાનો પ્રકાર પસંદ કરો',
    reg_consumer_desc: 'સ્થાનિક ડીલ્સ શોધવા અને પૈસા બચાવવા માટે નેટવર્કમાં જોડાઓ',
    reg_merchant_desc: 'DealPro ડિજિટલ તરંગો સાથે તમારા વ્યવસાયને સશક્ત બનાવો',
    reg_have_account: 'પહેલેથી જ ખાતું છે?',
    reg_back_login: 'લૉગિન પર પાછા જાઓ',
    reg_fullname: 'પૂરું નામ',
    reg_username: 'યુઝરનેમ',
    reg_email: 'ઇમેઇલ સરનામું',
    reg_password: 'પાસવર્ડ',
    reg_is_owner: 'તમે દુકાનના માલિક છો?',
    reg_brand: 'મુખ્ય સ્ટોરનું નામ - GST રજીસ્ટર્ડ',
    reg_category: 'વ્યવસાય શ્રેણી',
    reg_locations: 'દુકાનનું સ્થાન',
    reg_store_name_label: 'સ્ટોરનું નામ (દા.ત. મેઇન સ્ટ્રીટ બ્રાન્ચ)', // NEW
    reg_street: 'સરનામું',
    reg_state: 'રાજ્ય',
    reg_city: 'શહેર',
    reg_hours: 'કામકાજના કલાકો',
    reg_24h: '૨૪ કલાક',
    reg_opens: 'ખુલવાનો સમય',
    reg_closes: 'બંધ થવાનો સમય',
    reg_landmark: 'લેન્ડમાર્ક (વૈકલ્પિક)',
    reg_use_my_loc: 'મારું લોકેશન વાપરો',
    reg_sync_verified: 'સિંક સફળ',
    reg_add_outlet: 'બીજું આઉટલેટ ઉમેરો',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN કાર્ડ',
    reg_submit: 'ખાતું બનાવો',
    reg_verify: 'ચકાસો',
    loc_title: 'શોધ પરિમાણો',
    loc_sub: 'ગ્રીડ સ્કેનિંગ લોજિક',
    loc_radius: 'શોધ ત્રિજ્યા',
    loc_gps: 'જીપીએસ ટ્રેકિંગ',
    loc_manual: 'મેન્યુઅલ ગ્રીડ',
    loc_region: 'રાજ્ય પસંદ કરો',
    loc_city: 'શહેર પસંદ કરો',
    loc_area: 'વિસ્તાર પસંદ કરો',
    loc_scan_btn: 'વિસ્તાર સ્કેન કરો',
    loc_syncing: 'સિંક થઈ રહ્યું છે...',
    loc_resolving: 'લોકેશન શોધી રહ્યું છે',
    loc_locked: 'સિગ્નલ લોક થયું',
    loc_awaiting: 'લોકેશનની રાહ જોવાય છે',
    onboarding_1_headline: "સ્થાનિક શોધ",
    onboarding_1_sub: "ચોક્કસ જીપીએસ લોજિક સાથે તમારી નજીકની ખાસ ઓફર્સ શોધો.",
    onboarding_1_tag: "પ્રોક્સિમિટી ઇન્ટેલિજન્સ",
    onboarding_2_headline: "ફ્લેશ સેલ્સ",
    onboarding_2_sub: "વેપારીઓની ઓફર્સ પૂરી થાય તે પહેલાં તેનો લાભ લો.",
    onboarding_2_tag: "સમયની બચત",
    onboarding_3_headline: "વિશ્વાસપાત્રતા",
    onboarding_3_sub: "વેરિફાઇડ નોડ્સ અને સુરક્ષિત વાઉચર પ્રોટોકોલ તમને શ્રેષ્ઠ અનુભવ આપશે.",
    onboarding_3_tag: "ગ્રીડ સુરક્ષા",
    home_daily: 'આજની ડીલ',
    home_local_area: 'સ્થાનિક વિસ્તાર',
    home_your_area: 'તમારો વિસ્તાર',
    home_your_city: 'તમારું શહેર',
    home_your_sector: 'તમારો સેક્ટર',
    home_for_you: 'તમારા માટે',
    home_nearby_deals: 'નજીકની ડીલ્સ',
    home_all_deals: 'બધી ડીલ્સ',
    home_your_insights: 'તમારી સૂઝ',
    insight_love_category: 'તમે {category} ડીલ્સ પસંદ કરો છો - {count} દાવો કર્યો!',
    insight_nearby_deals: 'અત્યારે તમારી પાસે {count} સરસ ડીલ્સ',
    insight_new_deals: 'આ અઠવાડિયે {count} નવી ડીલ્સ શરૂ થઈ',
    insight_redeemed: 'તમે {count} ડીલ્સ રિડીમ કરી - મહાન સેવર!',
    insight_no_deals: 'હાલમાં કોઈ સક્રિય ડીલ્સ ઉપલબ્ધ નથી',
    home_deal_singular: 'ડીલ',
    home_deals_plural: 'ડીલ્સ',
    home_in: 'માં',
    home_no_deals_sector: 'આ સેક્ટરમાં હાલમાં ઓફર્સ નથી.',
    home_view_all: 'બધું જુઓ',
    home_syncing_grid: 'ગ્રીડ સિંક થઈ રહ્યું છે',
    details_redeem_btn: 'અત્યારે મેળવો',
    details_verifying: 'ચકાસણી થઈ રહી છે...',
    details_activating_for: 'રિવોર્ડ સક્રિય થઈ રહ્યો છે:',
    details_protocol: 'કેમ્પેઈન પ્રોટોકોલ',
    details_visit_intel: 'વિઝિટ ઇન્ટેલિજન્સ',
    details_start_gps: 'જીપીએસ શરૂ કરો',
    details_coordinates: 'દુકાનનું લોકેશન',
    details_landmark: 'નજીકની નિશાની',
    details_op_window: 'કામકાજના કલાકો',
    details_verified_node: 'વેરિફાઇડ ડીલપ્રો નોડ',
    details_instance_id: 'આઈડી નંબર',
    details_id_verified: 'ઓળખની પુષ્ટિ થઈ છે',
    details_present_counter: 'કાઉન્ટર પર બતાવો',
    details_exit_btn: 'બહાર નીકળો',
    history_title_1: 'રિડેમ્પશન',
    history_title_2: 'ઇતિહાસ',
    history_sub: 'તમારા રિડેમ્પશન',
    history_active_nodes: 'પરિણામો',
    history_rewards_label: 'રિવોર્ડ્સ',
    history_tab_all: 'બધા રિવોર્ડ્સ',
    history_tab_pending: 'મુલાકાતની રાહ',
    history_syncing: 'માહિતી સિંક થઈ રહી છે...',
    history_empty_title: 'વોલ્ટ સિંક થયો',
    history_empty_sub_pending: 'બધા ડીલ્સ વેરિફાઇડ છે. કોઈ મુલાકાત બાકી નથી.',
    history_empty_sub_all: 'તમારા ખાતામાં રિડેમ્પશન રેકોર્ડ્સ નથી.',
    history_search_btn: 'ગ્રીડ એક્સપ્લોર કરો',
    history_status_verified: 'વિઝિટ વેરિફાઇડ',
    history_status_awaiting: 'મુલાકાતની રાહ',
    history_page_label: 'પેજ',
    history_of: 'નું',
    history_ledger_end: 'રેકોર્ડ સમાપ્ત',
    history_voucher_security: 'વાઉચર સુરક્ષા',
    history_transaction_logged: 'વ્યવહાર નોંધાયો',
    history_present_counter: 'કાઉન્ટર પર બતાવો',
    history_ref_label: 'REF',
    history_voucher_node: 'વાઉચર નોડ',
    history_rate_exp: 'અનુભવ રેટ કરો',
    status_live: 'લાઇવ',
    status_expired: 'મુદત પૂરી થઈ',
    favorites_title_1: 'તમારા',
    favorites_title_2: 'મનપસંદ',
    favorites_sub: 'સેવ કરેલા ડીલ્સ ગમે ત્યારે જુઓ',
    favorites_syncing: 'ડેટા સિંક થઈ રહ્યો છે',
    favorites_empty_title: 'લિસ્ટ ખાલી છે',
    favorites_empty_sub: 'હાર્ટ આઇકોન પર ક્લિક કરીને ડીલ્સ સેવ કરો.',
    profile_elite_member: 'એલિટ મેમ્બર',
    profile_verif_hub: 'વેરિફિકેશન હબ',
    profile_verif_sub: 'વિઝિટ વેરિફાઇ કરો',
    profile_edit: 'પ્રોફાઇલ સંપાદિત કરો',
    profile_edit_store: 'દુકાનની પ્રોફાઇલ સંપાદિત કરો',
    profile_favs: 'મારા મનપસંદ ડીલ્સ',
    profile_invite_friend: 'મિત્રને આમંત્રણ આપો',
    profile_invite_partner: 'ભાગીદારને આમંત્રણ આપો',
    profile_invite_placeholder: 'ઇમેઇલ અથવા ફોન નંબર',
    profile_invite_success: 'આમંત્રણ મોકલવામાં આવ્યું',
    profile_help: 'મદદ અને પ્રતિભાવ',
    profile_support_hub: 'સપોર્ટ હબ',
    profile_console: 'સ્ટોર કન્સોલ',
    profile_payments: 'ચુકવણી',
    profile_subscriptions: 'મારા સબ્સ્ક્રિપ્શન',
    profile_bank_verification: 'બેંક ચકાસણી', // NEW translation key
    profile_verified_merchant: 'વેરિફાઇડ વેપારી',
    store_search_title: 'સ્ટોર', // NEW
    store_search_sub: 'શોધ', // NEW
    store_search_hint: 'વિશિષ્ટ રિટેલ નોડ્સ શોધો', // NEW
    store_search_placeholder: 'સ્ટોરનું નામ અથવા સરનામું શોધો', // NEW
    store_search_no_results: 'કોઈ સ્ટોર મળ્યું નથી.', // NEW
    store_search_adjust_query: 'તમારી શોધ ક્વેરીને સમાયોજિત કરવાનો પ્રયાસ કરો.', // NEW
  }
};

// Merge merchant-specific translations into DICTIONARY
for (const [lang, translations] of Object.entries(MERCHANT_TRANSLATIONS)) {
  if (DICTIONARY[lang]) {
    Object.assign(DICTIONARY[lang], translations);
  } else {
    DICTIONARY[lang] = translations;
  }
}

// Merge merchant signup-wizard (onboarding) translations into DICTIONARY
for (const [lang, translations] of Object.entries(ONBOARDING_TRANSLATIONS)) {
  if (DICTIONARY[lang]) {
    Object.assign(DICTIONARY[lang], translations);
  } else {
    DICTIONARY[lang] = translations;
  }
}

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
  getLocalizedText: (localizedData?: Record<string, string>, fallbackText?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocale] = useState<Locale>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const loadLanguagePreference = async () => {
      try {
        // Try to get from localStorage (web) or Capacitor Preferences (mobile)
        const storedLang = localStorage.getItem('userLanguagePreference');
        if (storedLang && ['en', 'kn', 'hi', 'ta', 'te', 'ml', 'bn', 'mr', 'gu'].includes(storedLang)) {
          setLocale(storedLang as Locale);
          console.log('[LanguageContext] Loaded language preference from storage:', storedLang);
        }
      } catch (error) {
        console.error('[LanguageContext] Failed to load language preference:', error);
      }
    };
    loadLanguagePreference();
  }, []);

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    try {
      localStorage.setItem('userLanguagePreference', locale);
      console.log('[LanguageContext] Saved language preference to storage:', locale);
    } catch (error) {
      console.error('[LanguageContext] Failed to save language preference:', error);
    }
  }, [locale]);

  const t = (key: string) => {
    return DICTIONARY[locale]?.[key] || DICTIONARY['en']?.[key] || key;
  };

  const getLocalizedText = (localizedData?: Record<string, any>, fallbackText?: string): string => {
    if (!localizedData || typeof localizedData !== 'object') return fallbackText || '';
    const localized = localizedData[locale];
    if (localized && typeof localized === 'string' && localized.trim() !== '') {
      return localized;
    }
    const englishFallback = localizedData['en'];
    if (englishFallback && typeof englishFallback === 'string' && englishFallback.trim() !== '') {
      return englishFallback;
    }
    return fallbackText || '';
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, getLocalizedText }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};