

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Locale } from '../types';

interface Dictionary {
  [key: string]: {
    [key: string]: string;
  };
}

const DICTIONARY: Dictionary = {
  en: {
    app_name: 'DealPro',
    login_header: 'Smart Discovery',
    login_sub: 'Unlock exclusive Deals & Discounts near you.',
    login_placeholder_id: 'Username / Email',
    login_placeholder_pass: 'Password',
    login_btn: 'Sign in',
    login_forgot: 'Forgot password?',
    login_register_hint: 'New to DealPro?',
    login_register_action: 'Create Account',
    home_deals: 'Deals',
    home_near_you: 'NEAR YOU',
    home_daily_waves: 'Daily WAVES',
    home_see_all: 'See all deals in',
    home_adjust_range: 'ADJUST RANGE',
    lang_select_title: 'Select Language',
    lang_select_sub: 'Choose your language for better experience',
    reg_title: 'JOIN THE GRID',
    reg_consumer: 'Consumer',
    reg_merchant: 'Merchant',
    reg_choose_account: 'Choose your account type to get started',
    reg_consumer_desc: 'Join the network to discover local deals and save money',
    reg_merchant_desc: 'Empower your business with DealPro digital waves',
    reg_have_account: 'Already have an account?',
    reg_back_login: 'Back to Login',
    reg_fullname: 'Full Name',
    reg_username: 'Username',
    reg_email: 'Email Address',
    reg_password: 'Password',
    reg_is_owner: 'Are you Store Owner',
    reg_brand: 'Main Store Name - GST Registered',
    reg_category: 'Business Category',
    reg_locations: 'Retail Store Locations',
    reg_store_name_label: 'Store Name (e.g., Main Street Branch)', // NEW
    reg_street: 'Street Address',
    reg_state: 'State',
    reg_city: 'City',
    reg_hours: 'Operating Hours',
    reg_24h: '24 Hrs',
    reg_opens: 'Opens',
    reg_closes: 'Closes',
    reg_landmark: 'Landmark (Optional)',
    reg_use_my_loc: 'Use My Location',
    reg_sync_verified: 'Sync Verified',
    reg_add_outlet: 'Add Another Outlet',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN Card',
    reg_submit: 'Create my account',
    reg_verify: 'Verify',
    loc_title: 'Discovery Parameters',
    loc_sub: 'Grid Scanning Logic',
    loc_radius: 'Search Radius',
    loc_gps: 'GPS Tracking',
    loc_manual: 'Manual Grid',
    loc_region: 'Select Region',
    loc_city: 'Select City',
    loc_area: 'Select Area',
    loc_scan_btn: 'Scan Area',
    loc_syncing: 'Syncing Localities...',
    loc_resolving: 'Resolving Coordinates',
    loc_locked: 'Signal Locked',
    loc_awaiting: 'Awaiting Location',
    onboarding_1_headline: "Hyper-Local Discovery",
    onboarding_1_sub: "Pinpoint exclusive retail opportunities in your immediate vicinity with precision GPS logic.",
    onboarding_1_tag: "Proximity Intelligence",
    onboarding_2_headline: "Real-Time Flash Sales",
    onboarding_2_sub: "Synchronize with active merchant waves and capture high-value incentives before they expire.",
    onboarding_2_tag: "Temporal Efficiency",
    onboarding_3_headline: "Institutional Trust",
    onboarding_3_sub: "Verified nodes and secure voucher protocols ensure a premium local shopping experience.",
    onboarding_3_tag: "Grid Security",
    home_daily: "Today's Deal",
    home_local_area: 'Local Area',
    home_your_sector: 'Your Sector',
    home_deal_singular: 'deal',
    home_deals_plural: 'deals',
    home_in: 'in',
    home_no_deals_sector: 'No active waves in this sector.',
    home_view_all: 'VIEW ALL',
    home_syncing_grid: 'Syncing Grid',
    details_redeem_btn: 'REDEEM NOW',
    details_verifying: 'Verifying...',
    details_activating_for: 'Activating Reward For:',
    details_protocol: 'Campaign Protocol',
    details_visit_intel: 'Visit Intelligence',
    details_start_gps: 'Start GPS',
    details_coordinates: 'Store Coordinates',
    details_landmark: 'Proximity Landmark',
    details_op_window: 'Operational Window',
    details_verified_node: 'Verified DealPro Node',
    details_instance_id: 'INSTANCE ID',
    details_id_verified: 'Identity Verified',
    details_present_counter: 'Present at node counter',
    details_exit_btn: 'Exit Dashboard',
    history_title_1: 'Redemption',
    history_title_2: 'History',
    history_sub: 'Your Redemptions',
    history_active_nodes: 'results',
    history_rewards_label: 'Rewards',
    history_tab_all: 'All Rewards',
    history_tab_pending: 'Awaiting Visit',
    history_syncing: 'Syncing Redemptions...',
    history_empty_title: 'Vault Synchronized',
    history_empty_sub_pending: 'All deals are verified. No pending store visits detected.',
    history_empty_sub_all: 'No activation records found in this identity sector.',
    history_search_btn: 'Explore Grid',
    history_status_verified: 'Visit Verified',
    history_status_awaiting: 'Awaiting Visit',
    history_page_label: 'Page',
    history_of: 'of',
    history_ledger_end: 'Secure Grid Ledger End',
    history_voucher_security: 'Voucher Security',
    history_transaction_logged: 'Transaction Logged',
    history_present_counter: 'Present at counter',
    history_ref_label: 'REF',
    history_voucher_node: 'Voucher Node',
    history_rate_exp: 'Rate Experience',
    status_live: 'Live',
    status_expired: 'Expired',
    favorites_title_1: 'Your',
    favorites_title_2: 'Favorites',
    favorites_sub: 'Access your saved deals anytime',
    favorites_syncing: 'Syncing Vault Data',
    favorites_empty_title: 'Vault Empty',
    favorites_empty_sub: 'Capture exclusive deals by tapping the heart icon in discovery mode.',
    profile_elite_member: 'Elite Member',
    profile_verif_hub: 'Verification Hub',
    profile_verif_sub: 'Verify store visits',
    profile_edit: 'Edit Profile',
    profile_edit_store: 'Edit Store Profile',
    profile_favs: 'My Favorites',
    profile_invite_friend: 'Invite a Friend',
    profile_invite_partner: 'Invite a Partner',
    profile_invite_placeholder: 'Email or phone number',
    profile_invite_success: 'Invite sent to your friend',
    profile_help: 'Help & Feedback',
    profile_support_hub: 'Support Hub',
    profile_console: 'Store Console',
    profile_payments: 'Payments',
    profile_subscriptions: 'My Subscriptions',
    profile_bank_verification: 'Bank Verification', // NEW translation key
    profile_verified_merchant: 'Verified Merchant',
    store_search_title: 'Store', // NEW
    store_search_sub: 'Discovery', // NEW
    store_search_hint: 'Locate specific retail nodes', // NEW
    store_search_placeholder: 'Search store name or address', // NEW
    store_search_no_results: 'No stores found.', // NEW
    store_search_adjust_query: 'Try adjusting your search query.', // NEW
  },
  kn: {
    app_name: 'ಡೀಲ್‌ಪ್ರೊ',
    login_header: 'ಸ್ಮಾರ್ಟ್ ಅನ್ವೇಷಣೆ',
    login_sub: 'ನಿಮ್ಮ ಹತ್ತಿರವಿರುವ ವಿಶೇಷ ಡೀಲ್‌ಗಳು ಮತ್ತು ರಿಯಾಯಿತಿಗಳನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಿ.',
    login_placeholder_id: 'ಬಳಕೆದಾರಹೆಸರು / ಇಮೇಲ್',
    login_placeholder_pass: 'ಪಾಸ್‌ವರ್ಡ್',
    login_btn: 'ಸೈನ್ ಇನ್',
    login_forgot: 'ರುಜುವಾತುಗಳನ್ನು ಮರೆತಿರುವಿರಾ?',
    login_register_hint: 'ಗ್ರಿಡ್‌ಗೆ ಹೊಸಬರೇ?',
    login_register_action: 'ಗುರುತನ್ನು ಸ್ಥಾಪಿಸಿ',
    home_deals: 'ಡೀಲ್‌ಗಳು',
    home_near_you: 'ನಿಮ್ಮ ಹತ್ತಿರ',
    home_daily_waves: 'ದೈನಂದಿನ ವೇವ್ಸ್',
    home_see_all: 'ಎಲ್ಲಾ ಡೀಲ್‌ಗಳನ್ನು ಇಲ್ಲಿ ನೋಡಿ',
    home_adjust_range: 'ಶ್ರೇಣಿಯನ್ನು ಹೊಂದಿಸಿ',
    lang_select_title: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    lang_select_sub: 'ಉತ್ತಮ ಅನುಭವಕ್ಕಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    reg_title: 'ಗ್ರಿಡ್‌ಗೆ ಸೇರಿ',
    reg_consumer: 'ಗ್ರಾಹಕ',
    reg_merchant: 'ವ್ಯಾಪಾರಿ',
    reg_choose_account: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಖಾತೆ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ',
    reg_consumer_desc: 'ಸ್ಥಳೀಯ ಡೀಲ್‌ಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಮತ್ತು ಹಣವನ್ನು ಉಳಿಸಲು ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ',
    reg_merchant_desc: 'DealPro ಡಿಜಿಟಲ್ ತರಂಗಗಳೊಂದಿಗೆ ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಸಬಲಗೊಳಿಸಿ',
    reg_have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
    reg_back_login: 'ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    reg_fullname: 'ಪೂರ್ಣ ಹೆಸರು',
    reg_username: 'ಬಳಕೆದಾರಹೆಸರು',
    reg_email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    reg_password: 'ಪಾಸ್‌ವರ್ಡ್',
    reg_is_owner: 'ನೀವು ಅಂಗಡಿ ಮಾಲೀಕರೆ?',
    reg_brand: 'ಮುಖ್ಯ ಅಂಗಡಿ ಹೆಸರು - GST ನೋಂದಾಯಿತ',
    reg_category: 'ವ್ಯಾಪಾರ ವರ್ಗ',
    reg_locations: 'ಚಿಲ್ಲರೆ ಅಂಗಡಿ ಸ್ಥಳಗಳು',
    reg_store_name_label: 'ಅಂಗಡಿ ಹೆಸರು (ಉದಾ. ಮುಖ್ಯ ರಸ್ತೆ ಶಾಖೆ)', // NEW
    reg_street: 'ಬೀದಿ ವಿಳಾಸ',
    reg_state: 'ರಾಜ್ಯ',
    reg_city: 'ನಗರ',
    reg_hours: 'ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಸಮಯ',
    reg_24h: '24 ಗಂಟೆ',
    reg_opens: 'ತೆರೆಯುತ್ತದೆ',
    reg_closes: 'ಮುಚ್ಚುತ್ತದೆ',
    reg_landmark: 'ಗುರುತು (ಐಚ್ಛಿಕ)',
    reg_use_my_loc: 'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ',
    reg_sync_verified: 'ಸಿಂಕ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    reg_add_outlet: 'ಇನ್ನೊಂದು ಮಳಿಗೆ ಸೇರಿಸಿ',
    reg_gstin: 'GSTIN',
    reg_pan: 'ಪ್ಯಾನ್ ಕಾರ್ಡ್',
    reg_submit: 'ನನ್ನ ಖಾತೆ ರಚಿಸಿ',
    reg_verify: 'ಪರಿಶೀಲಿಸಿ',
    loc_title: 'ಅನ್ವೇಷಣೆಯ ನಿಯತಾಂಕಗಳು',
    loc_sub: 'ಗ್ರಿಡ್ ಸ್ಕ್ಯಾನಿಂಗ್ ತರ್ಕ',
    loc_radius: 'ಹುಡುಕಾಟದ ತ್ರಿಜ್ಯ',
    loc_gps: 'ಜಿಪಿಎಸ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    loc_manual: 'ಮ್ಯಾನ್ಯುವಲ್ ಗ್ರಿಡ್',
    loc_region: 'ಪ್ರದೇಶವನ್ನು ಆರಿಸಿ',
    loc_city: 'ನಗರವನ್ನು ಆರಿಸಿ',
    loc_area: 'ಸ್ಥಳವನ್ನು ಆರಿಸಿ',
    loc_scan_btn: 'ಪ್ರದೇಶವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    loc_syncing: 'ಸಿಂಕ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    loc_resolving: 'ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ',
    loc_locked: 'ಸಿಗ್ನಲ್ ಲಾಕ್ ಆಗಿದೆ',
    loc_awaiting: 'ಸ್ಥಳಕ್ಕಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    onboarding_1_headline: "ಸ್ಥಳೀಯ ಅನ್ವೇಷಣೆ",
    onboarding_1_sub: "ನಿಖರವಾದ ಜಿಪಿಎಸ್ ತರ್ಕದೊಂದಿಗೆ ನಿಮ್ಮ ಸಮೀಪದಲ್ಲಿರುವ ವಿಶೇಷ ಚಿಲ್ಲರೆ ಅವಕಾಶಗಳನ್ನು ಗುರುತಿಸಿ.",
    onboarding_1_tag: "ಸ್ಥಳೀಯ ಬುದ್ಧಿವಂತಿಕೆ",
    onboarding_2_headline: "ತಕ್ಷಣದ ಮಾರಾಟ",
    onboarding_2_sub: "ಸಕ್ರಿಯ ವ್ಯಾಪಾರಿ ಕೊಡುಗೆಗಳೊಂದಿಗೆ ಸಿಂಕ್ ಮಾಡಿ ಮತ್ತು ಅವು ಮುಕ್ತಾಯಗೊಳ್ಳುವ ಮೊದಲೇ ಪಡೆದುಕೊಳ್ಳಿ.",
    onboarding_2_tag: "ಸಮಯದ ದಕ್ಷತೆ",
    onboarding_3_headline: "ಸಂಸ್ಥೆಯ ನಂಬಿಕೆ",
    onboarding_3_sub: "ಪರಿಶೀಲಿಸಿದ ನೋಡ್‌ಗಳು ಮತ್ತು ಸುರಕ್ಷಿತ ವೋಚರ್ ಪ್ರೋಟೋಕಾಲ್‌ಗಳು ಪ್ರೀಮಿಯಂ ಶಾಪಿಂಗ್ ಅನುಭವವನ್ನು ಖಚಿತಪಡಿಸುತ್ತವೆ.",
    onboarding_3_tag: "ಗ್ರಿಡ್ ಭದ್ರತೆ",
    home_daily: 'ಇಂದಿನ ಡೀಲ್',
    home_local_area: 'ಸ್ಥಳೀಯ ಪ್ರದೇಶ',
    home_your_sector: 'ನಿಮ್ಮ ವಲಯ',
    home_deal_singular: 'ಕೊಡುಗೆ',
    home_deals_plural: 'ಕೊಡುಗೆಗಳು',
    home_in: 'ನಲ್ಲಿ',
    home_no_deals_sector: 'ಈ ವಲಯದಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ಕೊಡುಗೆಗಳಿಲ್ಲ.',
    home_view_all: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    home_syncing_grid: 'ಗ್ರಿಡ್ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ',
    details_redeem_btn: 'ಈಗಲೇ ಪಡೆದುಕೊಳ್ಳಿ',
    details_verifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    details_activating_for: 'ಬಹುಮಾನವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲಾಗುತ್ತಿದೆ:',
    details_protocol: 'ಕಾರ್ಯಕ್ರಮದ ಶಿಷ್ಟಾಚಾರ',
    details_visit_intel: 'ಸ್ಥಳದ ಮಾಹಿತಿ',
    details_start_gps: 'ಜಿಪಿಎಸ್ ಪ್ರಾರಂಭಿಸಿ',
    details_coordinates: 'ಅಂಗಡಿಯ ವಿಳಾಸ',
    details_landmark: 'ಹತ್ತಿರದ ಗುರುತು',
    details_op_window: 'ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಸಮಯ',
    details_verified_node: 'ಪರಿಶೀಲಿಸಿದ ಡೀಲ್‌ಪ್ರೊ ಕೇಂದ್ರ',
    details_instance_id: 'ಐಡಿ ಸಂಖ್ಯೆ',
    details_id_verified: 'ಗುರುತು ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    details_present_counter: 'ಕೌಂಟರ್‌ನಲ್ಲಿ ತೋರಿಸಿ',
    details_exit_btn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಧಿನಿಂದ ನಿರ್ಗಮಿಸಿ',
    history_title_1: 'ಪಡೆದುಕೊಂಡ',
    history_title_2: 'ಇತಿಹಾಸ',
    history_sub: 'ನಿಮ್ಮ ಕೊಡುಗೆಗಳು',
    history_active_nodes: 'ಫಲಿತಾಂಶಗಳು',
    history_rewards_label: 'ಬಹುಮಾನಗಳು',
    history_tab_all: 'ಎಲ್ಲಾ ಬಹುಮಾನಗಳು',
    history_tab_pending: 'ಭೇಟಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    history_syncing: 'ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    history_empty_title: 'ವಾಲ್ಟ್ ಸಿಂಕ್ ಆಗಿದೆ',
    history_empty_sub_pending: 'ಎಲ್ಲಾ ಡೀಲ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ. ಯಾವುದೇ ಬಾಕಿ ಇರುವ ಅಂಗಡಿ ಭೇಟಿಗಳಿಲ್ಲ.',
    history_empty_sub_all: 'ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಯಾವುದೇ ಬಹುಮಾನಗಳ ದಾಖಲೆ ಇಲ್ಲ.',
    history_search_btn: 'ಗ್ರಿಡ್ ಅನ್ವೇಷಿಸಿ',
    history_status_verified: 'ಭೇಟಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    history_status_awaiting: 'ಭೇಟಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    history_page_label: 'ಪುಟ',
    history_of: 'ರಲ್ಲಿ',
    history_ledger_end: 'ದಾಖಲೆ ಮುಕ್ತಾಯ',
    history_voucher_security: 'ವೋಚರ್ ಭದ್ರತೆ',
    history_transaction_logged: 'ವಹಿವಾಟು ದಾಖಲಾಗಿದೆ',
    history_present_counter: 'ಕೌಂಟರ್‌ನಲ್ಲಿ ತೋರಿಸಿ',
    history_ref_label: 'REF',
    history_voucher_node: 'ವೋಚರ್ ಕೇಂದ್ರ',
    history_rate_exp: 'ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ',
    status_live: 'ಲೈವ್',
    status_expired: 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
    favorites_title_1: 'ನಿಮ್ಮ',
    favorites_title_2: 'ಮೆಚ್ಚಿನವುಗಳು',
    favorites_sub: 'ನಿಮ್ಮ ಉಳಿಸಿದ ಕೊಡುಗೆಗಳನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ವೀಕ್ಷಿಸಿ',
    favorites_syncing: 'ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ',
    favorites_empty_title: 'ಯಾವುದೂ ಇಲ್ಲ',
    favorites_empty_sub: 'ಅನ್ವೇಷಣೆಯಲ್ಲಿ ಹಾರ್ಟ್ ಐಕಾನ್ ಒತ್ತುವ ಮೂಲಕ ಕೊಡುಗೆಗಳನ್ನು ಉಳಿಸಿ.',
    profile_elite_member: 'ಗಣ್ಯ ಸದಸ್ಯ',
    profile_verif_hub: 'ಪರಿಶೀಲನಾ ಹಬ್',
    profile_verif_sub: 'ಭೇಟಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    profile_edit: 'ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ',
    profile_edit_store: 'ಅಂಗಡಿ ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ',
    profile_favs: 'ನನ್ನ ಮೆಚ್ಚಿನವುಗಳು',
    profile_invite_friend: 'ಸ್ನೇಹಿತರನ್ನು ಆಹ್ವಾನಿಸಿ',
    profile_invite_partner: 'ಪಾಲುದಾರರನ್ನು ಆಹ್ವಾನಿಸಿ',
    profile_invite_placeholder: 'ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ',
    profile_invite_success: 'ಆಹ್ವಾನವನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ',
    profile_help: 'ಸಹಾಯ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ',
    profile_support_hub: 'ಬೆಂಬಲ ಕೇಂದ್ರ',
    profile_console: 'ಅಂಗಡಿ ಕನ್ಸೋಲ್',
    profile_payments: 'ಪಾವತಿಗಳು',
    profile_subscriptions: 'ನನ್ನ ಚಂದಾದಾರಿಕೆಗಳು',
    profile_bank_verification: 'ಬ್ಯಾಂಕ್ ಪರಿಶೀಲನೆ', // NEW translation key
    profile_verified_merchant: 'ಪರಿಶೀಲಿಸಿದ ವ್ಯಾಪಾರಿ',
    store_search_title: 'ಸ್ಟೋರ್', // NEW
    store_search_sub: 'ಅನ್ವೇಷಣೆ', // NEW
    store_search_hint: 'ನಿರ್ದಿಷ್ಟ ಚಿಲ್ಲರೆ ಕೇಂದ್ರಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ', // NEW
    store_search_placeholder: 'ಸ್ಟೋರ್ ಹೆಸರು ಅಥವಾ ವಿಳಾಸವನ್ನು ಹುಡುಕಿ', // NEW
    store_search_no_results: 'ಯಾವುದೇ ಅಂಗಡಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', // NEW
    store_search_adjust_query: 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಪ್ರಶ್ನೆಯನ್ನು ಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.', // NEW
  },
  hi: {
    app_name: 'डीलप्रो',
    login_header: 'स्मार्ट खोज',
    login_sub: 'अपने पास के विशेष डील्स और छूट का लाभ उठाएं।',
    login_placeholder_id: 'यूजरनेम / ईमेल',
    login_placeholder_pass: 'पासवर्ड',
    login_btn: 'साइन इन',
    login_forgot: 'पासवर्ड भूल गए?',
    login_register_hint: 'ग्रिड पर नए हैं?',
    login_register_action: 'पहचान बनाएं',
    home_deals: 'डील्स',
    home_near_you: ' आपके पास',
    home_daily_waves: 'दैनिक वेव्स',
    home_see_all: 'सभी डील्स देखें',
    home_adjust_range: 'दूरी बदलें',
    lang_select_title: 'भाषा चुनें',
    lang_select_sub: 'बेहतर अनुभव के लिए अपनी भाषा चुनें',
    reg_title: 'ग्रिड से जुड़ें',
    reg_consumer: 'ग्राहक',
    reg_merchant: 'व्यापारी',
    reg_choose_account: 'शुरू करने के लिए अपना खाता प्रकार चुनें',
    reg_consumer_desc: 'स्थानीय डील्स खोजने और पैसे बचाने के लिए नेटवर्क से जुड़ें',
    reg_merchant_desc: 'DealPro डिजिटल वेव्स के साथ अपने व्यवसाय को सशक्त बनाएं',
    reg_have_account: 'पहले से खाता है?',
    reg_back_login: 'लॉगिन पर वापस जाएं',
    reg_fullname: 'पूरा नाम',
    reg_username: 'यूजरनेम',
    reg_email: 'ईमेल पता',
    reg_password: 'पासवर्ड',
    reg_is_owner: 'क्या आप स्टोर के मालिक हैं?',
    reg_brand: 'मुख्य स्टोर का नाम - GST रजिस्टर्ड',
    reg_category: 'व्यवसाय श्रेणी',
    reg_locations: 'स्टोर का स्थान',
    reg_store_name_label: 'स्टोर का नाम (उदा. मेन स्ट्रीट ब्रांच)', // NEW
    reg_street: 'पता',
    reg_state: 'राज्य',
    reg_city: 'शहर',
    reg_hours: 'कार्य का समय',
    reg_24h: '24 घंटे',
    reg_opens: 'खुलता है',
    reg_closes: 'बंद होता है',
    reg_landmark: 'लैंडमार्क (वैकल्पिक)',
    reg_use_my_loc: 'मेरे स्थान का उपयोग करें',
    reg_sync_verified: 'सिंक सत्यापित',
    reg_add_outlet: 'एक और आउटलेट जोड़ें',
    reg_gstin: 'GSTIN',
    reg_pan: 'पैन कार्ड',
    reg_submit: 'मेरा खाता बनाएं',
    reg_verify: 'सत्यापित करें',
    loc_title: 'खोज के मानक',
    loc_sub: 'ग्रिड स्कैनिंग लॉजिक',
    loc_radius: 'खोज का दायरा',
    loc_gps: 'जीपीएस ट्रैकिंग',
    loc_manual: 'मैन्युअल ग्रिड',
    loc_region: 'राज्य चुनें',
    loc_city: 'शहर चुनें',
    loc_area: 'इलाका चुनें',
    loc_scan_btn: 'क्षेत्र स्कैन करें',
    loc_syncing: 'इलाकों को सिंक कर रहे हैं...',
    loc_resolving: 'लोकेशन का पता लगा रहे हैं',
    loc_locked: 'सिग्नल लॉक',
    loc_awaiting: 'लोकेशन की प्रतीक्षा',
    onboarding_1_headline: "हाइपर-लोकल खोज",
    onboarding_1_sub: "सटीक जीपीएस लॉजिक के साथ अपने तत्काल क्षेत्र में विशेष खुदरा अवसरों का पता लगाएं।",
    onboarding_1_tag: "प्रोक्सिमिटी इंटेलिजेंस",
    onboarding_2_headline: "रीयल-टाइम फ्लैश सेल",
    onboarding_2_sub: "सक्रिय मर्चेंट वेव्स के साथ सिंक करें और समाप्त होने से पहले उच्च मूल्य के लाभ प्राप्त करें।",
    onboarding_2_tag: "समय की बचत",
    onboarding_3_headline: "संस्थागत विश्वास",
    onboarding_3_sub: "सत्यापित नोड्स और सुरक्षित वाउचर प्रोटोकॉल एक प्रीमियम स्थानीय खरीदारी अनुभव सुनिश्चित करते हैं।",
    onboarding_3_tag: "ग्रिड सुरक्षा",
    home_daily: 'आज का सौदा',
    home_local_area: 'स्थानीय क्षेत्र',
    home_your_sector: 'आपका क्षेत्र',
    home_deal_singular: 'डील',
    home_deals_plural: 'डील्स',
    home_in: 'में',
    home_no_deals_sector: 'इस क्षेत्र में कोई सक्रिय डील नहीं है।',
    home_view_all: 'सभी देखें',
    home_syncing_grid: 'ग्रिड सिंक हो रहा है',
    details_redeem_btn: 'अभी रिडीम करें',
    details_verifying: 'सत्यापित हो रहा है...',
    details_activating_for: 'रिवॉर्ड इसके लिए सक्रिय:',
    details_protocol: 'अभियान प्रोटोकॉल',
    details_visit_intel: 'विजिट इंटेलिजेंस',
    details_start_gps: 'जीपीएस शुरू करें',
    details_coordinates: 'स्टोर का पता',
    details_landmark: 'निकटतम स्थान',
    details_op_window: 'कार्य का समय',
    details_verified_node: 'सत्यापित डीलप्रो नोड',
    details_instance_id: 'आईडी नंबर',
    details_id_verified: 'पहचान सत्यापित',
    details_present_counter: 'काउंटर पर दिखाएं',
    details_exit_btn: 'डैशबोर्ड से बाहर निकलें',
    history_title_1: 'रिडेम्पशन',
    history_title_2: 'इतिहास',
    history_sub: 'आपके रिडेम्पशन',
    history_active_nodes: 'परिणाम',
    history_rewards_label: 'रिवॉर्ड्स',
    history_tab_all: 'सभी रिवॉर्ड्स',
    history_tab_pending: 'भेंट की प्रतीक्षा',
    history_syncing: 'जानकारी सिंक हो रही है...',
    history_empty_title: 'वॉल्ट सिंक हो गया',
    history_empty_sub_pending: 'सभी डील्स सत्यापित हैं। कोई भी दुकान भेंट लंबित नहीं है।',
    history_empty_sub_all: 'आपके खाते में कोई रिवॉर्ड रिकॉर्ड नहीं मिला।',
    history_search_btn: 'ग्रिड खोजें',
    history_status_verified: 'भेंट सत्यापित',
    history_status_awaiting: 'भेंट की प्रतीक्षा',
    history_page_label: 'पेज',
    history_of: 'का',
    history_ledger_end: 'रिकॉर्ड समाप्त',
    history_voucher_security: 'वाउचर सुरक्षा',
    history_transaction_logged: 'लेनदेन दर्ज',
    history_present_counter: 'काउंटर पर दिखाएं',
    history_ref_label: 'REF',
    history_voucher_node: 'वाउचर नोड',
    history_rate_exp: 'अनुभव को रेट करें',
    status_live: 'लाइव',
    status_expired: 'समाप्त',
    favorites_title_1: 'आपके',
    favorites_title_2: 'पसंदीदा',
    favorites_sub: 'अपने सहेजे गए डील्स कभी भी देखें',
    favorites_syncing: 'डेटा सिंक हो रहा है',
    favorites_empty_title: 'कोई पसंदीदा नहीं',
    favorites_empty_sub: 'खोज मोड में दिल के आइकन पर टैप करके डील्स सहेजें।',
    profile_elite_member: 'एलीट सदस्य',
    profile_verif_hub: 'सत्यापन हब',
    profile_verif_sub: 'दुकान की यात्राएं सत्यापित करें',
    profile_edit: 'प्रोफ़ाइल बदलें',
    profile_edit_store: 'स्टोर प्रोफ़ाइल बदलें',
    profile_favs: 'मेरी पसंदीदा सूची',
    profile_invite_friend: 'दोस्त को आमंत्रित करें',
    profile_invite_partner: 'पार्टनर को आमंत्रित करें',
    profile_invite_placeholder: 'ईमेल या फोन नंबर',
    profile_invite_success: 'आमंत्रण भेज दिया गया है',
    profile_help: 'सहायता और प्रतिक्रिया',
    profile_support_hub: 'सपोर्ट हब',
    profile_console: 'स्टोर कंसोल',
    profile_payments: 'भुगतान',
    profile_subscriptions: 'मेरी सदस्यताएं',
    profile_bank_verification: 'बैंक सत्यापन', // NEW translation key
    profile_verified_merchant: 'सत्यापित व्यापारी',
    store_search_title: 'स्टोर', // NEW
    store_search_sub: 'खोज', // NEW
    store_search_hint: 'विशिष्ट खुदरा नोड्स का पता लगाएं', // NEW
    store_search_placeholder: 'स्टोर का नाम या पता खोजें', // NEW
    store_search_no_results: 'कोई स्टोर नहीं मिला।', // NEW
    store_search_adjust_query: 'अपनी खोज क्वेरी को समायोजित करने का प्रयास करें।', // NEW
  },
  ta: {
    app_name: 'டீல்ப்ரோ',
    login_header: 'ஸ்மார்ட் தேடல்',
    login_sub: 'உங்களுக்கு அருகிலுள்ள பிரத்யேக சலுகைகள் மற்றும் தள்ளுபடிகளைத் திறக்கவும்.',
    login_placeholder_id: 'பயனர் பெயர் / மின்னஞ்சல்',
    login_placeholder_pass: 'கடவுச்சொல்',
    login_btn: 'உள்நுழைக',
    login_forgot: 'சான்றுகளை மறந்துவிட்டீர்களா?',
    login_register_hint: 'புதியவரா?',
    login_register_action: 'கணக்கை உருவாக்கவும்',
    home_deals: 'சலுகைகள்',
    home_near_you: 'உங்களுக்கு அருகில்',
    home_daily_waves: 'தினசரி அலைகள்',
    home_see_all: 'அனைத்து சலுகைகளையும் இங்கே பார்க்கவும்',
    home_adjust_range: 'தூரத்தை மாற்றவும்',
    lang_select_title: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    lang_select_sub: 'சிறந்த அனுபவத்திற்கு உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    reg_title: 'கிரிட்டில் இணையுங்கள்',
    reg_consumer: 'நுகர்வோர்',
    reg_merchant: 'வணிகர்',
    reg_choose_account: 'தொடங்க உங்கள் கணக்கு வகையைத் தேர்ந்தெடுக்கவும்',
    reg_consumer_desc: 'உள்ளூர் சலுகைகளைக் கண்டறிந்து பணத்தை சேமிக்க நெட்வொர்க்கில் சேரவும்',
    reg_merchant_desc: 'DealPro டிஜிட்டல் அலைகளால் உங்கள் வணிகத்தை வலுப்படுத்துங்கள்',
    reg_have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
    reg_back_login: 'உள்நுழைவுக்குத் திரும்பு',
    reg_fullname: 'முழு பெயர்',
    reg_username: 'யூனர் பெயர்',
    reg_email: 'மின்னஞ்சல் முகவரி',
    reg_password: 'கடவுச்சொல்',
    reg_is_owner: 'நீங்கள் கடை உரிமையாளரா?',
    reg_brand: 'முக்கிய கடை பெயர் - GST பதிவுசெய்யப்பட்டது',
    reg_category: 'வணிக வகை',
    reg_locations: 'கடை இருப்பிடங்கள்',
    reg_store_name_label: 'கடை பெயர் (எ.கா. மெயின் ஸ்ட்ரீட் கிளை)', // NEW
    reg_street: 'தெரு முகவரி',
    reg_state: 'மாநிலம்',
    reg_city: 'நகரம்',
    reg_hours: 'இயங்கும் நேரம்',
    reg_24h: '24 மணிநேரம்',
    reg_opens: 'திறக்கும் நேரம்',
    reg_closes: 'மூடும் நேரம்',
    reg_landmark: 'அடையாளம் (விருப்பம்)',
    reg_use_my_loc: 'எனது இருப்பிடத்தைப் பயன்படுத்தவும்',
    reg_sync_verified: 'ஒத்திசைவு சரிபார்க்கப்பட்டது',
    reg_add_outlet: 'மற்றொரு கடையைச் சேர்க்கவும்',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN கார்டு',
    reg_submit: 'கணக்கை உருவாக்கு',
    reg_verify: 'சரிபார்',
    loc_title: 'தேடல் அளவுருக்கள்',
    loc_sub: 'கிரிட் ஸ்கேனிங் லாஜிக்',
    loc_radius: 'தேடல் ஆரம்',
    loc_gps: 'ஜிபிஎஸ் டிராக்கிங்',
    loc_manual: 'மேனுவல் கிரிட்',
    loc_region: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    loc_city: 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
    loc_area: 'இடத்தைத் தேர்ந்தெடுக்கவும்',
    loc_scan_btn: 'ஸ்கேன் பகுதி',
    loc_syncing: 'ஒத்திசைக்கப்படுகிறது...',
    loc_resolving: 'அமைவிடத்தைக் கண்டறிகிறது',
    loc_locked: 'சிக்னல் லாக் செய்யப்பட்டது',
    loc_awaiting: 'இருப்பிடத்திற்காக காத்திருக்கிறது',
    onboarding_1_headline: "உள்ளூர் தேடல்",
    onboarding_1_sub: "துல்லியமான ஜிபிஎஸ் லாஜிக் மூலம் உங்களுக்கு அருகிலுள்ள பிரத்யேக சலுகைகளைக் கண்டறியவும்.",
    onboarding_1_tag: "அருகாமை நுண்ணறிவு",
    onboarding_2_headline: "ஃபிளாஷ் விற்பனை",
    onboarding_2_sub: "வணிகர் சலுகைகளுடன் ஒத்திசைந்து காலாவதியாகும் முன் பலன்களைப் பெறுங்கள்.",
    onboarding_2_tag: "நேர திறன்",
    onboarding_3_headline: "நம்பகத்தன்மை",
    onboarding_3_sub: "சரிபார்க்கப்பட்ட முனையங்கள் மற்றும் பாதுகாப்பான வவுச்சர் நெறிமுறைகள் பிரீமியம் அனுபவத்தை உறுதி செய்கின்றன.",
    onboarding_3_tag: "கிரிட் பாதுகாப்பு",
    home_daily: 'இன்றைய சலுகை',
    home_local_area: 'உள்ளூர் பகுதி',
    home_your_sector: 'உங்கள் துறை',
    home_deal_singular: 'சலுகை',
    home_deals_plural: 'சலுகைகள்',
    home_in: 'இல்',
    home_no_deals_sector: 'இந்தத் துறையில் செயலில் உள்ள சலுகைகள் இல்லை.',
    home_view_all: 'அனைத்தையும் பார்',
    home_syncing_grid: 'கிரிட் ஒத்திசைக்கப்படுகிறது',
    details_redeem_btn: 'இப்போதே பெறுங்கள்',
    details_verifying: 'சரிபார்க்கப்படுகிறது...',
    details_activating_for: 'வெகுமதி செயல்படுத்தப்படுகிறது:',
    details_protocol: 'பிரச்சார நெறிமுறை',
    details_visit_intel: 'வருகை நுண்ணறிவு',
    details_start_gps: 'ஜிபிஎஸ் தொடங்கவும்',
    details_coordinates: 'கடை அமைவிடம்',
    details_landmark: 'அருகிலுள்ள அடையாளம்',
    details_op_window: 'இயங்கும் நேரம்',
    details_verified_node: 'சரிபார்க்கப்பட்ட டீல்ப்ரோ முனையம்',
    details_instance_id: 'ஐடி எண்',
    details_id_verified: 'அடையாளம் சரிபார்க்கப்பட்டது',
    details_present_counter: 'கவுண்டரில் காண்பிக்கவும்',
    details_exit_btn: 'வெளியேறு',
    history_title_1: 'மீட்பு',
    history_title_2: 'வரலாறு',
    history_sub: 'உங்கள் மீட்புகள்',
    history_active_nodes: 'முடிவுகள்',
    history_rewards_label: 'வெகுமதிகள்',
    history_tab_all: 'அனைத்து வெகுமதிகளும்',
    history_tab_pending: 'வருகைக்காக காத்திருக்கிறது',
    history_syncing: 'தகவல் ஒத்திசைக்கப்படுகிறது...',
    history_empty_title: 'வால்ட் ஒத்திசைக்கப்பட்டது',
    history_empty_sub_pending: 'அனைத்து சலுகைகளும் சரிபார்க்கப்பட்டன. நிலுவையில் உள்ள வருகைகள் இல்லை.',
    history_empty_sub_all: 'உங்கள் கணக்கில் மீட்பு பதிவுகள் எதுவும் இல்லை.',
    history_search_btn: 'கிரிட்டைத் தேடுங்கள்',
    history_status_verified: 'வருகை சரிபார்க்கப்பட்டது',
    history_status_awaiting: 'வருகைக்காக காத்திருக்கிறது',
    history_page_label: 'பக்கம்',
    history_of: 'இல்',
    history_ledger_end: 'பதிவு முடிவு',
    history_voucher_security: 'வவுச்சர் பாதுகாப்பு',
    history_transaction_logged: 'பரிவர்த்தனை பதிவு செய்யப்பட்டது',
    history_present_counter: 'கவுண்டரில் காண்பிக்கவும்',
    history_ref_label: 'REF',
    history_voucher_node: 'வவுச்சர் முனையம்',
    history_rate_exp: 'அனுபவத்தை மதிப்பிடுங்கள்',
    status_live: 'நேரலை',
    status_expired: 'காலாவதியானது',
    favorites_title_1: 'உங்கள்',
    favorites_title_2: 'விருப்பங்கள்',
    favorites_sub: 'சேமித்த சலுகைகளை எப்போது வேண்டுமானாலும் அணுகவும்',
    favorites_syncing: 'தரவு ஒத்திசைக்கப்படுகிறது',
    favorites_empty_title: 'விருப்பங்கள் காலியாக உள்ளன',
    favorites_empty_sub: 'இதய ஐகானைத் தட்டுவதன் மூலம் சலுகைகளைச் சேமிக்கவும்.',
    profile_elite_member: 'எலைட் உறுப்பினர்',
    profile_verif_hub: 'சரிபார்ப்பு மையம்',
    profile_verif_sub: 'வருகைகளைச் சரிபார்க்கவும்',
    profile_edit: 'சுயவிவரத்தைத் திருத்து',
    profile_edit_store: 'கடை சுயவிவரத்தைத் திருத்து',
    profile_favs: 'எனது விருப்பங்கள்',
    profile_invite_friend: 'நண்பரை அழை',
    profile_invite_partner: 'கூட்டாளரை அழை',
    profile_invite_placeholder: 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    profile_invite_success: 'அழைப்பு நண்பருக்கு அனுப்பப்பட்டது',
    profile_help: 'உதவி மற்றும் கருத்து',
    profile_support_hub: 'ஆதரவு மையம்',
    profile_console: 'ஸ்டோர் கன்சோல்',
    profile_payments: 'பணம் செலுத்துதல்',
    profile_subscriptions: 'எனது சந்தாக்கள்',
    profile_bank_verification: 'வங்கி சரிபார்ப்பு', // NEW translation key
    profile_verified_merchant: 'சரிபார்க்கப்பட்ட வணிகர்',
    store_search_title: 'கடை', // NEW
    store_search_sub: 'தேடல்', // NEW
    store_search_hint: 'குறிப்பிட்ட சில்லறை முனையங்களைக் கண்டறியவும்', // NEW
    store_search_placeholder: 'கடை பெயர் அல்லது முகவரியைத் தேடுங்கள்', // NEW
    store_search_no_results: 'கடைகள் எதுவும் கண்டறியப்படவில்லை.', // NEW
    store_search_adjust_query: 'உங்கள் தேடல் வினவலை சரிசெய்ய முயற்சிக்கவும்.', // NEW
  },
  te: {
    app_name: 'డీల్‌ప్రో',
    login_header: 'స్మార్ట్ సెర్చ్',
    login_sub: 'మీకు సమీపంలోని ప్రత్యేక డీల్స్ మరియు డిస్కౌంట్‌లను పొందండి.',
    login_placeholder_id: 'యూజర్ పేరు / ఈమెయిల్',
    login_placeholder_pass: 'పాస్‌వర్డ్',
    login_btn: 'సైన్ ఇన్',
    login_forgot: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    login_register_hint: 'కొత్తవారా?',
    login_register_action: 'ఖాతా సృష్టించండి',
    home_deals: 'డీల్స్',
    home_near_you: 'మీకు దగ్గరలో',
    home_daily_waves: 'రోజువారీ ఆఫర్లు',
    home_see_all: 'అన్ని డీల్స్ ఇక్కడ చూడండి',
    home_adjust_range: 'దూరం మార్చండి',
    lang_select_title: 'భాషను ఎంచుకోండి',
    lang_select_sub: 'మంచి అనుభవం కోసం మీ భాషను ఎంచుకోండి',
    reg_title: 'గ్రిడ్‌లో చేరండి',
    reg_consumer: 'వినియోగదారుడు',
    reg_merchant: 'వ్యాపారి',
    reg_choose_account: 'ప్రారంభించడానికి మీ ఖాతా రకాన్ని ఎంచుకోండి',
    reg_consumer_desc: 'స్థానిక డీల్స్ కనుగొని డబ్బు ఆదా చేయడానికి నెట్వర్క్‌లో చేరండి',
    reg_merchant_desc: 'DealPro డిజిటల్ తరంగాలతో మీ వ్యాపారాన్ని శక్తివంతం చేయండి',
    reg_have_account: 'ఇప్పటికే ఖాతా ఉందా?',
    reg_back_login: 'లాగిన్‌కు తిరిగి వెళ్లండి',
    reg_fullname: 'పూర్తి పేరు',
    reg_username: 'యూజర్ పేరు',
    reg_email: 'ఈమెయిల్ చిరునామా',
    reg_password: 'పాస్‌వర్డ్',
    reg_is_owner: 'మీరు స్టోర్ యజమానినా?',
    reg_brand: 'ప్రధాన స్టోర్ పేరు - GST నమోదు చేయబడింది',
    reg_category: 'వ్యాపార వర్గం',
    reg_locations: 'స్టోర్ స్థానాలు',
    reg_store_name_label: 'స్టోర్ పేరు (ఉదా. మెయిన్ స్ట్రీట్ బ్రాంచ్)', // NEW
    reg_street: 'వీధి చిరునామా',
    reg_state: 'రాష్ట్రం',
    reg_city: 'నగరం',
    reg_hours: 'పని వేళలు',
    reg_24h: '24 గంటలు',
    reg_opens: 'తెరుచు సమయం',
    reg_closes: 'మూయు సమయం',
    reg_landmark: 'ల్యాండ్‌మార్క్ (అవసరం లేదు)',
    reg_use_my_loc: 'నా ప్రస్తుత స్థానాన్ని వాడు',
    reg_sync_verified: 'సింక్ వెరిఫై చేయబడింది',
    reg_add_outlet: 'మరో అవుట్‌లెట్ జోడించు',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN కార్డ్',
    reg_submit: 'ఖాతాను సృష్టించు',
    reg_verify: 'వెరిఫై',
    loc_title: 'సెర్చ్ పారామితులు',
    loc_sub: 'గ్రిడ్ స్కానింగ్ లాజిక్',
    loc_radius: 'సెర్చ్ పరిధి',
    loc_gps: 'GPS ట్రాకింగ్',
    loc_manual: 'మాన్యువల్ గ్రిడ్',
    loc_region: 'రాష్ట్రాన్ని ఎంచుకోండి',
    loc_city: 'నగరాన్ని ఎంచుకోండి',
    loc_area: 'ప్రాంతాన్ని ఎంచుకోండి',
    loc_scan_btn: 'స్కాన్ ఏరియా',
    loc_syncing: 'సింక్ అవుతోంది...',
    loc_resolving: 'స్థానాన్ని గుర్తిస్తోంది',
    loc_locked: 'సిగ్నల్ లాక్ చేయబడింది',
    loc_awaiting: 'స్థానం కోసం నిరీక్షణ',
    onboarding_1_headline: "స్థానిక అన్వేషణ",
    onboarding_1_sub: "ఖచ్చితమైన GPS లాజిక్‌తో మీ సమీపంలోని ప్రత్యేక ఆఫర్లను కనుగొనండి.",
    onboarding_1_tag: "సామీప్య మేధస్సు",
    onboarding_2_headline: "ఫ్లాష్ సేల్స్",
    onboarding_2_sub: "వ్యాపారి ఆఫర్లతో సింక్ అయ్యి అవి ముగిసేలోపే ప్రయోజనాలను పొందండి.",
    onboarding_2_tag: "సమయ సామర్థ్యం",
    onboarding_3_headline: "సంస్థాగత నమ్మకం",
    onboarding_3_sub: "ధృవీకరించబడిన నోడ్స్ మరియు సురక్షిత వోచర్ ప్రోటోకాల్స్ ప్రీమియం అనుభవాన్ని అందిస్తాయి.",
    onboarding_3_tag: "గ్రిడ్ భద్రత",
    home_daily: 'నేటి డీల్',
    home_local_area: 'స్థానిక ప్రాంతం',
    home_your_sector: 'మీ సెక్టార్',
    home_deal_singular: 'డీల్',
    home_deals_plural: 'డీల్స్',
    home_in: 'లో',
    home_no_deals_sector: 'ఈ సెక్టార్‌లో యాక్టివ్ ఆఫర్లు లేవు.',
    home_view_all: 'అన్నీ చూడండి',
    home_syncing_grid: 'గ్రిడ్ సింక్ అవుతోంది',
    details_redeem_btn: 'ఇప్పుడే పొందండి',
    details_verifying: 'వెరిఫై అవుతోంది...',
    details_activating_for: 'రివార్డ్ యాక్టివేట్ అవుతోంది:',
    details_protocol: 'క్యాంపెయిన్ ప్రోటోకాల్',
    details_visit_intel: 'విజిట్ ఇంటెలిజెన్స్',
    details_start_gps: 'GPS ప్రారంభించు',
    details_coordinates: 'స్టోర్ అడ్రస్',
    details_landmark: 'సమీప ల్యాండ్‌మార్క్',
    details_op_window: 'పని వేళలు',
    details_verified_node: 'ధృవీకరించబడిన డీల్‌ప్రో నోడ్',
    details_instance_id: 'ఐడీ నంబర్',
    details_id_verified: 'గుర్తింపు ధృవీకరించబడింది',
    details_present_counter: 'కౌంటర్ వద్ద చూపండి',
    details_exit_btn: 'నిష్క్రమించు',
    history_title_1: 'రిడెంప్షన్',
    history_title_2: 'చరిత్ర',
    history_sub: 'మీ రిడెంప్షన్లు',
    history_active_nodes: 'ఫలితాలు',
    history_rewards_label: 'రివార్డులు',
    history_tab_all: 'అన్ని రివార్డులు',
    history_tab_pending: 'సందర్శన కోసం నిరీక్షణ',
    history_syncing: 'సమాచారం సింక్ అవుతోంది...',
    history_empty_title: 'వాల్ట్ సింక్ చేయబడింది',
    history_empty_sub_pending: 'అన్ని డీల్స్ వెరిఫై చేయబడ్డాయి. పెండింగ్ సందర్శనలు లేవు.',
    history_empty_sub_all: 'మీ ఖాతాలో రిడెంప్షన్ రికార్డులు లేవు.',
    history_search_btn: 'గ్రిడ్‌ను అన్వేషించండి',
    history_status_verified: 'సందర్శన ధృవీకరించబడింది',
    history_status_awaiting: 'సందర్శన కోసం నిరీక్షణ',
    history_page_label: 'పేజీ',
    history_of: 'లో',
    history_ledger_end: 'రికార్డు ముగింపు',
    history_voucher_security: 'వోచర్ భద్రత',
    history_transaction_logged: 'లావాదేవీ రికార్డు చేయబడింది',
    history_present_counter: 'కౌంటర్ వద్ద చూపండి',
    history_ref_label: 'REF',
    history_voucher_node: 'వోచర్ నోడ్',
    history_rate_exp: 'అనుభవాన్ని రేట్ చేయండి',
    status_live: 'లైవ్',
    status_expired: 'గడువు ముగిసింది',
    favorites_title_1: 'మీ',
    favorites_title_2: 'ఇష్టమైనవి',
    favorites_sub: 'సేవ్ చేసిన డీల్స్ ఎప్పుడైనా చూడండి',
    favorites_syncing: 'డేటా సింక్ అవుతోంది',
    favorites_empty_title: 'ఇష్టమైనవి ఏమీ లేవు',
    favorites_empty_sub: 'హార్ట్ ఐకాన్ నొక్కడం ద్వారా డీల్స్ సేవ్ చేయండి.',
    profile_elite_member: 'ఎలైట్ సభ్యుడు',
    profile_verif_hub: 'ధృవీకరణ హబ్',
    profile_verif_sub: 'స్టోర్ విజిట్స్ వెరిఫై చేయండి',
    profile_edit: 'ప్రొఫైల్ ఎడిట్ చేయండి',
    profile_edit_store: 'స్టోర్ ప్రొఫైల్ ఎడిట్ చేయండి',
    profile_favs: 'నా ఇష్టమైనవి',
    profile_invite_friend: 'స్నేహితుడిని ఆహ్వానించండి',
    profile_invite_partner: 'భాగస్వామిని ఆహ్వానించండి',
    profile_invite_placeholder: 'ఈమెయిల్ లేదా ఫోన్ నంబర్',
    profile_invite_success: 'ఆహ్వానం పంపబడింది',
    profile_help: 'సహాయం మరియు ఫీడ్‌బ్యాక్',
    profile_support_hub: 'సపోర్ట్ హబ్',
    profile_console: 'స్టోర్ కన్సోల్',
    profile_payments: 'చెల్లింపులు',
    profile_subscriptions: 'నా సబ్‌స్క్రిప్షన్లు',
    profile_bank_verification: 'బ్యాంక్ ధృవీకరణ', // NEW translation key
    profile_verified_merchant: 'ధృవీకరించబడిన వ్యాపారి',
    store_search_title: 'స్టోర్', // NEW
    store_search_sub: 'అన్వేషణ', // NEW
    store_search_hint: 'నిర్దిష్ట రిటైల్ నోడ్స్‌ను గుర్తించండి', // NEW
    store_search_placeholder: 'స్టోర్ పేరు లేదా చిరునామాను శోధించండి', // NEW
    store_search_no_results: 'స్టోర్‌లు ఏమీ కనుగొనబడలేదు.', // NEW
    store_search_adjust_query: 'మీ శోధన క్వెరీని సర్దుబాటు చేయడానికి ప్రయత్నించండి.', // NEW
  },
  ml: {
    app_name: 'ഡീൽപ്രോ',
    login_header: 'സ്മാർട്ട് സെർച്ച്',
    login_sub: 'നിങ്ങൾക്ക് അടുത്തുള്ള സവിശേഷമായ ഡീലുകളും ഡിസ്കൗണ്ടുകളും നേടൂ.',
    login_placeholder_id: 'യൂസർ നെയിം / ഇമെയിൽ',
    login_placeholder_pass: 'പാസ്‌വേഡ്',
    login_btn: 'സൈൻ ഇൻ',
    login_forgot: 'രഹസ്യവാക്ക് മറന്നോ?',
    login_register_hint: 'പുതിയ ആളാണോ?',
    login_register_action: 'അക്കൗണ്ട് തുടങ്ങാം',
    home_deals: 'ഡീലുകൾ',
    home_near_you: 'നിങ്ങൾക്ക് അടുത്ത്',
    home_daily_waves: 'പ്രതിദിന ഓഫറുകൾ',
    home_see_all: 'എല്ലാ ഡീലുകളും ഇവിടെ കാണാം',
    home_adjust_range: 'ദൂരം ക്രമീകരിക്കുക',
    lang_select_title: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    lang_select_sub: 'മികച്ച അനുഭവത്തിനായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    reg_title: 'ഗ്രിഡിൽ ചേരൂ',
    reg_consumer: 'ഉപഭോക്താവ്',
    reg_merchant: 'വ്യാപാരി',
    reg_choose_account: 'ആരംഭിക്കാൻ നിങ്ങളുടെ അക്കൗണ്ട് തരം തിരഞ്ഞെടുക്കുക',
    reg_consumer_desc: 'പ്രാദേശിക ഡീലുകൾ കണ്ടെത്താനും പണം ലാഭിക്കാനും നെറ്റ്‌വർക്കിൽ ചേരൂ',
    reg_merchant_desc: 'DealPro ഡിജിറ്റൽ തരംഗങ്ങളിലൂടെ നിങ്ങളുടെ ബിസിനസ് ശക്തിപ്പെടുത്തുക',
    reg_have_account: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    reg_back_login: 'ലോഗിനിലേക്ക് മടങ്ങുക',
    reg_fullname: 'മുഴുവൻ പേര്',
    reg_username: 'യൂസർ നെയിം',
    reg_email: 'ഇമെയിൽ വിലാസം',
    reg_password: 'പാസ്‌വേഡ്',
    reg_is_owner: 'നിങ്ങൾ കടയുടെ ഉടമയാണോ?',
    reg_brand: 'പ്രധാന കടയുടെ പേര് - GST രജിസ്റ്റർ ചെയ്തത്',
    reg_category: 'ബിസിനസ് വിഭാഗം',
    reg_locations: 'കടയുടെ ലൊക്കേഷനുകൾ',
    reg_store_name_label: 'കടയുടെ പേര് (ഉദാ. മെയിൻ സ്ട്രീറ്റ് ബ്രാഞ്ച്)', // NEW
    reg_street: 'മേൽവിലാസം',
    reg_state: 'സംസ്ഥാനം',
    reg_city: 'നഗരം',
    reg_hours: 'പ്രവൃത്തി സമയം',
    reg_24h: '24 മണിക്കൂർ',
    reg_opens: 'തുറക്കുന്ന സമയം',
    reg_closes: 'അടയ്ക്കുന്ന സമയം',
    reg_landmark: 'അടയാളം (നിർബന്ധമില്ല)',
    reg_use_my_loc: 'എന്റെ ലൊക്കേഷൻ ഉപയോഗിക്കൂ',
    reg_sync_verified: 'സിങ്ക് സ്ഥിരീകരിച്ചു',
    reg_add_outlet: 'മറ്റൊരു കട ചേർക്കുക',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN കാർഡ്',
    reg_submit: 'അക്കൗണ്ട് ക്രിയേറ്റ് ചെയ്യൂ',
    reg_verify: 'വെരിഫൈ ചെയ്യൂ',
    loc_title: 'സെർച്ച് പാരാമീറ്ററുകൾ',
    loc_sub: 'ഗ്രിഡ് സ്കാനിംഗ് ലോജിക്',
    loc_radius: 'സെർച്ച് പരിധി',
    loc_gps: 'GPS ട്രാക്കിംഗ്',
    loc_manual: 'മാനുവൽ ഗ്രിഡ്',
    loc_region: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    loc_city: 'നഗരം തിരഞ്ഞെടുക്കുക',
    loc_area: 'സ്ഥലം തിരഞ്ഞെടുക്കുക',
    loc_scan_btn: 'സ്കാൻ ഏരിയ',
    loc_syncing: 'സിങ്ക് ചെയ്യുന്നു...',
    loc_resolving: 'സ്ഥലം കണ്ടെത്തുന്നു',
    loc_locked: 'സിഗ്നൽ ലോക്ക് ചെയ്തു',
    loc_awaiting: 'ലൊക്കേഷനായി കാത്തിരിക്കുന്നു',
    onboarding_1_headline: "പ്രാദേശിക തിരച്ചിൽ",
    onboarding_1_sub: "കൃത്യമായ GPS ലോജിക് ഉപയോഗിച്ച് അടുത്തുള്ള മികച്ച ഓഫറുകൾ കണ്ടെത്തൂ.",
    onboarding_1_tag: "ലൊക്കേഷൻ ഇന്റലിജൻസ്",
    onboarding_2_headline: "ഫ്ലാഷ് സെയിൽസ്",
    onboarding_2_sub: "വ്യാപാരികളുടെ ഓഫറുകൾ അവസാനിക്കുന്നതിന് മുൻപ് തന്നെ നേടിയെടുക്കൂ.",
    onboarding_2_tag: "സമയ ലാഭം",
    onboarding_3_headline: "വിശ്വാസ്യത",
    onboarding_3_sub: "സ്ഥിരീകരിക്കപ്പെട്ട നോഡുകളും സുരക്ഷിത വൗച്ചർ പ്രോട്ടോക്കോളുകളും മികച്ച അനുഭവം നൽകുന്നു.",
    onboarding_3_tag: "ഗ്രിഡ് സെക്യൂരിറ്റി",
    home_daily: 'ഇന്നത്തെ ഡീൽ',
    home_local_area: 'പ്രാദേശിക മേഖല',
    home_your_sector: 'നിങ്ങളുടെ സെക്ടർ',
    home_deal_singular: 'ഡീൽ',
    home_deals_plural: 'ഡീലുകൾ',
    home_in: 'ൽ',
    home_no_deals_sector: 'ഈ സെക്ടറിൽ ഓഫറുകൾ ലഭ്യമല്ല.',
    home_view_all: 'എല്ലാം കാണുക',
    home_syncing_grid: 'ഗ്രിഡ് സിങ്ക് ചെയ്യുന്നു',
    details_redeem_btn: 'ഇപ്പോൾ നേടൂ',
    details_verifying: 'സ്ഥിരീകരിക്കുന്നു...',
    details_activating_for: 'ഓഫർ സജീവമാക്കുന്നു:',
    details_protocol: 'ക്യാമ്പയിൻ പ്രോട്ടോക്കോൾ',
    details_visit_intel: 'സന്ദർശന വിവരം',
    details_start_gps: 'GPS തുടങ്ങൂ',
    details_coordinates: 'കടയുടെ വിലാസം',
    details_landmark: 'അടുത്തുള്ള അടയാളം',
    details_op_window: 'പ്രവൃത്തി സമയം',
    details_verified_node: 'സ്ഥിരീകരിക്കപ്പെട്ട ഡീൽപ്രോ നോഡ്',
    details_instance_id: 'ഐഡി നമ്പർ',
    details_id_verified: 'തിരിച്ചറിയൽ രേഖ സ്ഥിരീകരിച്ചു',
    details_present_counter: 'കൗണ്ടറിൽ കാണിക്കുക',
    details_exit_btn: 'പുറത്തുകടക്കുക',
    history_title_1: 'റിഡംപ്ഷൻ',
    history_title_2: 'ചരിത്രം',
    history_sub: 'നിങ്ങളുടെ ഓഫറുകൾ',
    history_active_nodes: 'ഫലങ്ങൾ',
    history_rewards_label: 'റിവാർഡുകൾ',
    history_tab_all: 'എല്ലാ റിവാർഡുകളും',
    history_tab_pending: 'സന്ദർശനത്തിനായി കാക്കുന്നു',
    history_syncing: 'വിവരങ്ങൾ സിങ്ക് ചെയ്യുന്നു...',
    history_empty_title: 'വാൽട്ട് സിങ്ക് ചെയ്തു',
    history_empty_sub_pending: 'എല്ലാ ഡീലുകളും സ്ഥിരീകരിച്ചു. സന്ദർശനങ്ങൾ ബാക്കിയില്ല.',
    history_empty_sub_all: 'നിങ്ങളുടെ അക്കൗണ്ടിൽ റിഡംപ്ഷൻ വിവരങ്ങൾ ലഭ്യമല്ല.',
    history_search_btn: 'ഗ്രിഡ് തിരയുക',
    history_status_verified: 'സന്ദർശനം സ്ഥിരീകരിച്ചു',
    history_status_awaiting: 'സന്ദർശനത്തിനായി കാക്കുന്നു',
    history_page_label: 'പേജ്',
    history_of: 'ൽ',
    history_ledger_end: 'റെക്കോർഡ് അവസാനിച്ചു',
    history_voucher_security: 'വൗച്ചർ സുരക്ഷ',
    history_transaction_logged: 'ഇടപാട് രേഖപ്പെടുത്തി',
    history_present_counter: 'കൗണ്ടറിൽ കാണിക്കുക',
    history_ref_label: 'REF',
    history_voucher_node: 'വൗച്ചർ നോഡ്',
    history_rate_exp: 'അനുഭവം വിലയിരുത്തുക',
    status_live: 'ലൈവ്',
    status_expired: 'കാലഹരണപ്പെട്ടു',
    favorites_title_1: 'നിങ്ങളുടെ',
    favorites_title_2: 'ഇഷ്ടങ്ങൾ',
    favorites_sub: 'സേവ് ചെയ്ത ഡീലുകൾ എപ്പോൾ വേണമെങ്കിലും കാണാം',
    favorites_syncing: 'ഡാറ്റ സിങ്ക് ചെയ്യുന്നു',
    favorites_empty_title: 'ലിസ്റ്റ് കാലിയാണ്',
    favorites_empty_sub: 'ഹാർട്ട് ഐക്കൺ ക്ലിക്ക് ചെയ്ത് ഡീലുകൾ സേവ് ചെയ്യൂ.',
    profile_elite_member: 'എലൈറ്റ് മെമ്പർ',
    profile_verif_hub: 'വെരിഫിക്കേഷൻ ഹബ്',
    profile_verif_sub: 'സന്ദർശനങ്ങൾ സ്ഥിരീകരിക്കുക',
    profile_edit: 'പ്രൊഫൈൽ തിരുത്തുക',
    profile_edit_store: 'കടയുടെ പ്രൊഫൈൽ തിരുത്തുക',
    profile_favs: 'എനിക്ക് ഇഷ്ടപ്പെട്ടവ',
    profile_invite_friend: 'സുഹൃത്തിനെ ക്ഷണിക്കുക',
    profile_invite_partner: 'പങ്കാളിയെ ക്ഷണിക്കുക',
    profile_invite_placeholder: 'ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ നമ്പർ',
    profile_invite_success: 'ക്ഷണം സുഹൃത്തിന് അയച്ചു',
    profile_help: 'സഹായവും അഭിപ്രായങ്ങളും',
    profile_support_hub: 'സപ്പോർട്ട് ഹബ്',
    profile_console: 'സ്റ്റോർ കൺസോൾ',
    profile_payments: 'പേയ്‌മെന്റുകൾ',
    profile_subscriptions: 'സബ്‌സ്‌ക്രിപ്‌ഷനുകൾ',
    profile_bank_verification: 'ബാങ്ക് സ്ഥിരീകരണം', // NEW translation key
    profile_verified_merchant: 'സ്ഥിരീകരിക്കപ്പെട്ട വ്യാപാരി',
    store_search_title: 'സ്റ്റോർ', // NEW
    store_search_sub: 'അന്വേഷണം', // NEW
    store_search_hint: 'നിർദ്ദിഷ്ട റീട്ടെയിൽ നോഡുകൾ കണ്ടെത്തുക', // NEW
    store_search_placeholder: 'സ്റ്റോർ പേര് അല്ലെങ്കിൽ വിലാസം തിരയുക', // NEW
    store_search_no_results: 'സ്റ്റോറുകളൊന്നും കണ്ടെത്തിയില്ല.', // NEW
    store_search_adjust_query: 'നിങ്ങളുടെ തിരയൽ ക്വറി ക്രമീകരിക്കാൻ ശ്രമിക്കുക.', // NEW
  },
  bn: {
    app_name: 'ডিলপ্রো',
    login_header: 'স্মার্ট ডিসকভারি',
    login_sub: 'আপনার কাছের বিশেষ ডিল এবং ডিসকাউন্টগুলি আনলক করুন।',
    login_placeholder_id: 'ইউজারনেম / ইমেল',
    login_placeholder_pass: 'পাসওয়ার্ড',
    login_btn: 'সাইন ইন',
    login_forgot: 'পাসওয়ার্ড ভুলে গেছেন?',
    login_register_hint: 'গ্রিডে নতুন?',
    login_register_action: 'পরিচয় তৈরি করুন',
    home_deals: 'ডিলস',
    home_near_you: 'আপনার কাছে',
    home_daily_waves: 'প্রতিদিনের অফার',
    home_see_all: 'সব ডিল এখানে দেখুন',
    home_adjust_range: 'দূরত্ব পরিবর্তন করুন',
    lang_select_title: 'ভাষা নির্বাচন করুন',
    lang_select_sub: 'ভালো অভিজ্ঞতার জন্য আপনার ভাষা বেছে নিন',
    reg_title: 'গ্রিডে যোগ দিন',
    reg_consumer: 'গ্রাহক',
    reg_merchant: 'বিক্রেতা',
    reg_choose_account: 'শুরু করতে আপনার অ্যাকাউন্টের ধরন নির্বাচন করুন',
    reg_consumer_desc: 'স্থানীয় ডিল খুঁজে পেতে এবং অর্থ সাশ্রয় করতে নেটওয়ার্কে যোগ দিন',
    reg_merchant_desc: 'DealPro ডিজিটাল তরঙ্গ দিয়ে আপনার ব্যবসাকে ক্ষমতায়িত করুন',
    reg_have_account: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    reg_back_login: 'লগইনে ফিরে যান',
    reg_fullname: 'পুরো নাম',
    reg_username: 'ইউজারনেম',
    reg_email: 'ইমেল ঠিকানা',
    reg_password: 'পাসওয়ার্ড',
    reg_is_owner: 'আপনি কি দোকানের মালিক?',
    reg_brand: 'প্রধান দোকানের নাম - GST রেজিস্টার্ড',
    reg_category: 'ব্যবসার বিভাগ',
    reg_locations: 'দোকানের অবস্থান',
    reg_store_name_label: 'দোকানের নাম (যেমন: মেন স্ট্রিট শাখা)', // NEW
    reg_street: 'ঠিকানা',
    reg_state: 'রাজ্য',
    reg_city: 'শহর',
    reg_hours: 'কাজের সময়',
    reg_24h: '২৪ ঘন্টা',
    reg_opens: 'খোলার সময়',
    reg_closes: 'বন্ধের সময়',
    reg_landmark: 'ল্যান্ডমার্ক (ঐচ্ছিক)',
    reg_use_my_loc: 'আমার অবস্থান ব্যবহার করুন',
    reg_sync_verified: 'সিঙ্ক যাচাই করা হয়েছে',
    reg_add_outlet: 'অন্য আউটলেট যোগ করুন',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN কার্ড',
    reg_submit: 'অ্যাকাউন্ট তৈরি করুন',
    reg_verify: 'যাচাই করুন',
    loc_title: 'সার্চ প্যারামিটার',
    loc_sub: 'গ্রিড স্ক্যানিং লজিক',
    loc_radius: 'সার্চ রেডিয়াস',
    loc_gps: 'জিপিএস ট্র্যাকিং',
    loc_manual: 'ম্যানুয়াল গ্রিড',
    loc_region: 'রাজ্য নির্বাচন করুন',
    loc_city: 'শহর নির্বাচন করুন',
    loc_area: 'এলাকা নির্বাচন করুন',
    loc_scan_btn: 'এলাকা স্ক্যান করুন',
    loc_syncing: 'সিঙ্ক হচ্ছে...',
    loc_resolving: 'অবস্থান খুঁজছে',
    loc_locked: 'সিগন্যাল লক করা হয়েছে',
    loc_awaiting: 'অবস্থানের অপেক্ষা',
    onboarding_1_headline: "স্থানীয় ডিসকভারি",
    onboarding_1_sub: "সঠিক জিপিএস লজিকের মাধ্যমে আপনার কাছের বিশেষ ডিলগুলি খুঁজুন।",
    onboarding_1_tag: "প্রক্সিমিটি ইন্টেলিজেন্স",
    onboarding_2_headline: "ফ্ল্যাশ সেলস",
    onboarding_2_sub: "বিক্রেতাদের অফারের সাথে সিঙ্ক করুন এবং শেষ হওয়ার আগেই সুবিধা নিন।",
    onboarding_2_tag: "সময়ের সঠিক ব্যবহার",
    onboarding_3_headline: "নির্ভরযোগ্যতা",
    onboarding_3_sub: "যাচাইকৃত নোড এবং নিরাপদ ভাউচার প্রোটোকল আপনাকে সেরা অভিজ্ঞতা দেবে।",
    onboarding_3_tag: "গ্রিড সিকিউরিটি",
    home_daily: 'আজকের ডিল',
    home_local_area: 'স্থানীয় এলাকা',
    home_your_sector: 'আপনার সেক্টর',
    home_deal_singular: 'ডিল',
    home_deals_plural: 'ডিলস',
    home_in: 'এ',
    home_no_deals_sector: 'এই সেক্টরে কোনো সক্রিয় অফার নেই।',
    home_view_all: 'সব দেখুন',
    home_syncing_grid: 'গ্রিড সিঙ্ক হচ্ছে',
    details_redeem_btn: 'এখনই নিন',
    details_verifying: 'যাচাই করা হচ্ছে...',
    details_activating_for: 'রিওয়ার্ড সক্রিয় হচ্ছে:',
    details_protocol: 'ক্যাম্পেইন প্রোটোকল',
    details_visit_intel: 'ভিজিট ইন্টেলিজেন্স',
    details_start_gps: 'জিপিএস শুরু করুন',
    details_coordinates: 'দোকানের ঠিকানা',
    details_landmark: 'কাছের ল্যান্ডমার্ক',
    details_op_window: 'কাজের সময়',
    details_verified_node: 'যাচাইকৃত ডিলপ্রো নোড',
    details_instance_id: 'আইডি নম্বর',
    details_id_verified: 'পরিচয় যাচাই করা হয়েছে',
    details_present_counter: 'কাউন্টারে দেখান',
    details_exit_btn: 'প্রস্থান করুন',
    history_title_1: 'রিডেম্পশন',
    history_title_2: 'ইতিহাস',
    history_sub: 'আপনার রিডেম্পশনগুলি',
    history_active_nodes: 'ফলাফল',
    history_rewards_label: 'রিওয়ার্ডস',
    history_tab_all: 'সব রিওয়ার্ড',
    history_tab_pending: 'পরিদর্শনের অপেক্ষা',
    history_syncing: 'তথ্য সিঙ্ক হচ্ছে...',
    history_empty_title: 'ভল্ট সিঙ্ক করা হয়েছে',
    history_empty_sub_pending: 'সব ডিল যাচাই করা হয়েছে। কোনো ভিজিট বাকি নেই।',
    history_empty_sub_all: 'আপনার অ্যাকাউন্টে কোনো রিডেম্পशन रिकॉर्ड নেই।',
    history_search_btn: 'গ্রিড এক্সপ্লোर করুন',
    history_status_verified: 'ভিজিট যাচাইকৃত',
    history_status_awaiting: 'পরিদর্শনের অপেক্ষা',
    history_page_label: 'পেজ',
    history_of: 'এর',
    history_ledger_end: 'রেকর্ড শেষ',
    history_voucher_security: 'ভাউচার সিকিউরিটি',
    history_transaction_logged: 'লেনদেন নথিভুক্ত',
    history_present_counter: 'কাউন্টারে দেখান',
    history_ref_label: 'REF',
    history_voucher_node: 'ভাউচার নোড',
    history_rate_exp: 'অভিজ্ঞতা রেট করুন',
    status_live: 'লাইভ',
    status_expired: 'মেয়াদ শেষ',
    favorites_title_1: 'আপনার',
    favorites_title_2: 'প্রিয়',
    favorites_sub: 'সেভ করা ডিলগুলি যেকোনো সময় দেখুন',
    favorites_syncing: 'ডেটা সিঙ্ক হচ্ছে',
    favorites_empty_title: 'লিস্ট খালি',
    favorites_empty_sub: 'হার্ট আইকনে ক্লিক করে ডিলগুলি সেভ করুন।',
    profile_elite_member: 'এলিট মেম্বার',
    profile_verif_hub: 'ভেরিফিকেশন হাব',
    profile_verif_sub: 'ভিজিট যাচাই করুন',
    profile_edit: 'প্রোফাইল পরিবর্তন',
    profile_edit_store: 'দোকানের প্রোফাইল পরিবর্তন',
    profile_favs: 'আমার প্রিয় ডিলস',
    profile_invite_friend: 'বন্ধুকে আমন্ত্রণ জানান',
    profile_invite_partner: 'পার্টনারকে আমন্ত্রণ জানান',
    profile_invite_placeholder: 'ইমেল বা ফোন নম্বর',
    profile_invite_success: 'আমন্ত্রণ পাঠানো হয়েছে',
    profile_help: 'সাহায্য ও মতামত',
    profile_support_hub: 'সাপোর্ট হাব',
    profile_console: 'স্টোর কনসোল',
    profile_payments: 'পেমেন্ট',
    profile_subscriptions: 'আমার সাবস্ক্রিপশন',
    profile_bank_verification: 'ব্যাংক যাচাইকরণ', // NEW translation key
    profile_verified_merchant: 'যাচাইকৃত বিক্রেতা',
    store_search_title: 'দোকান', // NEW
    store_search_sub: 'সন্ধান', // NEW
    store_search_hint: 'নির্দিষ্ট খুচরা নোড খুঁজুন', // NEW
    store_search_placeholder: 'দোকানের নাম বা ঠিকানা খুঁজুন', // NEW
    store_search_no_results: 'কোনো দোকান পাওয়া যায়নি।', // NEW
    store_search_adjust_query: 'আপনার অনুসন্ধান ক্যোয়ারী সামঞ্জস্য করার চেষ্টা করুন।', // NEW
  },
  mr: {
    app_name: 'डीलप्रो',
    login_header: 'स्मार्ट डिस्कव्हरी',
    login_sub: 'तुमच्या जवळचे विशेष डील्स आणि सवलती मिळवा.',
    login_placeholder_id: 'युजरनेम / ईमेल',
    login_placeholder_pass: 'पासवर्ड',
    login_btn: 'साइन इन',
    login_forgot: 'पासवर्ड विसरलात?',
    login_register_hint: 'ग्रिडवर नवीन आहात?',
    login_register_action: 'ओळख तयार करा',
    home_deals: 'डील्स',
    home_near_you: 'तुमच्या जवळ',
    home_daily_waves: 'दैनंदिन ऑफर्स',
    home_see_all: 'सर्व डील्स येथे पहा',
    home_adjust_range: 'क्षेत्र बदला',
    lang_select_title: 'भाषा निवडा',
    lang_select_sub: 'उत्तम अनुभवासाठी तुमची भाषा निवडा',
    reg_title: 'ग्रिडमध्ये सामील व्हा',
    reg_consumer: 'ग्राहक',
    reg_merchant: 'व्यापारी',
    reg_choose_account: 'सुरू करण्यासाठी तुमचा खाते प्रकार निवडा',
    reg_consumer_desc: 'स्थानिक डील्स शोधण्यासाठी आणि पैसे वाचवण्यासाठी नेटवर्कमध्ये सामील व्हा',
    reg_merchant_desc: 'DealPro डिजिटल लहरींसह तुमचा व्यवसाय सशक्त करा',
    reg_have_account: 'आधीपासूनच खाते आहे?',
    reg_back_login: 'लॉगिनवर परत या',
    reg_fullname: 'पूर्ण नाव',
    reg_username: 'युजरनेम',
    reg_email: 'ईमेल पत्ता',
    reg_password: 'पासवर्ड',
    reg_is_owner: 'तुम्ही दुकानाचे मालक आहात का?',
    reg_brand: 'मुख्य दुकानाचे नाव - GST नोंदणीकृत',
    reg_category: 'व्यवसाय श्रेणी',
    reg_locations: 'दुकानाचे ठिकाण',
    reg_store_name_label: 'दुकानाचे नाव (उदा. मेन स्ट्रीट ब्रांच)', // NEW
    reg_street: 'पत्ता',
    reg_state: 'राज्य',
    reg_city: 'शहर',
    reg_hours: 'कामकाजाची वेळ',
    reg_24h: '२४ तास',
    reg_opens: 'उघडण्याची वेळ',
    reg_closes: 'बंद होण्याची वेळ',
    reg_landmark: 'लँडमार्क (पर्यायी)',
    reg_use_my_loc: 'माझे लोकेशन वापरा',
    reg_sync_verified: 'सिंक यशस्वी',
    reg_add_outlet: 'दुसरे आउटलेट जोडा',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN कार्ड',
    reg_submit: 'खाते तयार करा',
    reg_verify: 'पडताळणी करा',
    loc_title: 'शोध निकष',
    loc_sub: 'ग्रिड स्कॅनिंग लॉजिक',
    loc_radius: 'शोध त्रिज्या',
    loc_gps: 'जीपीएस ट्रॅकिंग',
    loc_manual: 'मॅन्युअल ग्रिড',
    loc_region: 'राज्य निवडा',
    loc_city: 'शहर निवडा',
    loc_area: 'परिसर निवडा',
    loc_scan_btn: 'परिसर स्कॅन करा',
    loc_syncing: 'सिंक होत आहे...',
    loc_resolving: 'लोकेशन शोधत आहे',
    loc_locked: 'सिग्नल लॉक झाले',
    loc_awaiting: 'लोकेशनची प्रतीक्षा',
    onboarding_1_headline: "स्थानिक शोध",
    onboarding_1_sub: "अचूक जीपीएस लॉजिकसह तुमच्या जवळच्या विशेष ऑफर्स शोधा.",
    onboarding_1_tag: "प्रॉक्सिमिटी इंटेलिजन्स",
    onboarding_2_headline: "फ्लॅश सेल्स",
    onboarding_2_sub: "व्यापाऱ्यांच्या ऑफर्स संपण्यापूर्वीच त्यांचा लाभ घ्या.",
    onboarding_2_tag: "वेळेची बचत",
    onboarding_3_headline: "विश्वासार्हता",
    onboarding_3_sub: "व्हेरिफाईड नोड्स आणि सुरक्षित व्हाउचर प्रोटोकॉल तुम्हाला सर्वोत्तम अनुभव देतील.",
    onboarding_3_tag: "ग्रिड सुरक्षा",
    home_daily: 'आजचा सौदा',
    home_local_area: 'स्थानिक परिसर',
    home_your_sector: 'तुमचा सेक्टर',
    home_deal_singular: 'डील',
    home_deals_plural: 'डील्स',
    home_in: 'मध्ये',
    home_no_deals_sector: 'या सेक्टरमध्ये सध्या ऑफर्स नाहीत.',
    home_view_all: 'सर्व पहा',
    home_syncing_grid: 'ग्रिड सिंक होत आहे',
    details_redeem_btn: 'आत्ता मिळवा',
    details_verifying: 'पडताळणी होत आहे...',
    details_activating_for: 'रिवॉर्ड सक्रिय होत आहे:',
    details_protocol: 'कॅम्पेन प्रोटोकॉल',
    details_visit_intel: 'व्हिजिट इंटेलिजन्स',
    details_start_gps: 'जीपीएस सुरू करा',
    details_coordinates: 'दुकानाचे लोकेशन',
    details_landmark: 'जवळपासची खुण',
    details_op_window: 'कामकाजाची वेळ',
    details_verified_node: 'व्हेरिफाईड डीलप्रो नोड',
    details_instance_id: 'आयडी नंबर',
    details_id_verified: 'ओळख पटली आहे',
    details_present_counter: 'काउंटरवर दाखवा',
    details_exit_btn: 'बाहेर पडा',
    history_title_1: 'रिडेम्पशन',
    history_title_2: 'इतिहास',
    history_sub: 'तुमची रिदेम्पशन',
    history_active_nodes: 'निकाल',
    history_rewards_label: 'रिवॉर्ड्स',
    history_tab_all: 'सर्व रिवॉर्ड्स',
    history_tab_pending: 'भेटीची प्रतीक्षा',
    history_syncing: 'माहिती सिंक होत आहे...',
    history_empty_title: 'व्हॉल्ट सिंक झाले',
    history_empty_sub_pending: 'सर्व डील्स सत्यापित आहेत. कोणतीही भेट प्रलंबित नाही.',
    history_empty_sub_all: 'तुमच्या खात्यात रिदेम्पशन रेकॉर्ड नाहीत.',
    history_search_btn: 'ग्रिड एक्सप्लोर करा',
    history_status_verified: 'व्हिजिट व्हेरिफाईड',
    history_status_awaiting: 'भेटीची प्रतीक्षा',
    history_page_label: 'पेज',
    history_of: 'चे',
    history_ledger_end: 'रेकॉर्ड समाप्त',
    history_voucher_security: 'व्हाउचर सुरक्षा',
    history_transaction_logged: 'व्यवहार नोंदवला',
    history_present_counter: 'काउंटरवर दाखवा',
    history_ref_label: 'REF',
    history_voucher_node: 'व्हाउचर नोड',
    history_rate_exp: 'अनुभव रेट करा',
    status_live: 'लाईव्ह',
    status_expired: 'मुदत संपली',
    favorites_title_1: 'तुमचे',
    favorites_title_2: 'आवडते',
    favorites_sub: 'सेव्ह केलेले डील्स कधीही पहा',
    favorites_syncing: 'डेटा सिंक होत आहे',
    favorites_empty_title: 'लिस्ट रिकामी आहे',
    favorites_empty_sub: 'हार्ट आयकॉनवर क्लिक करून डील्स सेव्ह करा.',
    profile_elite_member: 'एलिट मेंबर',
    profile_verif_hub: 'व्हेरिफिकेशन हब',
    profile_verif_sub: 'व्हिजिट्स व्हेरिफाय करा',
    profile_edit: 'प्रोफाईल संपादित करा',
    profile_edit_store: 'दुकानाची माहिती संपादित करा',
    profile_favs: 'माझे आवडते डील्स',
    profile_invite_friend: 'मित्राला आमंत्रित करा',
    profile_invite_partner: 'भागीदाराला आमंत्रित करा',
    profile_invite_placeholder: 'ईमेल किंवा फोन नंबर',
    profile_invite_success: 'आमंत्रण पाठवण्यात आले',
    profile_help: 'मदत आणि अभिप्राय',
    profile_support_hub: 'सपोर्ट हब',
    profile_console: 'स्टोर कन्सोल',
    profile_payments: 'पमेंट',
    profile_subscriptions: 'माझे सबस्क्रिप्शन',
    profile_bank_verification: 'बँक पडताळणी', // NEW translation key
    profile_verified_merchant: 'व्हेरिफाईड व्यापारी',
    store_search_title: 'स्टोअर', // NEW
    store_search_sub: 'शोध', // NEW
    store_search_hint: 'विशिष्ट रिटेल नोड्स शोधा', // NEW
    store_search_placeholder: 'स्टोअरचे नाव किंवा पत्ता शोधा', // NEW
    store_search_no_results: 'કોઈ સ્ટોર મળ્યું નથી.', // NEW
    store_search_adjust_query: 'तुमची शोध क्वेरी समायोजित करण्याचा प्रयत्न करा.', // NEW
  },
  gu: {
    app_name: 'ડીલપ્રો',
    login_header: 'સ્માર્ટ ડિસ્કવરી',
    login_sub: 'તમારી નજીકના વિશિષ્ટ ડીલ્સ અને ડિસ્કવન્ટ મેળવો.',
    login_placeholder_id: 'યુઝરનેમ / ઇમેઇલ',
    login_placeholder_pass: 'પાસવર્ડ',
    login_btn: 'સાઇન ઇન',
    login_forgot: 'પાસવર્ડ ભૂલી ગયા છો?',
    login_register_hint: 'ગ્રીડ પર નવા છો?',
    login_register_action: 'ઓળખ બનાવો',
    home_deals: 'ડીલ્સ',
    home_near_you: 'તમારી નજીક',
    home_daily_waves: 'દૈનિક ઓફર્સ',
    home_see_all: 'બધા ડીલ્સ અહીં જુઓ',
    home_adjust_range: 'વિસ્તાર બદલો',
    lang_select_title: 'ભાષા પસંદ કરો',
    lang_select_sub: 'સારા અનુભવ માટે તમારી ભાષા પસંદ કરો',
    reg_title: 'ગ્રીડમાં જોડાઓ',
    reg_consumer: 'ગ્રાહક',
    reg_merchant: 'વેપારી',
    reg_choose_account: 'શરૂ કરવા માટે તમારા ખાતાનો પ્રકાર પસંદ કરો',
    reg_consumer_desc: 'સ્થાનિક ડીલ્સ શોધવા અને પૈસા બચાવવા માટે નેટવર્કમાં જોડાઓ',
    reg_merchant_desc: 'DealPro ડિજિટલ તરંગો સાથે તમારા વ્યવસાયને સશક્ત બનાવો',
    reg_have_account: 'પહેલેથી જ ખાતું છે?',
    reg_back_login: 'લૉગિન પર પાછા જાઓ',
    reg_fullname: 'પૂરું નામ',
    reg_username: 'યુઝરનેમ',
    reg_email: 'ઇમેઇલ સરનામું',
    reg_password: 'પાસવર્ડ',
    reg_is_owner: 'તમે દુકાનના માલિક છો?',
    reg_brand: 'મુખ્ય સ્ટોરનું નામ - GST રજીસ્ટર્ડ',
    reg_category: 'વ્યવસાય શ્રેણી',
    reg_locations: 'દુકાનનું સ્થાન',
    reg_store_name_label: 'સ્ટોરનું નામ (દા.ત. મેઇન સ્ટ્રીટ બ્રાન્ચ)', // NEW
    reg_street: 'સરનામું',
    reg_state: 'રાજ્ય',
    reg_city: 'શહેર',
    reg_hours: 'કામકાજના કલાકો',
    reg_24h: '૨૪ કલાક',
    reg_opens: 'ખુલવાનો સમય',
    reg_closes: 'બંધ થવાનો સમય',
    reg_landmark: 'લેન્ડમાર્ક (વૈકલ્પિક)',
    reg_use_my_loc: 'મારું લોકેશન વાપરો',
    reg_sync_verified: 'સિંક સફળ',
    reg_add_outlet: 'બીજું આઉટલેટ ઉમેરો',
    reg_gstin: 'GSTIN',
    reg_pan: 'PAN કાર્ડ',
    reg_submit: 'ખાતું બનાવો',
    reg_verify: 'ચકાસો',
    loc_title: 'શોધ પરિમાણો',
    loc_sub: 'ગ્રીડ સ્કેનિંગ લોજિક',
    loc_radius: 'શોધ ત્રિજ્યા',
    loc_gps: 'જીપીએસ ટ્રેકિંગ',
    loc_manual: 'મેન્યુઅલ ગ્રીડ',
    loc_region: 'રાજ્ય પસંદ કરો',
    loc_city: 'શહેર પસંદ કરો',
    loc_area: 'વિસ્તાર પસંદ કરો',
    loc_scan_btn: 'વિસ્તાર સ્કેન કરો',
    loc_syncing: 'સિંક થઈ રહ્યું છે...',
    loc_resolving: 'લોકેશન શોધી રહ્યું છે',
    loc_locked: 'સિગ્નલ લોક થયું',
    loc_awaiting: 'લોકેશનની રાહ જોવાય છે',
    onboarding_1_headline: "સ્થાનિક શોધ",
    onboarding_1_sub: "ચોક્કસ જીપીએસ લોજિક સાથે તમારી નજીકની ખાસ ઓફર્સ શોધો.",
    onboarding_1_tag: "પ્રોક્સિમિટી ઇન્ટેલિજન્સ",
    onboarding_2_headline: "ફ્લેશ સેલ્સ",
    onboarding_2_sub: "વેપારીઓની ઓફર્સ પૂરી થાય તે પહેલાં તેનો લાભ લો.",
    onboarding_2_tag: "સમયની બચત",
    onboarding_3_headline: "વિશ્વાસપાત્રતા",
    onboarding_3_sub: "વેરિફાઇડ નોડ્સ અને સુરક્ષિત વાઉચર પ્રોટોકોલ તમને શ્રેષ્ઠ અનુભવ આપશે.",
    onboarding_3_tag: "ગ્રીડ સુરક્ષા",
    home_daily: 'આજની ડીલ',
    home_local_area: 'સ્થાનિક વિસ્તાર',
    home_your_sector: 'તમારો સેક્ટર',
    home_deal_singular: 'ડીલ',
    home_deals_plural: 'ડીલ્સ',
    home_in: 'માં',
    home_no_deals_sector: 'આ સેક્ટરમાં હાલમાં ઓફર્સ નથી.',
    home_view_all: 'બધું જુઓ',
    home_syncing_grid: 'ગ્રીડ સિંક થઈ રહ્યું છે',
    details_redeem_btn: 'અત્યારે મેળવો',
    details_verifying: 'ચકાસણી થઈ રહી છે...',
    details_activating_for: 'રિવોર્ડ સક્રિય થઈ રહ્યો છે:',
    details_protocol: 'કેમ્પેઈન પ્રોટોકોલ',
    details_visit_intel: 'વિઝિટ ઇન્ટેલિજન્સ',
    details_start_gps: 'જીપીએસ શરૂ કરો',
    details_coordinates: 'દુકાનનું લોકેશન',
    details_landmark: 'નજીકની નિશાની',
    details_op_window: 'કામકાજના કલાકો',
    details_verified_node: 'વેરિફાઇડ ડીલપ્રો નોડ',
    details_instance_id: 'આઈડી નંબર',
    details_id_verified: 'ઓળખની પુષ્ટિ થઈ છે',
    details_present_counter: 'કાઉન્ટર પર બતાવો',
    details_exit_btn: 'બહાર નીકળો',
    history_title_1: 'રિડેમ્પશન',
    history_title_2: 'ઇતિહાસ',
    history_sub: 'તમારા રિડેમ્પશન',
    history_active_nodes: 'પરિણામો',
    history_rewards_label: 'રિવોર્ડ્સ',
    history_tab_all: 'બધા રિવોર્ડ્સ',
    history_tab_pending: 'મુલાકાતની રાહ',
    history_syncing: 'માહિતી સિંક થઈ રહી છે...',
    history_empty_title: 'વોલ્ટ સિંક થયો',
    history_empty_sub_pending: 'બધા ડીલ્સ વેરિફાઇડ છે. કોઈ મુલાકાત બાકી નથી.',
    history_empty_sub_all: 'તમારા ખાતામાં રિડેમ્પશન રેકોર્ડ્સ નથી.',
    history_search_btn: 'ગ્રીડ એક્સપ્લોર કરો',
    history_status_verified: 'વિઝિટ વેરિફાઇડ',
    history_status_awaiting: 'મુલાકાતની રાહ',
    history_page_label: 'પેજ',
    history_of: 'નું',
    history_ledger_end: 'રેકોર્ડ સમાપ્ત',
    history_voucher_security: 'વાઉચર સુરક્ષા',
    history_transaction_logged: 'વ્યવહાર નોંધાયો',
    history_present_counter: 'કાઉન્ટર પર બતાવો',
    history_ref_label: 'REF',
    history_voucher_node: 'વાઉચર નોડ',
    history_rate_exp: 'અનુભવ રેટ કરો',
    status_live: 'લાઇવ',
    status_expired: 'મુદત પૂરી થઈ',
    favorites_title_1: 'તમારા',
    favorites_title_2: 'મનપસંદ',
    favorites_sub: 'સેવ કરેલા ડીલ્સ ગમે ત્યારે જુઓ',
    favorites_syncing: 'ડેટા સિંક થઈ રહ્યો છે',
    favorites_empty_title: 'લિસ્ટ ખાલી છે',
    favorites_empty_sub: 'હાર્ટ આઇકોન પર ક્લિક કરીને ડીલ્સ સેવ કરો.',
    profile_elite_member: 'એલિટ મેમ્બર',
    profile_verif_hub: 'વેરિફિકેશન હબ',
    profile_verif_sub: 'વિઝિટ વેરિફાઇ કરો',
    profile_edit: 'પ્રોફાઇલ સંપાદિત કરો',
    profile_edit_store: 'દુકાનની પ્રોફાઇલ સંપાદિત કરો',
    profile_favs: 'મારા મનપસંદ ડીલ્સ',
    profile_invite_friend: 'મિત્રને આમંત્રણ આપો',
    profile_invite_partner: 'ભાગીદારને આમંત્રણ આપો',
    profile_invite_placeholder: 'ઇમેઇલ અથવા ફોન નંબર',
    profile_invite_success: 'આમંત્રણ મોકલવામાં આવ્યું',
    profile_help: 'મદદ અને પ્રતિભાવ',
    profile_support_hub: 'સપોર્ટ હબ',
    profile_console: 'સ્ટોર કન્સોલ',
    profile_payments: 'ચુકવણી',
    profile_subscriptions: 'મારા સબ્સ્ક્રિપ્શન',
    profile_bank_verification: 'બેંક ચકાસણી', // NEW translation key
    profile_verified_merchant: 'વેરિફાઇડ વેપારી',
    store_search_title: 'સ્ટોર', // NEW
    store_search_sub: 'શોધ', // NEW
    store_search_hint: 'વિશિષ્ટ રિટેલ નોડ્સ શોધો', // NEW
    store_search_placeholder: 'સ્ટોરનું નામ અથવા સરનામું શોધો', // NEW
    store_search_no_results: 'કોઈ સ્ટોર મળ્યું નથી.', // NEW
    store_search_adjust_query: 'તમારી શોધ ક્વેરીને સમાયોજિત કરવાનો પ્રયાસ કરો.', // NEW
  }
};

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
  getLocalizedText: (localizedData?: Record<string, string>, fallbackText?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocale] = useState<Locale>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const loadLanguagePreference = async () => {
      try {
        // Try to get from localStorage (web) or Capacitor Preferences (mobile)
        const storedLang = localStorage.getItem('userLanguagePreference');
        if (storedLang && ['en', 'kn', 'hi', 'ta', 'te', 'ml', 'bn', 'mr', 'gu'].includes(storedLang)) {
          setLocale(storedLang as Locale);
          console.log('[LanguageContext] Loaded language preference from storage:', storedLang);
        }
      } catch (error) {
        console.error('[LanguageContext] Failed to load language preference:', error);
      }
    };
    loadLanguagePreference();
  }, []);

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    try {
      localStorage.setItem('userLanguagePreference', locale);
      console.log('[LanguageContext] Saved language preference to storage:', locale);
    } catch (error) {
      console.error('[LanguageContext] Failed to save language preference:', error);
    }
  }, [locale]);

  const t = (key: string) => {
    return DICTIONARY[locale]?.[key] || DICTIONARY['en']?.[key] || key;
  };

  const getLocalizedText = (localizedData?: Record<string, any>, fallbackText?: string): string => {
    if (!localizedData || typeof localizedData !== 'object') return fallbackText || '';
    const localized = localizedData[locale];
    if (localized && typeof localized === 'string' && localized.trim() !== '') {
      return localized;
    }
    const englishFallback = localizedData['en'];
    if (englishFallback && typeof englishFallback === 'string' && englishFallback.trim() !== '') {
      return englishFallback;
    }
    return fallbackText || '';
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, getLocalizedText }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};