-- Globally-unique per-campaign code (format A123456) stored on each campaign.
-- Generated by the create-campaign edge function at deal creation. The partial
-- unique index ignores existing rows with a NULL code (so legacy campaigns don't
-- conflict) while guaranteeing uniqueness for all newly-coded campaigns.
ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS discount_code TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS campaigns_discount_code_unique
  ON campaigns (discount_code)
  WHERE discount_code IS NOT NULL;
